# Generated by Django 3.0.7 on 2020-10-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='comp_title10',
            field=models.CharField(blank=True, db_column='Comp_Title10', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='comp_title5',
            field=models.CharField(blank=True, db_column='Comp_Title5', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='comp_title6',
            field=models.CharField(blank=True, db_column='Comp_Title6', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='comp_title7',
            field=models.CharField(blank=True, db_column='Comp_Title7', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='comp_title8',
            field=models.CharField(blank=True, db_column='Comp_Title8', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='comp_title9',
            field=models.CharField(blank=True, db_column='Comp_Title9', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='logourl',
            field=models.TextField(blank=True, db_column='logoUrl', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='receipttemplate',
            field=models.CharField(blank=True, db_column='ReceiptTemplate', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_footer',
            field=models.BooleanField(db_column='SubRpt_Show_Footer', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_footer_cust_sign',
            field=models.BooleanField(db_column='SubRpt_Show_Footer_Cust_Sign', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_footer_cust_sign_sst',
            field=models.BooleanField(db_column='SubRpt_Show_Footer_Cust_Sign_SST', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_footer_sst',
            field=models.BooleanField(db_column='SubRpt_Show_Footer_SST', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_footer_tax',
            field=models.BooleanField(db_column='SubRpt_Show_Footer_Tax', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_footer_tax_sst',
            field=models.BooleanField(db_column='SubRpt_Show_Footer_Tax_SST', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_footer_trmt_available',
            field=models.BooleanField(db_column='SubRpt_Show_Footer_Trmt_Available', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_footer_trmt_available_sst',
            field=models.BooleanField(db_column='SubRpt_Show_Footer_Trmt_Available_SST', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_footerremark',
            field=models.BooleanField(db_column='SubRpt_Show_FooterRemark', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_footerremark_sst',
            field=models.BooleanField(db_column='SubRpt_Show_FooterRemark_SST', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_gst_summary',
            field=models.BooleanField(db_column='SubRpt_Show_GST_Summary', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_tax_summary_sst',
            field=models.BooleanField(db_column='SubRpt_Show_Tax_Summary_SST', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='subrpt_show_title',
            field=models.BooleanField(db_column='SubRpt_Show_Title', null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
