# Generated by Django 3.0.7 on 2020-10-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='numberofappointments',
            field=models.IntegerField(db_column='numberOfAppointments', null=True),
        ),
    ]
