# Generated by Django 3.0.7 on 2020-10-09 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_auto_20201009_0626'),
        ('cl_app', '0002_auto_20201009_0613'),
        ('cl_table', '0004_appointment_numberofappointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ItemSite_Codeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Room_Codeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.Room'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='islate',
            field=models.BooleanField(db_column='isLate', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='isnotifiedonce',
            field=models.BooleanField(blank=True, db_column='isNotifiedOnce', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='isnotifiedtwice',
            field=models.BooleanField(blank=True, db_column='isNotifiedTwice', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='remark_pts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sec_status',
            field=models.CharField(blank=True, choices=[('Rescheduled', 'Rescheduled'), ('Notified Once', 'Notified Once'), ('Notified Twice', 'Notified Twice')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_cancel',
            field=models.BooleanField(db_column='Appt_Cancel', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_comfirm',
            field=models.BooleanField(db_column='Appt_Comfirm', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='Appt_Created_Date', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_created_time',
            field=models.DateTimeField(auto_now_add=True, db_column='Appt_Created_Time', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_date',
            field=models.DateField(blank=True, db_column='Appt_date', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_fr_time',
            field=models.TimeField(blank=True, db_column='Appt_Fr_time', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_isactive',
            field=models.BooleanField(db_column='Appt_Isactive', default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_status',
            field=models.CharField(blank=True, choices=[('Booking', 'Booking'), ('Waiting', 'Waiting List'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Arrived', 'Arrived'), ('Done', 'Done'), ('LastMinCancel', 'Cancelled Last Minute'), ('Late', 'Late'), ('No Show', 'No Show')], db_column='Appt_Status', default='Booking', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_to_time',
            field=models.TimeField(blank=True, db_column='Appt_To_time', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='booking',
            field=models.BooleanField(db_column='Booking', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_consultant',
            field=models.BooleanField(db_column='IS_Consultant', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_enrollment',
            field=models.BooleanField(db_column='IS_Enrollment', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_hq',
            field=models.BooleanField(db_column='IS_HQ', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_missconsultant',
            field=models.BooleanField(db_column='IS_MISSConsultant', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_missconsultantb',
            field=models.BooleanField(db_column='IS_MISSConsultantB', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='is_noshow',
            field=models.BooleanField(db_column='IS_NoShow', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='isend_time',
            field=models.BooleanField(db_column='IsEnd_Time', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='lastmincancel',
            field=models.BooleanField(db_column='LastMinCancel', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='modified_lock',
            field=models.BooleanField(db_column='Modified_Lock', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='new',
            field=models.BooleanField(db_column='New', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='onlineappointment',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='remind_user',
            field=models.BooleanField(db_column='Remind_User', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='requesttherapist',
            field=models.BooleanField(db_column='requestTherapist', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='update_status',
            field=models.IntegerField(db_column='Update_Status', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='waiting',
            field=models.BooleanField(db_column='Waiting', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='walkin',
            field=models.BooleanField(db_column='WalkIn', null=True),
        ),
    ]
