# Generated by Django 3.0.7 on 2020-10-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0006_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='gst_item_code',
            field=models.CharField(blank=True, db_column='GST_Item_Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='istnc',
            field=models.BooleanField(blank=True, db_column='isTnc', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='postatus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='sst_item_code',
            field=models.CharField(blank=True, db_column='SST_Item_Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='workcommholder',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='autocustdisc',
            field=models.BooleanField(db_column='AutoCustDisc', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='autoproportion',
            field=models.BooleanField(db_column='AutoProportion', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='have_package_disc',
            field=models.BooleanField(db_column='Have_Package_Disc', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_allow_foc',
            field=models.BooleanField(db_column='IS_ALLOW_FOC', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_gst',
            field=models.BooleanField(db_column='IS_GST', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_have_tax',
            field=models.BooleanField(db_column='IS_HAVE_TAX', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='is_open_prepaid',
            field=models.BooleanField(db_column='IS_OPEN_PREPAID', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_foc',
            field=models.BooleanField(db_column='Item_FOC', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_havechild',
            field=models.BooleanField(db_column='item_haveChild', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_isactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='limitservice_flexionly',
            field=models.BooleanField(db_column='LimitService_FlexiOnly', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='mixbrand',
            field=models.BooleanField(db_column='MIXBRAND', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='service_cost_percent',
            field=models.BooleanField(db_column='Service_Cost_Percent', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='service_expire_active',
            field=models.BooleanField(db_column='Service_Expire_Active', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='treatment_limit_active',
            field=models.BooleanField(db_column='Treatment_Limit_Active', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='value_applytochild',
            field=models.BooleanField(db_column='Value_ApplyToChild', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='voucher_isvalid_until_date',
            field=models.BooleanField(db_column='Voucher_IsValid_Until_Date', null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='voucher_value_is_amount',
            field=models.BooleanField(db_column='Voucher_Value_Is_Amount', null=True),
        ),
    ]
