# Generated by Django 3.0.7 on 2020-10-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0007_auto_20201009_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentAccount',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cust_code', models.CharField(db_column='Cust_Code', max_length=20)),
                ('sa_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(db_column='Description', max_length=100)),
                ('ref_no', models.CharField(db_column='Ref_No', max_length=20)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=10, null=True)),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('balance', models.FloatField(db_column='Balance')),
                ('user_name', models.CharField(blank=True, db_column='User_Name', max_length=50, null=True)),
                ('sa_time', models.DateTimeField(blank=True, null=True)),
                ('ref_transacno', models.CharField(blank=True, db_column='Ref_Transacno', max_length=20, null=True)),
                ('sa_transacno', models.CharField(max_length=20)),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('outstanding', models.FloatField(blank=True, db_column='Outstanding', null=True)),
                ('deposit', models.FloatField(blank=True, db_column='Deposit', null=True)),
                ('treatment_parentcode', models.CharField(blank=True, db_column='Treatment_ParentCode', max_length=20, null=True)),
                ('treatment_code', models.CharField(blank=True, db_column='Treatment_Code', max_length=20, null=True)),
                ('cas_logno', models.CharField(blank=True, max_length=20, null=True)),
                ('sa_status', models.CharField(blank=True, max_length=5, null=True)),
                ('mac_code', models.CharField(blank=True, max_length=15, null=True)),
                ('cas_name', models.CharField(blank=True, max_length=60, null=True)),
                ('sa_staffno', models.CharField(max_length=100)),
                ('sa_staffname', models.CharField(blank=True, max_length=600, null=True)),
                ('next_paydate', models.DateTimeField(blank=True, db_column='Next_PayDate', null=True)),
                ('hasduedate', models.BooleanField(db_column='HasDueDate')),
                ('dt_lineno', models.IntegerField(db_column='dt_LineNo')),
                ('lpackage', models.BooleanField(db_column='lPackage')),
                ('package_code', models.CharField(blank=True, db_column='Package_Code', max_length=50, null=True)),
                ('site_code', models.CharField(db_column='Site_Code', max_length=50)),
                ('treat_code', models.CharField(db_column='Treat_Code', max_length=50)),
            ],
            options={
                'db_table': 'Treatment_Account',
            },
        ),
    ]
