# Generated by Django 3.0.7 on 2020-10-09 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_auto_20201009_0626'),
        ('cl_app', '0002_auto_20201009_0613'),
        ('cl_table', '0008_treatmentaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentaccount',
            name='Site_Codeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist'),
        ),
        migrations.AddField(
            model_name='treatmentaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentaccount',
            name='focreason',
            field=models.TextField(blank=True, db_column='focReason', null=True),
        ),
        migrations.AddField(
            model_name='treatmentaccount',
            name='itemcart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart'),
        ),
        migrations.AddField(
            model_name='treatmentaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='balance',
            field=models.FloatField(db_column='Balance', null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='cust_code',
            field=models.CharField(db_column='Cust_Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='description',
            field=models.CharField(db_column='Description', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='dt_lineno',
            field=models.IntegerField(db_column='dt_LineNo', null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='hasduedate',
            field=models.BooleanField(db_column='HasDueDate', null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='lpackage',
            field=models.BooleanField(db_column='lPackage', null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='ref_no',
            field=models.CharField(db_column='Ref_No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='sa_staffno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='sa_status',
            field=models.CharField(blank=True, choices=[('SA', 'SA'), ('VT', 'VT'), ('SU', 'SU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='sa_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='sa_transacno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='site_code',
            field=models.CharField(db_column='Site_Code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='treat_code',
            field=models.CharField(db_column='Treat_Code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Top Up', 'Top Up'), ('Sales', 'Sales')], db_column='Type', max_length=10, null=True),
        ),
    ]
