# Generated by Django 3.0.7 on 2020-10-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0009_auto_20201009_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holditemdetail',
            fields=[
                ('hi_no', models.AutoField(db_column='HI_no', primary_key=True, serialize=False)),
                ('sa_date', models.DateTimeField(blank=True, null=True)),
                ('sa_time', models.DateTimeField(blank=True, null=True)),
                ('cas_logno', models.CharField(blank=True, db_column='Cas_LogNo', max_length=50, null=True)),
                ('itemsite_code', models.CharField(db_column='ItemSite_Code', max_length=50)),
                ('sa_transacno', models.CharField(db_column='sa_TransacNo', max_length=50)),
                ('transacamt', models.FloatField(blank=True, db_column='TRANSACAMT', null=True)),
                ('itemno', models.CharField(db_column='ItemNo', max_length=50)),
                ('hi_staffno', models.CharField(blank=True, db_column='HI_staffNo', max_length=50, null=True)),
                ('hi_itemdesc', models.CharField(blank=True, db_column='HI_ItemDesc', max_length=200, null=True)),
                ('hi_price', models.FloatField(blank=True, db_column='HI_Price', null=True)),
                ('hi_amt', models.FloatField(blank=True, db_column='HI_Amt', null=True)),
                ('hi_qty', models.IntegerField(blank=True, db_column='HI_Qty', null=True)),
                ('hi_discamt', models.FloatField(blank=True, db_column='HI_discAmt', null=True)),
                ('hi_discpercent', models.FloatField(blank=True, db_column='HI_discPercent', null=True)),
                ('hi_discdesc', models.CharField(blank=True, db_column='HI_discDesc', max_length=100, null=True)),
                ('hi_staffname', models.CharField(blank=True, db_column='HI_StaffName', max_length=50, null=True)),
                ('hi_lineno', models.IntegerField(db_column='HI_LineNo')),
                ('hi_uom', models.CharField(blank=True, db_column='HI_UOM', max_length=50, null=True)),
                ('hold_item', models.BooleanField(db_column='Hold_Item')),
                ('hi_deposit', models.FloatField(blank=True, db_column='HI_deposit', null=True)),
                ('holditemqty', models.IntegerField(blank=True, db_column='HoldItemQty', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('sa_custno', models.CharField(blank=True, db_column='sa_CustNo', max_length=50, null=True)),
                ('sa_custname', models.CharField(blank=True, db_column='sa_Custname', max_length=50, null=True)),
                ('history_line', models.IntegerField(db_column='History_Line')),
                ('hold_type', models.CharField(blank=True, db_column='Hold_Type', max_length=50, null=True)),
                ('product_issues_no', models.CharField(db_column='Product_Issues_No', max_length=20)),
            ],
            options={
                'db_table': 'HoldItemDetail',
            },
        ),
    ]
