# Generated by Django 3.0.7 on 2020-10-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0010_holditemdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='holditemdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='holditemdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='holditemdetail',
            name='hi_lineno',
            field=models.IntegerField(db_column='HI_LineNo', null=True),
        ),
        migrations.AlterField(
            model_name='holditemdetail',
            name='history_line',
            field=models.IntegerField(db_column='History_Line', null=True),
        ),
        migrations.AlterField(
            model_name='holditemdetail',
            name='hold_item',
            field=models.BooleanField(db_column='Hold_Item', null=True),
        ),
        migrations.AlterField(
            model_name='holditemdetail',
            name='itemno',
            field=models.CharField(db_column='ItemNo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='holditemdetail',
            name='itemsite_code',
            field=models.CharField(db_column='ItemSite_Code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='holditemdetail',
            name='product_issues_no',
            field=models.CharField(db_column='Product_Issues_No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='holditemdetail',
            name='sa_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='holditemdetail',
            name='sa_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='holditemdetail',
            name='sa_transacno',
            field=models.CharField(db_column='sa_TransacNo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='holditemdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('Close', 'Close'), ('VOID', 'VOID')], db_column='Status', max_length=50, null=True),
        ),
    ]
