# Generated by Django 3.0.7 on 2020-10-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0002_auto_20201009_0613'),
        ('cl_table', '0012_poshaud'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshaud',
            name='ItemSite_Codeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist'),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='deliveryaddress',
            field=models.IntegerField(blank=True, db_column='deliveryAddress', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='deliverystatus',
            field=models.IntegerField(blank=True, db_column='deliveryStatus', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='earn_pts',
            field=models.FloatField(blank=True, db_column='Earn_pts', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='expire_soon_date_1',
            field=models.DateTimeField(blank=True, db_column='Expire_Soon_Date_1', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='expire_soon_date_2',
            field=models.DateTimeField(blank=True, db_column='Expire_Soon_Date_2', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='expire_soon_date_3',
            field=models.DateTimeField(blank=True, db_column='Expire_Soon_Date_3', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='expire_soon_date_4',
            field=models.DateTimeField(blank=True, db_column='Expire_Soon_Date_4', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='expire_soon_date_5',
            field=models.DateTimeField(blank=True, db_column='Expire_Soon_Date_5', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='expire_soon_point_1',
            field=models.FloatField(blank=True, db_column='Expire_Soon_Point_1', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='expire_soon_point_2',
            field=models.FloatField(blank=True, db_column='Expire_Soon_Point_2', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='expire_soon_point_3',
            field=models.FloatField(blank=True, db_column='Expire_Soon_Point_3', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='expire_soon_point_4',
            field=models.FloatField(blank=True, db_column='Expire_Soon_Point_4', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='expire_soon_point_5',
            field=models.FloatField(blank=True, db_column='Expire_Soon_Point_5', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='expire_soon_remark',
            field=models.CharField(blank=True, db_column='Expire_Soon_Remark', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='expire_soon_remark_point',
            field=models.FloatField(blank=True, db_column='Expire_Soon_Remark_Point', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='onlinepurchase',
            field=models.BooleanField(blank=True, db_column='onlinePurchase', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='trans_outstanding',
            field=models.FloatField(blank=True, db_column='Trans_Outstanding', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='trans_packagecode',
            field=models.CharField(blank=True, db_column='Trans_PackageCode', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='trans_pay',
            field=models.FloatField(blank=True, db_column='Trans_Pay', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='trans_value',
            field=models.FloatField(blank=True, db_column='Trans_Value', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='transignurl',
            field=models.TextField(blank=True, db_column='tranSignUrl', null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='used_pts',
            field=models.FloatField(blank=True, db_column='Used_pts', null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='appt_time',
            field=models.TimeField(blank=True, db_column='Appt_Time', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='cas_logno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='holditemqty',
            field=models.IntegerField(db_column='HoldItemQty', null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='isvoid',
            field=models.BooleanField(db_column='IsVoid', null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='itemsite_code',
            field=models.CharField(db_column='ItemSite_Code', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='sa_custno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='sa_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='sa_status',
            field=models.CharField(blank=True, choices=[('SA', 'SA'), ('VT', 'VT'), ('SU', 'SU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='sa_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='sa_transacno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='sa_transacno_type',
            field=models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Redeem Service', 'Redeem Service'), ('Non Sales', 'Non Sales'), ('Void Transaction', 'Void Transaction')], db_column='SA_TransacNo_Type', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='walkin',
            field=models.BooleanField(db_column='WalkIn', null=True),
        ),
    ]
