# Generated by Django 3.0.7 on 2020-10-09 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0002_auto_20201009_0613'),
        ('custom', '0002_auto_20201009_0626'),
        ('cl_table', '0014_posdaud'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdaud',
            name='Appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Appointment'),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='ItemSite_Codeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist'),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='dt_td_tax_amt',
            field=models.FloatField(blank=True, db_column='dt_TD_Tax_Amt', null=True),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='dt_topup_new_outs_amt',
            field=models.FloatField(blank=True, db_column='dt_TopUp_New_Outs_Amt', null=True),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='dt_topup_old_outs_amt',
            field=models.FloatField(blank=True, db_column='dt_TopUp_Old_Outs_Amt', null=True),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='earnedpoints',
            field=models.DecimalField(blank=True, db_column='earnedPoints', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='earnedtype',
            field=models.CharField(blank=True, db_column='earnedType', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='itemcart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart'),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='redeempoints',
            field=models.DecimalField(blank=True, db_column='redeemPoints', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='redeemtype',
            field=models.CharField(blank=True, db_column='redeemType', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='staffs',
            field=models.CharField(db_column='Staffs', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='trmt_bal',
            field=models.FloatField(blank=True, db_column='Trmt_Bal', null=True),
        ),
        migrations.AddField(
            model_name='posdaud',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='Appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Appointment'),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='appt_time',
            field=models.TimeField(blank=True, db_column='Appt_Time', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='cas_logno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='deduct_commission',
            field=models.BooleanField(blank=True, db_column='Deduct_Commission', null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='dt_itemdesc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='dt_lineno',
            field=models.IntegerField(blank=True, db_column='dt_LineNo', null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='dt_status',
            field=models.CharField(blank=True, choices=[('SA', 'SA'), ('VT', 'VT'), ('SU', 'SU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='first_trmt_done',
            field=models.BooleanField(blank=True, db_column='First_Trmt_Done', null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='hold_item',
            field=models.BooleanField(blank=True, db_column='Hold_Item', null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='hold_item_out',
            field=models.BooleanField(blank=True, db_column='Hold_Item_Out', null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='isfoc',
            field=models.BooleanField(blank=True, db_column='IsFoc', null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='itemsite_code',
            field=models.CharField(blank=True, db_column='ItemSite_Code', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='record_detail_type',
            field=models.CharField(blank=True, choices=[('SERVICE', 'SERVICE'), ('TD', 'TD'), ('Product', 'Product'), ('Prepaid', 'Prepaid'), ('TP Service', 'TP Service'), ('TP Product', 'TP Product'), ('TP Prepaid', 'TP Prepaid'), ('Package', 'Package')], db_column='Record_Detail_Type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='sa_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='sa_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='sa_transacno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='st_ref_treatmentcode',
            field=models.CharField(blank=True, db_column='ST_Ref_TreatmentCode', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='update_prepaid_bonus',
            field=models.BooleanField(blank=True, db_column='Update_Prepaid_Bonus', null=True),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='voucher_link_cust',
            field=models.BooleanField(blank=True, db_column='Voucher_Link_Cust', null=True),
        ),
    ]
