# Generated by Django 3.0.7 on 2020-10-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0015_auto_20201009_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosTaud',
            fields=[
                ('pay_no', models.AutoField(primary_key=True, serialize=False)),
                ('mac_code', models.CharField(blank=True, max_length=15, null=True)),
                ('sa_date', models.DateTimeField(blank=True, null=True)),
                ('sa_time', models.DateTimeField(blank=True, null=True)),
                ('sa_transacno', models.CharField(max_length=20)),
                ('cas_logno', models.CharField(max_length=20)),
                ('pay_group', models.CharField(blank=True, max_length=40, null=True)),
                ('pay_type', models.CharField(blank=True, max_length=30, null=True)),
                ('pay_desc', models.CharField(blank=True, db_column='pay_Desc', max_length=200, null=True)),
                ('pay_tendamt', models.FloatField(blank=True, null=True)),
                ('pay_tendrate', models.FloatField(blank=True, null=True)),
                ('pay_tendcurr', models.CharField(blank=True, max_length=10, null=True)),
                ('pay_amt', models.FloatField(blank=True, null=True)),
                ('pay_amtrate', models.FloatField(blank=True, null=True)),
                ('pay_amtcurr', models.CharField(blank=True, max_length=10, null=True)),
                ('pay_rem1', models.CharField(blank=True, max_length=200, null=True)),
                ('pay_rem2', models.CharField(blank=True, max_length=200, null=True)),
                ('pay_rem3', models.CharField(blank=True, max_length=200, null=True)),
                ('pay_rem4', models.CharField(blank=True, max_length=200, null=True)),
                ('pay_status', models.BooleanField()),
                ('pay_actamt', models.FloatField(blank=True, null=True)),
                ('itemsite_code', models.CharField(db_column='ItemSIte_Code', max_length=10)),
                ('paychange', models.FloatField(blank=True, db_column='PayChange', null=True)),
                ('dt_lineno', models.IntegerField()),
                ('pay_gst_amt_collect', models.FloatField(blank=True, db_column='Pay_GST_Amt_Collect', null=True)),
                ('pay_gst', models.FloatField(blank=True, db_column='PAY_GST', null=True)),
                ('voucher_name', models.CharField(blank=True, db_column='Voucher_Name', max_length=100, null=True)),
            ],
            options={
                'db_table': 'pos_taud',
            },
        ),
    ]
