# Generated by Django 3.0.7 on 2020-10-09 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0002_auto_20201009_0613'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cl_table', '0020_fmspw_securities'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmspw',
            name='LEVEL_ItmIDid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Securities'),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgcalldatechange',
            field=models.BooleanField(db_column='flgCallDateChange', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgcallmodule',
            field=models.BooleanField(db_column='flgCallModule', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flggiftmodule',
            field=models.BooleanField(db_column='flgGiftModule', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flghmsetting',
            field=models.BooleanField(blank=True, db_column='flgHMSetting', default=False, null=True),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgsales',
            field=models.BooleanField(db_column='flgSales', default=False, null=True),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='loginsite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist'),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='securities',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='securities',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgaccountinterface',
            field=models.BooleanField(db_column='flgAccountInterface', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgaddath',
            field=models.BooleanField(db_column='flgAddAth', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgadj',
            field=models.BooleanField(db_column='flgADJ', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgallcom',
            field=models.BooleanField(blank=True, db_column='flgAllCom', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgalldayendsettlement',
            field=models.BooleanField(blank=True, db_column='flgAllDayEndSettlement', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgallowblockappointment',
            field=models.BooleanField(db_column='flgAllowBlockAppointment', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgallowcardusage',
            field=models.BooleanField(db_column='flgAllowCardUsage', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgallowinsufficent',
            field=models.BooleanField(db_column='flgAllowInsufficent', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgallowtdexpiryservice',
            field=models.BooleanField(db_column='flgAllowTDExpiryService', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgappt',
            field=models.BooleanField(db_column='flgAppt', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgappteditath',
            field=models.BooleanField(db_column='flgApptEditAth', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgattn',
            field=models.BooleanField(db_column='flgAttn', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgchangeexpirydate',
            field=models.BooleanField(db_column='flgChangeExpiryDate', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgchangeunitprice',
            field=models.BooleanField(db_column='flgChangeUnitPrice', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgcustadd',
            field=models.BooleanField(blank=True, db_column='flgCustAdd', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgdelart',
            field=models.BooleanField(db_column='flgDelArt', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgdisc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgeditath',
            field=models.BooleanField(db_column='flgEditAth', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgemail',
            field=models.BooleanField(db_column='flgEmail', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgexchange',
            field=models.BooleanField(db_column='flgExchange', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgexpire',
            field=models.BooleanField(db_column='flgExpire', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgfoc',
            field=models.BooleanField(db_column='flgFOC', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flggrn',
            field=models.BooleanField(db_column='flgGRN', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgluckydraw',
            field=models.BooleanField(db_column='flgLuckyDraw', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgmclock',
            field=models.BooleanField(db_column='flgMClock', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgopendrawer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgoutletrequest',
            field=models.BooleanField(db_column='flgOutletRequest', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgoveridearstaff',
            field=models.BooleanField(db_column='flgOverideARStaff', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgphy',
            field=models.BooleanField(db_column='flgPHY', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgrefund',
            field=models.BooleanField(db_column='flgRefund', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgrefundcn',
            field=models.BooleanField(db_column='flgRefundCN', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgrefundpp',
            field=models.BooleanField(db_column='flgRefundPP', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgrevtrm',
            field=models.BooleanField(db_column='flgRevTrm', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgstockusagememo',
            field=models.BooleanField(db_column='flgStockUsageMemo', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgtfr',
            field=models.BooleanField(db_column='flgTFR', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgviewath',
            field=models.BooleanField(db_column='flgViewAth', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgviewcost',
            field=models.BooleanField(blank=True, db_column='flgViewCost', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgvoid',
            field=models.BooleanField(db_column='flgVoid', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='flgvoidcurrentday',
            field=models.BooleanField(db_column='flgVoidCurrentDay', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='lallowflgdelart',
            field=models.BooleanField(db_column='lallowFlgDelArt', default=False),
        ),
        migrations.AlterField(
            model_name='fmspw',
            name='pw_isactive',
            field=models.BooleanField(db_column='PW_Isactive', default=True),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_isactive',
            field=models.BooleanField(db_column='LEVEL_Isactive', default=True),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitanalysis',
            field=models.BooleanField(db_column='LEVEL_PermitAnalysis', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitappointment',
            field=models.BooleanField(db_column='LEVEL_PermitAppointment', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitattendance',
            field=models.BooleanField(db_column='LEVEL_PermitAttendance', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitclass',
            field=models.BooleanField(db_column='LEVEL_PermitClass', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitcreditor',
            field=models.BooleanField(db_column='LEVEL_PermitCreditor', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitcrm',
            field=models.BooleanField(db_column='LEVEL_PermitCrm', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitdept',
            field=models.BooleanField(db_column='LEVEL_PermitDept', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitdiscount',
            field=models.BooleanField(db_column='LEVEL_PermitDiscount', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitdiv',
            field=models.BooleanField(db_column='LEVEL_PermitDiv', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitforex',
            field=models.BooleanField(db_column='LEVEL_PermitForex', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitinventory',
            field=models.BooleanField(db_column='LEVEL_PermitInventory', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitmaintain',
            field=models.BooleanField(db_column='LEVEL_PermitMaintain', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitpaytable',
            field=models.BooleanField(db_column='LEVEL_PermitPaytable', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitpos',
            field=models.BooleanField(db_column='LEVEL_PermitPOS', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitpromo',
            field=models.BooleanField(db_column='LEVEL_PermitPromo', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitsecurity',
            field=models.BooleanField(db_column='LEVEL_PermitSecurity', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitsendmail',
            field=models.BooleanField(db_column='LEVEL_PermitSendmail', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitstaff',
            field=models.BooleanField(db_column='LEVEL_PermitStaff', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitstkadj',
            field=models.BooleanField(db_column='LEVEL_PermitStkAdj', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitstkquery',
            field=models.BooleanField(db_column='LEVEL_PermitStkQuery', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitstkreceive',
            field=models.BooleanField(db_column='LEVEL_PermitStkReceive', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitstktk',
            field=models.BooleanField(db_column='LEVEL_PermitStkTK', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitstktrans',
            field=models.BooleanField(db_column='LEVEL_PermitStkTrans', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitstkvar',
            field=models.BooleanField(db_column='LEVEL_PermitStkVar', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitstkwriteoff',
            field=models.BooleanField(db_column='LEVEL_PermitStkWriteOff', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permitstockitem',
            field=models.BooleanField(db_column='LEVEL_PermitStockItem', default=False),
        ),
        migrations.AlterField(
            model_name='securities',
            name='level_permituserlogin',
            field=models.BooleanField(db_column='LEVEL_PermitUserLogin', default=False),
        ),
    ]
