# Generated by Django 3.0.7 on 2020-10-09 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0024_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='brandpoints',
            field=models.FloatField(blank=True, db_column='BrandPoints', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='brandusedpoints',
            field=models.FloatField(blank=True, db_column='BrandUsedPoints', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='creditnote',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_bal_point',
            field=models.FloatField(blank=True, db_column='Cust_Bal_Point', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_consultant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_consultantname',
            field=models.CharField(blank=True, db_column='cust_consultantName', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_fb',
            field=models.CharField(blank=True, db_column='cust_FB', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_used_point',
            field=models.FloatField(blank=True, db_column='Cust_Used_Point', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='customersign',
            field=models.BinaryField(blank=True, db_column='customerSign', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='fcmtoken',
            field=models.CharField(blank=True, db_column='FCMToken', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='iseczema',
            field=models.BooleanField(blank=True, db_column='isEczema', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='issensitiveskin',
            field=models.BooleanField(blank=True, db_column='isSensitiveSkin', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_visit',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='medicalhistory',
            field=models.TextField(blank=True, db_column='medicalHistory', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='modifiedby',
            field=models.CharField(blank=True, db_column='modifiedBy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nickname',
            field=models.CharField(blank=True, db_column='NickName', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='oustanding_payment',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='passport',
            field=models.CharField(blank=True, db_column='Passport', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='patientno',
            field=models.CharField(blank=True, db_column='PatientNo', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='pdpastatus',
            field=models.BooleanField(blank=True, db_column='pdpaStatus', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='prepaid_card',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='productpoints',
            field=models.FloatField(blank=True, db_column='ProductPoints', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='productusedpoints',
            field=models.FloatField(blank=True, db_column='ProductUsedPoints', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='residencetype',
            field=models.CharField(blank=True, db_column='residenceType', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='servicepoints',
            field=models.FloatField(blank=True, db_column='ServicePoints', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='serviceusedpoints',
            field=models.FloatField(blank=True, db_column='ServiceUsedPoints', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='upcoming_appointments',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='voucher_available',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age_range0',
            field=models.BooleanField(db_column='Age_Range0', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age_range1',
            field=models.BooleanField(db_column='Age_Range1', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age_range2',
            field=models.BooleanField(db_column='Age_Range2', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age_range3',
            field=models.BooleanField(db_column='Age_Range3', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age_range4',
            field=models.BooleanField(db_column='Age_Range4', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='corporatecust',
            field=models.CharField(db_column='CorporateCust', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_blacklist',
            field=models.BooleanField(db_column='Cust_BlackList', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_code',
            field=models.CharField(db_column='Cust_code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_defaultlist',
            field=models.BooleanField(db_column='Cust_DefaultList', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_dob',
            field=models.DateField(blank=True, db_column='Cust_DOB', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_email',
            field=models.EmailField(blank=True, db_column='Cust_email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_isactive',
            field=models.BooleanField(db_column='Cust_isactive', default=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_maillist',
            field=models.BooleanField(db_column='Cust_MailList', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cust_point',
            field=models.FloatField(db_column='Cust_Point', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custallowsendsms',
            field=models.BooleanField(db_column='CustAllowSendSMS', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='dob_status',
            field=models.BooleanField(db_column='DOB_status', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='exp_status',
            field=models.BooleanField(db_column='Exp_Status', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='externalvipprofile',
            field=models.BooleanField(db_column='ExternalVipProfile', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='iscorporate',
            field=models.BooleanField(db_column='IsCorporate', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='join_status',
            field=models.BooleanField(db_column='Join_status', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='potential_cust',
            field=models.BooleanField(null=True),
        ),
    ]
