# Generated by Django 3.0.7 on 2020-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0028_auto_20201009_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_desc', models.CharField(blank=True, max_length=40, null=True)),
                ('itm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='CnRefund',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rfn_trans_no', models.CharField(blank=True, db_column='RFN_Trans_No', max_length=20, null=True)),
                ('cn_no', models.CharField(blank=True, db_column='CN_No', max_length=20, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=10, null=True)),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('staff_code', models.CharField(blank=True, db_column='Staff_Code', max_length=20, null=True)),
                ('transac_no', models.CharField(blank=True, db_column='Transac_No', max_length=20, null=True)),
                ('rfn_date', models.DateTimeField(blank=True, db_column='RFN_Date', null=True)),
                ('rfn_before_amt', models.FloatField(blank=True, db_column='RFN_Before_Amt', null=True)),
                ('rfn_adjust_amt', models.FloatField(blank=True, db_column='RFN_Adjust_Amt', null=True)),
                ('rfn_new_amt', models.FloatField(blank=True, db_column='RFN_New_Amt', null=True)),
            ],
            options={
                'db_table': 'CN_Refund',
            },
        ),
        migrations.CreateModel(
            name='CommType',
            fields=[
                ('comm_type_id', models.AutoField(db_column='Comm_Type_ID', primary_key=True, serialize=False)),
                ('comm_type_code', models.CharField(blank=True, db_column='Comm_Type_Code', max_length=20, null=True)),
                ('comm_type_desc', models.CharField(blank=True, db_column='Comm_Type_Desc', max_length=50, null=True)),
                ('comm_type_active', models.BooleanField(db_column='Comm_Type_Active')),
            ],
            options={
                'db_table': 'Comm_Type',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_desc', models.CharField(blank=True, max_length=40, null=True)),
                ('itm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sa_date', models.DateTimeField(blank=True, db_column='sa_Date', null=True)),
                ('treatment_code', models.CharField(db_column='Treatment_Code', max_length=20)),
                ('treatment_name', models.CharField(blank=True, db_column='Treatment_Name', max_length=200, null=True)),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('treatment_parentcode', models.CharField(blank=True, db_column='Treatment_ParentCode', max_length=20, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=20, null=True)),
                ('cust_code', models.CharField(blank=True, db_column='Cust_Code', max_length=50, null=True)),
                ('cust_name', models.CharField(blank=True, db_column='Cust_Name', max_length=100, null=True)),
                ('sa_transacno', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=10, null=True)),
                ('credit_code', models.CharField(db_column='Credit_Code', max_length=20)),
                ('balance', models.FloatField(blank=True, db_column='Balance', null=True)),
                ('deposit_type', models.CharField(blank=True, db_column='Deposit_Type', max_length=50, null=True)),
                ('site_code', models.CharField(db_column='Site_Code', max_length=50)),
                ('treat_code', models.CharField(blank=True, db_column='Treat_Code', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Credit_Note',
            },
        ),
        migrations.CreateModel(
            name='CustomerClass',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('class_code', models.CharField(blank=True, db_column='Class_Code', max_length=50, null=True)),
                ('class_desc', models.CharField(blank=True, db_column='Class_Desc', max_length=50, null=True)),
                ('class_isactive', models.BooleanField(blank=True, db_column='Class_Isactive', null=True)),
                ('class_product', models.FloatField(db_column='Class_Product')),
                ('class_service', models.FloatField(db_column='Class_Service')),
            ],
            options={
                'db_table': 'Customer_Class',
            },
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('itm_id', models.AutoField(db_column='ITM_ID', primary_key=True, serialize=False)),
                ('itm_code', models.CharField(blank=True, db_column='ITM_CODE', max_length=50, null=True)),
                ('itm_name', models.CharField(blank=True, db_column='ITM_NAME', max_length=50, null=True)),
                ('itm_isactive', models.BooleanField(db_column='ITM_ISACTIVE')),
            ],
            options={
                'db_table': 'DAYS',
            },
        ),
        migrations.CreateModel(
            name='EmpSocso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('emp_code', models.CharField(blank=True, db_column='Emp_Code', max_length=50, null=True)),
                ('emp_socso_employee', models.FloatField(blank=True, db_column='Emp_SOCSO_Employee', null=True)),
                ('emp_socso_employer', models.FloatField(blank=True, db_column='Emp_SOCSO_Employer', null=True)),
            ],
            options={
                'db_table': 'Emp_SOCSO',
            },
        ),
        migrations.CreateModel(
            name='EmpType',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type_code', models.CharField(blank=True, db_column='TYPE_CODE', max_length=20, null=True)),
                ('type_desc', models.CharField(blank=True, db_column='TYPE_DESC', max_length=50, null=True)),
                ('type_isactive', models.BooleanField(blank=True, db_column='TYPE_ISACTIVE', null=True)),
            ],
            options={
                'db_table': 'EMP_TYPE',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_name', models.CharField(blank=True, max_length=20, null=True)),
                ('itm_isactive', models.BooleanField()),
                ('itm_code', models.CharField(blank=True, db_column='ITM_CODE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='ItemStatus',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_code', models.CharField(blank=True, db_column='Status_Code', max_length=50, null=True)),
                ('status_desc', models.CharField(blank=True, db_column='Status_Desc', max_length=255, null=True)),
                ('status_short_desc', models.CharField(blank=True, db_column='Status_Short_Desc', max_length=255, null=True)),
                ('itm_isactive', models.BooleanField(db_column='itm_IsActive')),
                ('status_group_code', models.CharField(blank=True, db_column='Status_Group_Code', max_length=20, null=True)),
            ],
            options={
                'db_table': 'item_status',
            },
        ),
        migrations.CreateModel(
            name='Maritalstatus',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_name', models.CharField(blank=True, max_length=20, null=True)),
                ('itm_isactive', models.BooleanField()),
                ('itm_code', models.IntegerField(blank=True, db_column='ITM_CODE', null=True)),
            ],
            options={
                'db_table': 'MaritalStatus',
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_name', models.CharField(blank=True, max_length=50, null=True)),
                ('itm_isactive', models.BooleanField()),
                ('itm_code', models.CharField(blank=True, db_column='ITM_CODE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'NATIONALITY',
            },
        ),
        migrations.CreateModel(
            name='PrepaidAccount',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('pp_no', models.CharField(db_column='PP_NO', max_length=50)),
                ('pp_type', models.CharField(db_column='PP_TYPE', max_length=50)),
                ('pp_desc', models.CharField(blank=True, db_column='PP_DESC', max_length=50, null=True)),
                ('sa_date', models.DateTimeField(blank=True, db_column='SA_DATE', null=True)),
                ('start_date', models.DateTimeField(blank=True, db_column='START_DATE', null=True)),
                ('exp_date', models.DateTimeField(blank=True, db_column='EXP_DATE', null=True)),
                ('cust_code', models.CharField(blank=True, db_column='CUST_CODE', max_length=50, null=True)),
                ('cust_name', models.CharField(blank=True, db_column='CUST_NAME', max_length=50, null=True)),
                ('pp_amt', models.FloatField(blank=True, db_column='PP_AMT', null=True)),
                ('pp_bonus', models.FloatField(blank=True, db_column='PP_BONUS', null=True)),
                ('pp_total', models.FloatField(blank=True, db_column='PP_TOTAL', null=True)),
                ('transac_no', models.CharField(db_column='TRANSAC_NO', max_length=50)),
                ('item_no', models.CharField(db_column='ITEM_NO', max_length=50)),
                ('use_amt', models.FloatField(db_column='USE_AMT')),
                ('remain', models.FloatField(db_column='REMAIN')),
                ('ref1', models.CharField(blank=True, db_column='REF1', max_length=50, null=True)),
                ('ref2', models.CharField(blank=True, db_column='REF2', max_length=50, null=True)),
                ('status', models.BooleanField(db_column='STATUS')),
                ('site_code', models.CharField(db_column='SITE_CODE', max_length=50)),
                ('sa_status', models.CharField(blank=True, db_column='SA_STATUS', max_length=50, null=True)),
                ('exp_status', models.BooleanField(db_column='EXP_STATUS')),
                ('voucher_no', models.CharField(blank=True, db_column='VOUCHER_NO', max_length=50, null=True)),
                ('isvoucher', models.BooleanField(db_column='ISVOUCHER')),
                ('has_deposit', models.BooleanField(db_column='HAS_DEPOSIT')),
                ('topup_amt', models.FloatField(blank=True, db_column='TopUp_AMT', null=True)),
                ('outstanding', models.FloatField(db_column='Outstanding')),
                ('active_deposit_bonus', models.BooleanField(db_column='Active_Deposit_Bonus')),
                ('topup_no', models.CharField(db_column='TopUp_No', max_length=50)),
                ('topup_date', models.DateTimeField(blank=True, db_column='TopUp_Date', null=True)),
                ('line_no', models.BigIntegerField(db_column='Line_No')),
                ('edit_date', models.DateTimeField(db_column='Edit_Date')),
                ('cas_logno', models.CharField(blank=True, db_column='Cas_LogNo', max_length=50, null=True)),
                ('staff_name', models.CharField(blank=True, db_column='Staff_Name', max_length=50, null=True)),
                ('staff_no', models.CharField(blank=True, db_column='Staff_No', max_length=50, null=True)),
                ('pp_type2', models.CharField(blank=True, db_column='PP_TYPE2', max_length=20, null=True)),
                ('condition_type1', models.CharField(blank=True, db_column='Condition_TYPE1', max_length=20, null=True)),
                ('pos_daud_lineno', models.IntegerField(blank=True, db_column='POS_DAUD_LineNo', null=True)),
                ('mac_uid_ref', models.CharField(blank=True, db_column='MAC_UID_Ref', max_length=50, null=True)),
                ('lpackage', models.BooleanField(db_column='lPackage')),
                ('package_code', models.CharField(blank=True, db_column='Package_Code', max_length=50, null=True)),
                ('package_code_lineno', models.IntegerField(blank=True, db_column='Package_Code_LineNo', null=True)),
                ('prepaid_disc_type', models.CharField(blank=True, db_column='Prepaid_Disc_Type', max_length=20, null=True)),
                ('prepaid_disc_percent', models.FloatField(blank=True, db_column='Prepaid_Disc_Percent', null=True)),
            ],
            options={
                'db_table': 'Prepaid_Account',
            },
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_name', models.CharField(blank=True, max_length=20, null=True)),
                ('itm_isactive', models.BooleanField()),
                ('itm_code', models.CharField(blank=True, db_column='ITM_CODE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Races',
            },
        ),
        migrations.CreateModel(
            name='Religious',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_name', models.CharField(blank=True, max_length=20, null=True)),
                ('itm_isactive', models.BooleanField()),
                ('itm_code', models.CharField(blank=True, db_column='ITM_CODE', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Religious',
            },
        ),
        migrations.CreateModel(
            name='ReverseDtl',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('treatment_no', models.CharField(blank=True, db_column='Treatment_No', max_length=50, null=True)),
                ('treatment_desc', models.CharField(blank=True, db_column='Treatment_Desc', max_length=250, null=True)),
                ('treatment_price', models.FloatField(blank=True, db_column='Treatment_Price', null=True)),
                ('transac_no', models.CharField(blank=True, db_column='Transac_No', max_length=50, null=True)),
                ('reverse_no', models.CharField(blank=True, db_column='Reverse_No', max_length=50, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Reverse_Dtl',
            },
        ),
        migrations.CreateModel(
            name='ReverseHdr',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('reverse_no', models.CharField(blank=True, db_column='Reverse_No', max_length=50, null=True)),
                ('reverse_date', models.DateTimeField(blank=True, db_column='Reverse_Date', null=True)),
                ('reverse_time', models.DateTimeField(blank=True, db_column='Reverse_Time', null=True)),
                ('staff_code', models.CharField(blank=True, db_column='Staff_Code', max_length=50, null=True)),
                ('staff_name', models.CharField(blank=True, db_column='Staff_Name', max_length=50, null=True)),
                ('cust_code', models.CharField(blank=True, db_column='Cust_Code', max_length=50, null=True)),
                ('cust_name', models.CharField(blank=True, db_column='Cust_Name', max_length=50, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('has_adjustment', models.BooleanField(blank=True, db_column='Has_Adjustment', null=True)),
                ('adjustment_value', models.FloatField(blank=True, db_column='Adjustment_Value', null=True)),
                ('credit_note_amt', models.FloatField(blank=True, db_column='Credit_Note_Amt', null=True)),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=50, null=True)),
                ('remark', models.CharField(blank=True, db_column='Remark', max_length=50, null=True)),
                ('total_balance', models.FloatField(blank=True, db_column='Total_Balance', null=True)),
                ('ref_creditnote', models.CharField(blank=True, db_column='Ref_CreditNote', max_length=20, null=True)),
                ('reason1', models.CharField(blank=True, db_column='Reason1', max_length=50, null=True)),
                ('reason2', models.CharField(blank=True, db_column='Reason2', max_length=50, null=True)),
                ('reason3', models.CharField(blank=True, db_column='Reason3', max_length=50, null=True)),
                ('reason4', models.CharField(blank=True, db_column='Reason4', max_length=50, null=True)),
                ('reason_adj_value1', models.FloatField(blank=True, db_column='Reason_Adj_Value1', null=True)),
                ('reason_adj_value2', models.FloatField(blank=True, db_column='Reason_Adj_Value2', null=True)),
                ('reason_adj_value3', models.FloatField(blank=True, db_column='Reason_Adj_Value3', null=True)),
                ('reason_adj_value4', models.FloatField(blank=True, db_column='Reason_Adj_Value4', null=True)),
            ],
            options={
                'db_table': 'Reverse_Hdr',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('source_code', models.CharField(db_column='Source_Code', max_length=20)),
                ('source_desc', models.CharField(blank=True, db_column='Source_Desc', max_length=100, null=True)),
                ('source_isactive', models.BooleanField(db_column='Source_IsActive')),
            ],
            options={
                'db_table': 'Source',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('itm_id', models.AutoField(db_column='itm_ID', primary_key=True, serialize=False)),
                ('itm_desc', models.CharField(blank=True, max_length=40, null=True)),
                ('itm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_isactive', models.BooleanField()),
            ],
            options={
                'db_table': 'State',
            },
        ),
    ]
