# Generated by Django 3.0.7 on 2020-10-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0031_appointmentdetails_appttype_attntype_customervoucher_depositaccount_deposittype_focreason_gstsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='appttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='attntype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='attntype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customervoucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customervoucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='depositaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='depositaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='deposittype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='deposittype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='focreason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='focreason',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='gstsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='gstsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itembatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itembatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itembrand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itembrand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcolor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcolor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemfabric',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemfabric',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemlink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemlink',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemseason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemseason',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemsize',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemsize',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemsizepack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemsizepack',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemstocklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemstocklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemuom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemuom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='itemuomprice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemuomprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='packagedtl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='packagedtl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='packagehdr',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='packagehdr',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='prepaidaccountcondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prepaidaccountcondition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='prepaidopencondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prepaidopencondition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='prepaidvalidperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='prepaidvalidperiod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='receiptar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='stktrn',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='stktrn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='systemlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='systemloginlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='systemloginlog',
            name='log_terminalcode',
            field=models.CharField(blank=True, db_column='Log_TerminalCode', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='systemloginlog',
            name='mac_uid_ref',
            field=models.CharField(blank=True, db_column='MAC_UID_Ref', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemloginlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsetup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsetup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentprotocol',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentprotocol',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vouchervalidperiod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vouchervalidperiod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='appt_code',
            field=models.CharField(db_column='Appt_code', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointmentdetails',
            name='isactive',
            field=models.BooleanField(blank=True, db_column='isActive', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='appttype',
            name='appt_type_isactive',
            field=models.BooleanField(db_column='Appt_type_Isactive', default=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='attn_isactive',
            field=models.BooleanField(db_column='Attn_isactive', default=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='attn_spec_in',
            field=models.BooleanField(db_column='Attn_Spec_In', null=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='attn_spec_out',
            field=models.BooleanField(db_column='Attn_Spec_Out', null=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='show_when_breakin_on',
            field=models.BooleanField(db_column='Show_When_BreakIn_On', null=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='show_when_breakout_on',
            field=models.BooleanField(db_column='Show_When_BreakOut_On', null=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='show_when_dinnerin_on',
            field=models.BooleanField(db_column='Show_When_DinnerIn_On', null=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='show_when_dinnerout_on',
            field=models.BooleanField(db_column='Show_When_DinnerOut_On', null=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='show_when_lunchin_on',
            field=models.BooleanField(db_column='Show_When_LunchIn_On', null=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='show_when_lunchout_on',
            field=models.BooleanField(db_column='Show_When_LunchOut_On', null=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='show_when_norecord',
            field=models.BooleanField(db_column='Show_When_NoRecord', null=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='show_when_specialin_on',
            field=models.BooleanField(db_column='Show_When_SpecialIn_On', null=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='show_when_specialout_on',
            field=models.BooleanField(db_column='Show_When_SpecialOut_On', null=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='show_when_workin_on',
            field=models.BooleanField(db_column='Show_When_WorkIn_On', null=True),
        ),
        migrations.AlterField(
            model_name='attntype',
            name='show_when_workout_on',
            field=models.BooleanField(db_column='Show_When_WorkOut_On', null=True),
        ),
        migrations.AlterField(
            model_name='customervoucher',
            name='customermobile',
            field=models.CharField(db_column='customerMobile', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='cust_code',
            field=models.CharField(db_column='Cust_Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='dt_lineno',
            field=models.IntegerField(db_column='dt_LineNo', null=True),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='item_barcode',
            field=models.CharField(db_column='Item_Barcode', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='lpackage',
            field=models.BooleanField(db_column='lPackage', null=True),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='sa_transacno',
            field=models.CharField(db_column='sa_Transacno', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('deposit', 'Deposit'), ('top up', 'Top up')], db_column='Type', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='deposittype',
            name='card_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='deposittype',
            name='pay_desc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposittype',
            name='pos_taud_lineno',
            field=models.IntegerField(db_column='POS_TAUD_LineNo', null=True),
        ),
        migrations.AlterField(
            model_name='deposittype',
            name='sa_transacno',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='focreason',
            name='foc_reason_code',
            field=models.CharField(db_column='FOC_Reason_Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='focreason',
            name='foc_reason_isactive',
            field=models.BooleanField(db_column='FOC_Reason_IsActive', default=True),
        ),
        migrations.AlterField(
            model_name='gstsetting',
            name='isactive',
            field=models.BooleanField(blank=True, db_column='ISACTIVE', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='itembrand',
            name='itm_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itembrand',
            name='prepaid_brand',
            field=models.BooleanField(db_column='Prepaid_Brand', null=True),
        ),
        migrations.AlterField(
            model_name='itembrand',
            name='retail_product_brand',
            field=models.BooleanField(db_column='Retail_Product_Brand', null=True),
        ),
        migrations.AlterField(
            model_name='itembrand',
            name='voucher_brand',
            field=models.BooleanField(db_column='Voucher_Brand', null=True),
        ),
        migrations.AlterField(
            model_name='itembrand',
            name='voucher_for_sales',
            field=models.BooleanField(db_column='Voucher_For_Sales', null=True),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='color_isactive',
            field=models.BooleanField(db_column='Color_Isactive', default=True),
        ),
        migrations.AlterField(
            model_name='itemfabric',
            name='itm_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='item_code',
            field=models.CharField(db_column='ITEM_CODE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='itm_isactive',
            field=models.BooleanField(blank=True, db_column='Itm_IsActive', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemlink',
            name='link_code',
            field=models.CharField(db_column='LINK_CODE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemseason',
            name='season_isactive',
            field=models.BooleanField(db_column='Season_Isactive', default=True),
        ),
        migrations.AlterField(
            model_name='itemsize',
            name='size_isactive',
            field=models.BooleanField(db_column='Size_Isactive', default=True),
        ),
        migrations.AlterField(
            model_name='itemsizepack',
            name='sizepack_isactive',
            field=models.BooleanField(db_column='SizePack_Isactive', default=True),
        ),
        migrations.AlterField(
            model_name='itemstocklist',
            name='item_code',
            field=models.CharField(db_column='Item_Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='itm_removable',
            field=models.BooleanField(db_column='ITM_REMOVABLE', null=True),
        ),
        migrations.AlterField(
            model_name='itemuom',
            name='uom_isactive',
            field=models.BooleanField(blank=True, db_column='UOM_Isactive', default=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemuomprice',
            name='isactive',
            field=models.BooleanField(db_column='IsActive', default=True),
        ),
        migrations.AlterField(
            model_name='packagedtl',
            name='isactive',
            field=models.BooleanField(db_column='IsActive', default=True),
        ),
        migrations.AlterField(
            model_name='packagedtl',
            name='limitservice_flexionly',
            field=models.BooleanField(db_column='LimitService_FlexiOnly', null=True),
        ),
        migrations.AlterField(
            model_name='packagedtl',
            name='service_expire_active',
            field=models.BooleanField(db_column='Service_Expire_Active', null=True),
        ),
        migrations.AlterField(
            model_name='packagedtl',
            name='treatment_limit_active',
            field=models.BooleanField(db_column='Treatment_Limit_Active', null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='conditiontype1',
            field=models.CharField(db_column='ConditionType1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='conditiontype2',
            field=models.CharField(db_column='ConditionType2', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='creditvalueshared',
            field=models.BooleanField(db_column='CreditValueShared', null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='item_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='lpackage',
            field=models.BooleanField(db_column='lPackage', null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='membercardnoaccess',
            field=models.BooleanField(db_column='MemberCardNoAccess', null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='p_itemtype',
            field=models.CharField(db_column='P_ItemType', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='pos_daud_lineno',
            field=models.FloatField(db_column='POS_Daud_LineNo', null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='pp_no',
            field=models.CharField(db_column='PP_NO', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccountcondition',
            name='pp_type',
            field=models.CharField(db_column='PP_TYPE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidopencondition',
            name='conditiontype1',
            field=models.CharField(db_column='ConditionType1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidopencondition',
            name='conditiontype2',
            field=models.CharField(db_column='ConditionType2', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidopencondition',
            name='item_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidopencondition',
            name='membercardnoaccess',
            field=models.BooleanField(db_column='MemberCardNoAccess', null=True),
        ),
        migrations.AlterField(
            model_name='prepaidopencondition',
            name='p_itemtype',
            field=models.CharField(db_column='P_ItemType', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidopencondition',
            name='prepaid_valid_period',
            field=models.CharField(db_column='Prepaid_Valid_Period', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidopencondition',
            name='rate',
            field=models.CharField(db_column='Rate', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidopencondition',
            name='uid',
            field=models.CharField(db_column='UID', max_length=36, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidvalidperiod',
            name='prepaid_valid_code',
            field=models.CharField(db_column='Prepaid_Valid_Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidvalidperiod',
            name='prepaid_valid_isactive',
            field=models.BooleanField(db_column='Prepaid_Valid_IsActive', default=True),
        ),
        migrations.AlterField(
            model_name='receiptar',
            name='invoice_no',
            field=models.CharField(db_column='Invoice_No', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='receiptar',
            name='receipt_date',
            field=models.DateTimeField(db_column='Receipt_Date', null=True),
        ),
        migrations.AlterField(
            model_name='receiptar',
            name='receipt_no',
            field=models.CharField(db_column='Receipt_no', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='stktrn',
            name='hq_update',
            field=models.BooleanField(db_column='HQ_UPDATE', null=True),
        ),
        migrations.AlterField(
            model_name='systemsetup',
            name='create_datetime',
            field=models.DateTimeField(auto_now_add=True, db_column='Create_DateTime', null=True),
        ),
        migrations.AlterField(
            model_name='systemsetup',
            name='edit_datetime',
            field=models.DateTimeField(auto_now_add=True, db_column='Edit_DateTime', null=True),
        ),
        migrations.AlterField(
            model_name='treatmentprotocol',
            name='isactive',
            field=models.BooleanField(db_column='ISACTIVE', default=True),
        ),
        migrations.AlterField(
            model_name='vouchervalidperiod',
            name='voucher_valid_code',
            field=models.CharField(db_column='Voucher_Valid_Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vouchervalidperiod',
            name='voucher_valid_isactive',
            field=models.BooleanField(db_column='Voucher_Valid_IsActive', default=True),
        ),
    ]
