# Generated by Django 3.0.7 on 2020-10-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0003_auto_20201009_1642'),
        ('cl_table', '0033_treatment_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='img')),
                ('item_sitelist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cl_app.ItemSitelist')),
                ('services', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cl_table.Stock')),
            ],
            options={
                'db_table': 'Images',
            },
        ),
    ]
