# Generated by Django 3.0.7 on 2020-10-11 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0035_auto_20201010_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommType',
        ),
    ]
