# Generated by Django 3.0.7 on 2020-10-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0036_delete_commtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommType',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('comm_type_code', models.CharField(blank=True, db_column='Comm_Type_Code', max_length=20, null=True)),
                ('comm_type_desc', models.CharField(blank=True, db_column='Comm_Type_Desc', max_length=50, null=True)),
                ('comm_type_active', models.BooleanField(db_column='Comm_Type_Active', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Comm_Type',
            },
        ),
    ]
