# Generated by Django 3.0.7 on 2020-10-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0037_commtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpSocso',
        ),
    ]
