# Generated by Django 3.0.7 on 2020-10-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0038_delete_empsocso'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpSocso',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('emp_code', models.CharField(blank=True, db_column='Emp_Code', max_length=50, null=True)),
                ('emp_socso_employee', models.FloatField(blank=True, db_column='Emp_SOCSO_Employee', null=True)),
                ('emp_socso_employer', models.FloatField(blank=True, db_column='Emp_SOCSO_Employer', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Emp_SOCSO',
            },
        ),
    ]
