# Generated by Django 3.0.7 on 2020-10-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0039_empsocso'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customervoucher',
        ),
    ]
