# Generated by Django 3.0.7 on 2020-10-11 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0041_customervoucher'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creditnote',
            unique_together={('treatment_code', 'credit_code', 'site_code')},
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('cust_code',)},
        ),
        migrations.AlterUniqueTogether(
            name='depositaccount',
            unique_together={('cust_code', 'sa_transacno', 'ref_code', 'item_barcode', 'dt_lineno')},
        ),
        migrations.AlterUniqueTogether(
            name='empsitelist',
            unique_together={('emp_code', 'site_code')},
        ),
        migrations.AlterUniqueTogether(
            name='holditemdetail',
            unique_together={('itemsite_code', 'sa_transacno', 'itemno', 'hi_lineno', 'product_issues_no')},
        ),
        migrations.AlterUniqueTogether(
            name='itemhelper',
            unique_together={('item_code', 'line_no', 'sa_transacno', 'helper_code', 'sa_date', 'site_code', 'helper_transacno')},
        ),
        migrations.AlterUniqueTogether(
            name='multistaff',
            unique_together={('sa_transacno', 'item_code', 'emp_code', 'role', 'dt_lineno')},
        ),
        migrations.AlterUniqueTogether(
            name='posdaud',
            unique_together={('cas_logno', 'sa_transacno', 'dt_itemdesc', 'itemsite_code', 'dt_lineno', 'st_ref_treatmentcode')},
        ),
        migrations.AlterUniqueTogether(
            name='poshaud',
            unique_together={('cas_logno', 'sa_transacno', 'sa_custno', 'itemsite_code')},
        ),
        migrations.AlterUniqueTogether(
            name='postaud',
            unique_together={('sa_transacno', 'cas_logno', 'itemsite_code', 'dt_lineno')},
        ),
        migrations.AlterUniqueTogether(
            name='prepaidaccountcondition',
            unique_together={('pp_no', 'pp_type', 'p_itemtype', 'item_code', 'conditiontype1', 'conditiontype2', 'pos_daud_lineno')},
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('source_code',)},
        ),
        migrations.AlterUniqueTogether(
            name='treatment',
            unique_together={('treatment_code', 'site_code')},
        ),
        migrations.AlterUniqueTogether(
            name='treatmentaccount',
            unique_together={('cust_code', 'description', 'ref_no', 'balance', 'sa_transacno', 'sa_staffno', 'dt_lineno', 'site_code', 'treat_code')},
        ),
    ]
