# Generated by Django 3.0.7 on 2020-10-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0043_remove_stock_equipmentcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='equipmentcost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
