# Generated by Django 3.0.7 on 2020-10-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0045_customer_site_codeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pronetocomplain',
            field=models.BooleanField(blank=True, db_column='ProneToComplain', default=False, null=True),
        ),
    ]
