# Generated by Django 3.0.7 on 2020-10-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0048_auto_20201013_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_class',
            field=models.CharField(db_column='Item_Class', default=1, max_length=20),
            preserve_default=False,
        ),
    ]
