# Generated by Django 3.0.7 on 2020-10-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0049_auto_20201013_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_class',
            field=models.CharField(db_column='Item_Class', max_length=20, null=True),
        ),
    ]
