# Generated by Django 3.0.7 on 2020-10-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0051_auto_20201013_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item_pingying',
            field=models.CharField(db_column='Item_PingYing', default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='procedure',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='process_remark',
            field=models.CharField(db_column='Process_Remark', default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tax',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='treatment_details',
            field=models.TextField(default=None, null=True),
        ),
    ]
