# Generated by Django 3.0.7 on 2020-10-13 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0052_auto_20201013_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='Itm_Statusid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item_Brandid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item_Seasonid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item_SizePackid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item_Sizeid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item_colorid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='item_fabricid',
        ),
    ]
