# Generated by Django 3.0.7 on 2020-10-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0053_auto_20201013_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='item_pingying',
            field=models.CharField(db_column='Item_PingYing', default='null', max_length=250, null=True),
        ),
    ]
