# Generated by Django 3.0.7 on 2020-10-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0055_auto_20201013_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment_master',
            name='sys_code',
        ),
        migrations.AddField(
            model_name='treatment_master',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
