# Generated by Django 3.0.7 on 2020-10-13 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0057_auto_20201013_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Cust_Classid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.CustomerClass'),
        ),
    ]
