# Generated by Django 3.0.7 on 2020-10-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0058_customer_cust_classid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstsetting',
            name='is_exclusive',
            field=models.BooleanField(null=True),
        ),
    ]
