# Generated by Django 3.0.7 on 2020-10-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0059_gstsetting_is_exclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Cust_Sourceid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Source'),
        ),
    ]
