# Generated by Django 3.0.7 on 2020-10-16 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0060_customer_cust_sourceid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creditnote',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='depositaccount',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='holditemdetail',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemhelper',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='multistaff',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='posdaud',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='poshaud',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='postaud',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prepaidaccountcondition',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='treatment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='treatment_master',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='treatmentaccount',
            unique_together=set(),
        ),
    ]
