# Generated by Django 3.0.7 on 2020-10-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0061_auto_20201016_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posdaud',
            name='itemcart',
        ),
        migrations.RemoveField(
            model_name='tmpitemhelper',
            name='itemcart',
        ),
        migrations.RemoveField(
            model_name='treatmentaccount',
            name='itemcart',
        ),
    ]
