# Generated by Django 3.0.7 on 2020-10-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0063_auto_20201016_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpitemhelper',
            name='times',
            field=models.CharField(blank=True, db_column='Times', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tmpitemhelper',
            name='treatment_no',
            field=models.CharField(blank=True, db_column='Treatment_No', max_length=10, null=True),
        ),
    ]
