# Generated by Django 3.0.7 on 2020-10-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0065_tmpitemhelper_workcommpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdaud',
            name='st_ref_treatmentcode',
            field=models.CharField(blank=True, db_column='ST_Ref_TreatmentCode', max_length=500, null=True),
        ),
    ]
