# Generated by Django 3.0.7 on 2020-10-19 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0066_auto_20201018_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentaccount',
            name='sa_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
