# Generated by Django 3.0.7 on 2020-10-23 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0011_itemcart_treatment_account'),
        ('cl_table', '0069_auto_20201023_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpitemhelper',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Treatment'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='helper_ids',
            field=models.ManyToManyField(blank=True, related_name='tmpitemhelper', to='cl_table.TmpItemHelper'),
        ),
        migrations.AlterField(
            model_name='tmpitemhelper',
            name='itemcart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart'),
        ),
    ]
