# Generated by Django 3.0.7 on 2020-10-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0070_auto_20201023_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='record_status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING')], db_column='Record_Status', max_length=10, null=True),
        ),
    ]
