# Generated by Django 3.0.7 on 2020-10-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0072_auto_20201027_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaccount',
            name='sa_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='sa_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='depositaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Top Up', 'Top Up')], db_column='Type', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccount',
            name='edit_date',
            field=models.DateTimeField(auto_now_add=True, db_column='Edit_Date', null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccount',
            name='sa_date',
            field=models.DateTimeField(auto_now_add=True, db_column='SA_DATE', null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccount',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, db_column='START_DATE', null=True),
        ),
    ]
