# Generated by Django 3.0.7 on 2020-10-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0074_vouchercondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaccount',
            name='ref_code',
            field=models.CharField(db_column='Ref_Code', max_length=100, null=True),
        ),
    ]
