# Generated by Django 3.0.7 on 2020-10-29 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0076_auto_20201029_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositaccount',
            name='Item_Codeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Stock'),
        ),
        migrations.AddField(
            model_name='depositaccount',
            name='item_code',
            field=models.CharField(blank=True, db_column='Item_Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prepaidaccount',
            name='Item_Codeid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Stock'),
        ),
        migrations.AddField(
            model_name='prepaidaccount',
            name='item_code',
            field=models.CharField(blank=True, db_column='Item_Code', max_length=20, null=True),
        ),
    ]
