# Generated by Django 3.0.7 on 2020-10-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0077_auto_20201029_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositaccount',
            name='ref_productcode',
            field=models.CharField(blank=True, db_column='Ref_ProductCode', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='depositaccount',
            name='ref_transacno',
            field=models.CharField(blank=True, db_column='Ref_Transacno', max_length=20, null=True),
        ),
    ]
