# Generated by Django 3.0.7 on 2020-11-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0078_auto_20201030_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='sa_date',
            field=models.DateTimeField(auto_now_add=True, db_column='sa_Date', null=True),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE')], db_column='Status', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='reversehdr',
            name='reverse_date',
            field=models.DateTimeField(auto_now_add=True, db_column='Reverse_Date', null=True),
        ),
        migrations.AlterField(
            model_name='reversehdr',
            name='reverse_time',
            field=models.DateTimeField(auto_now_add=True, db_column='Reverse_Time', null=True),
        ),
    ]
