# Generated by Django 3.0.7 on 2020-11-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0079_auto_20201105_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshaud',
            name='cart_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
