# Generated by Django 3.0.7 on 2020-11-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0080_poshaud_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaccount',
            name='type',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Top Up', 'Top Up'), ('CANCEL', 'CANCEL')], db_column='Type', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='itemhelper',
            name='sa_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='isvoid',
            field=models.BooleanField(db_column='IsVoid', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='prepaidaccount',
            name='sa_status',
            field=models.CharField(blank=True, choices=[('DEPOSIT', 'DEPOSIT'), ('TOPUP', 'TOPUP'), ('SA', 'SA')], db_column='SA_STATUS', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='sa_status',
            field=models.CharField(blank=True, choices=[('SA', 'SA'), ('VOID', 'VOID'), ('SU', 'SU')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentaccount',
            name='sa_status',
            field=models.CharField(blank=True, choices=[('SA', 'SA'), ('VOID', 'VOID'), ('SU', 'SU')], max_length=5, null=True),
        ),
    ]
