# Generated by Django 3.0.7 on 2020-11-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0081_auto_20201109_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshaud',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='sa_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='poshaud',
            name='sa_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
