# Generated by Django 3.0.7 on 2020-11-16 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0084_auto_20201116_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshaud',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
