# Generated by Django 3.0.7 on 2020-12-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0086_auto_20201127_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='favorites',
        ),
    ]
