# Generated by Django 3.0.7 on 2020-12-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0088_auto_20201202_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Title',
        ),
    ]
