# Generated by Django 3.0.7 on 2020-12-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0090_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('cust_code', 'cust_email', 'cust_phone1', 'cust_phone2')},
        ),
    ]
