# Generated by Django 3.0.7 on 2020-12-13 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0091_auto_20201211_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_login',
        ),
    ]
