# Generated by Django 3.0.7 on 2020-12-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0092_remove_employee_is_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_login',
            field=models.BooleanField(blank=True, db_column='Login', null=True),
        ),
    ]
