# Generated by Django 3.0.7 on 2020-12-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0093_employee_is_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdaud',
            name='record_detail_type',
            field=models.CharField(blank=True, choices=[('SERVICE', 'SERVICE'), ('PRODUCT', 'PRODUCT'), ('PREPAID', 'PREPAID'), ('VOUCHER', 'VOUCHER'), ('PACKAGE', 'PACKAGE'), ('TD', 'TD'), ('TP SERVICE', 'TP SERVICE'), ('TP PRODUCT', 'TP PRODUCT'), ('TP PREPAID', 'TP PREPAID')], db_column='Record_Detail_Type', max_length=50, null=True),
        ),
    ]
