# Generated by Django 3.0.7 on 2020-12-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0094_auto_20201215_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sa_transacno',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
