# Generated by Django 3.0.7 on 2021-02-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0095_auto_20201224_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holditemdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('VOID', 'VOID')], db_column='Status', max_length=50, null=True),
        ),
    ]
