# Generated by Django 3.0.7 on 2021-01-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0095_auto_20201224_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sa_transacno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
