# Generated by Django 3.0.7 on 2021-02-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0096_auto_20210210_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stktrn',
            name='trn_date',
            field=models.DateTimeField(auto_now=True, db_column='TRN_DATE', null=True),
        ),
        migrations.AlterField(
            model_name='stktrn',
            name='trn_post',
            field=models.DateTimeField(auto_now=True, db_column='TRN_POST', null=True),
        ),
    ]
