# Generated by Django 3.0.7 on 2021-03-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0097_auto_20210219_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockReason',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('b_no', models.CharField(blank=True, db_column='B_No', max_length=50, null=True)),
                ('b_reason', models.CharField(blank=True, db_column='B_Reason', max_length=50, null=True)),
                ('active', models.BooleanField(blank=True, db_column='Active', default=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Block_Reason',
            },
        ),
    ]
