# Generated by Django 3.0.7 on 2021-03-25 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0098_blockreason'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='User_Name', max_length=300, null=True)),
                ('appt_date', models.DateField(blank=True, db_column='Appt_date', null=True)),
                ('appt_fr_time', models.TimeField(blank=True, db_column='Appt_Fr_time', null=True)),
                ('appt_to_time', models.TimeField(blank=True, db_column='Appt_To_time', null=True)),
                ('emp_code', models.CharField(blank=True, max_length=100, null=True)),
                ('appt_status', models.CharField(blank=True, choices=[('Booking', 'Booking'), ('Waiting', 'Waiting List'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Arrived', 'Arrived'), ('Done', 'Done'), ('LastMinCancel', 'Cancelled Last Minute'), ('Late', 'Late'), ('No Show', 'No Show')], db_column='Appt_Status', max_length=20, null=True)),
                ('sec_status', models.CharField(blank=True, choices=[('Rescheduled', 'Rescheduled'), ('Notified Once', 'Notified Once'), ('Notified Twice', 'Notified Twice')], max_length=25, null=True)),
                ('appt_remark', models.CharField(blank=True, db_column='Appt_remark', max_length=250, null=True)),
                ('item_code', models.CharField(blank=True, db_column='item_Code', max_length=20, null=True)),
                ('requesttherapist', models.BooleanField(db_column='requestTherapist', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('appt_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Appointment')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee')),
            ],
            options={
                'db_table': 'Appointment_Log',
            },
        ),
    ]
