# Generated by Django 3.0.7 on 2021-03-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0100_appointmentlog_add_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentlog',
            name='new_remark',
            field=models.CharField(blank=True, db_column='New_Remark', max_length=800, null=True),
        ),
    ]
