# Generated by Django 3.0.7 on 2021-04-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0101_appointmentlog_new_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdaud',
            name='dt_status',
            field=models.CharField(blank=True, choices=[('SA', 'SA'), ('VT', 'VT'), ('SU', 'SU'), ('EX', 'EX')], max_length=5, null=True),
        ),
    ]
