# Generated by Django 3.0.7 on 2021-04-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0102_auto_20210416_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='recur_linkcode',
            field=models.CharField(blank=True, db_column='Recur_Linkcode', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurring_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='recurring_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
