# Generated by Django 3.0.7 on 2021-05-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0104_auto_20210511_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmpmultistaff',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sa_transacno', models.CharField(db_column='sa_transacNo', max_length=20)),
                ('item_code', models.CharField(db_column='Item_Code', max_length=20)),
                ('emp_code', models.CharField(db_column='Emp_Code', max_length=20)),
                ('ratio', models.FloatField(db_column='Ratio')),
                ('salesamt', models.FloatField(db_column='SalesAmt')),
                ('type', models.CharField(db_column='Type', max_length=20)),
                ('isdelete', models.BooleanField(db_column='IsDelete')),
                ('role', models.CharField(db_column='Role', max_length=50)),
                ('dt_lineno', models.IntegerField(db_column='dt_LineNo')),
                ('mac_uid_ref', models.CharField(blank=True, db_column='MAC_UID_Ref', max_length=50, null=True)),
            ],
            options={
                'db_table': 'TmpMultiStaff',
            },
        ),
    ]
