# Generated by Django 3.0.7 on 2021-05-12 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0025_auto_20210505_1658'),
        ('cl_table', '0105_tmpmultistaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistaff',
            name='salescommpoints',
            field=models.FloatField(blank=True, db_column='SalesCommPoints', null=True),
        ),
        migrations.AddField(
            model_name='tmpmultistaff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tmpmultistaff',
            name='itemcart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart'),
        ),
        migrations.AddField(
            model_name='tmpmultistaff',
            name='level_group_code',
            field=models.CharField(blank=True, db_column='Level_Group_Code', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tmpmultistaff',
            name='salescommpoints',
            field=models.FloatField(blank=True, db_column='SalesCommPoints', null=True),
        ),
        migrations.AddField(
            model_name='tmpmultistaff',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
