# Generated by Django 3.0.7 on 2021-05-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0107_tmpmultistaff_emp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpmultistaff',
            name='dt_lineno',
            field=models.IntegerField(db_column='dt_LineNo', null=True),
        ),
        migrations.AlterField(
            model_name='tmpmultistaff',
            name='emp_code',
            field=models.CharField(db_column='Emp_Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tmpmultistaff',
            name='isdelete',
            field=models.BooleanField(db_column='IsDelete', null=True),
        ),
        migrations.AlterField(
            model_name='tmpmultistaff',
            name='item_code',
            field=models.CharField(db_column='Item_Code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tmpmultistaff',
            name='ratio',
            field=models.FloatField(db_column='Ratio', null=True),
        ),
        migrations.AlterField(
            model_name='tmpmultistaff',
            name='role',
            field=models.CharField(db_column='Role', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tmpmultistaff',
            name='sa_transacno',
            field=models.CharField(db_column='sa_transacNo', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tmpmultistaff',
            name='salesamt',
            field=models.FloatField(db_column='SalesAmt', null=True),
        ),
        migrations.AlterField(
            model_name='tmpmultistaff',
            name='type',
            field=models.CharField(db_column='Type', max_length=20, null=True),
        ),
    ]
