# Generated by Django 3.0.7 on 2021-05-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0027_auto_20210516_2145'),
        ('cl_table', '0108_auto_20210512_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cardno1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cardno2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cardno3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cardno4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cardno5',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='emergencycontact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postaud',
            name='gt',
            field=models.CharField(db_column='gt', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='holditemdetail',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'OPEN'), ('Close', 'Close'), ('VOID', 'VOID')], db_column='Status', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stktrn',
            name='trn_date',
            field=models.DateTimeField(blank=True, db_column='TRN_DATE', null=True),
        ),
        migrations.AlterField(
            model_name='stktrn',
            name='trn_post',
            field=models.DateTimeField(blank=True, db_column='TRN_POST', null=True),
        ),
      
    ]
