# Generated by Django 3.0.7 on 2021-05-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0108_auto_20210512_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmptreatment',
            fields=[
                ('sys_code', models.AutoField(db_column='Sys_Code', primary_key=True, serialize=False)),
                ('treatment_code', models.CharField(blank=True, db_column='Treatment_Code', max_length=20, null=True)),
                ('course', models.CharField(blank=True, db_column='Course', max_length=80, null=True)),
                ('times', models.CharField(blank=True, db_column='Times', max_length=10, null=True)),
                ('treatment_no', models.CharField(blank=True, db_column='Treatment_No', max_length=10, null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('treatment_date', models.DateTimeField(blank=True, db_column='Treatment_Date', null=True)),
                ('next_appt', models.DateTimeField(blank=True, db_column='Next_Appt', null=True)),
                ('cust_name', models.CharField(blank=True, db_column='Cust_Name', max_length=100, null=True)),
                ('cust_code', models.CharField(blank=True, db_column='Cust_Code', max_length=50, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=50, null=True)),
                ('unit_amount', models.FloatField(blank=True, db_column='Unit_Amount', null=True)),
                ('item_code', models.CharField(blank=True, db_column='Item_Code', max_length=20, null=True)),
                ('treatment_parentcode', models.CharField(blank=True, db_column='Treatment_ParentCode', max_length=20, null=True)),
                ('prescription', models.CharField(blank=True, db_column='Prescription', max_length=255, null=True)),
                ('allergy', models.CharField(blank=True, db_column='Allergy', max_length=255, null=True)),
                ('sa_transacno', models.CharField(blank=True, max_length=20, null=True)),
                ('sa_status', models.CharField(blank=True, max_length=5, null=True)),
                ('appt_time', models.CharField(blank=True, db_column='Appt_Time', max_length=10, null=True)),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True)),
                ('hold_item', models.CharField(blank=True, db_column='Hold_Item', max_length=50, null=True)),
                ('dt_lineno', models.IntegerField(blank=True, db_column='dt_LineNo', null=True)),
                ('expiry', models.DateTimeField(blank=True, db_column='Expiry', null=True)),
                ('lpackage', models.BooleanField(db_column='lPackage')),
                ('package_code', models.CharField(blank=True, db_column='Package_Code', max_length=50, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('treatment_limit_times', models.FloatField(blank=True, db_column='Treatment_Limit_Times', null=True)),
                ('treatment_count_done', models.FloatField(blank=True, db_column='Treatment_Count_Done', null=True)),
                ('mac_uid_ref', models.CharField(blank=True, db_column='MAC_UID_Ref', max_length=50, null=True)),
                ('trmt_is_auto_proportion', models.BooleanField(db_column='Trmt_Is_Auto_Proportion')),
            ],
            options={
                'db_table': 'TmpTreatment',
            },
        ),
    ]
