# Generated by Django 3.0.7 on 2021-05-19 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0027_auto_20210519_1133'),
        ('cl_table', '0109_tmptreatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmptreatment',
            name='itemcart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart'),
        ),
    ]
