# Generated by Django 3.0.7 on 2021-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0110_tmptreatment_itemcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmptreatment',
            name='isfoc',
            field=models.BooleanField(blank=True, db_column='isFOC', null=True),
        ),
        migrations.AlterField(
            model_name='tmptreatment',
            name='treatment_date',
            field=models.DateTimeField(auto_now_add=True, db_column='Treatment_Date', null=True),
        ),
    ]
