# Generated by Django 3.0.7 on 2021-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0113_exchangedtl'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangedtl',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='exchangedtl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
