# Generated by Django 3.0.7 on 2021-05-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0114_auto_20210524_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangedtl',
            name='exchange_date',
            field=models.DateTimeField(auto_now_add=True, db_column='Exchange_Date', null=True),
        ),
        migrations.AlterField(
            model_name='exchangedtl',
            name='sa_date',
            field=models.DateTimeField(auto_now_add=True, db_column='Sa_Date', null=True),
        ),
    ]
