# Generated by Django 3.0.7 on 2021-06-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0119_fmspw_is_reversal'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='linkcode',
            field=models.CharField(blank=True, db_column='Linkcode', max_length=200, null=True),
        ),
    ]
