# Generated by Django 3.0.7 on 2021-06-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0120_appointment_linkcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='link_flag',
            field=models.BooleanField(db_column='Link Flag', default=False),
        ),
    ]
