# Generated by Django 3.0.7 on 2021-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0121_appointment_link_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_code', models.CharField(db_column='Site_Code', max_length=50)),
                ('template_name', models.CharField(db_column='Template_Name', max_length=500)),
                ('logo_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='Logo_align', max_length=150)),
                ('trans_h1_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='trans_h1_align', max_length=150)),
                ('trans_h2_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='trans_h2_align', max_length=150)),
                ('custname_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='custname_align', max_length=150)),
                ('custcode_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='custcode_align', max_length=150)),
                ('custrefer_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='custrefer_align', max_length=150)),
                ('custphone2_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='custphone2_align', max_length=150)),
                ('satransac_ref_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='satransacref_align', max_length=150)),
                ('sa_date_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='sa_date_align', max_length=150)),
                ('sa_time_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='sa_time_align', max_length=150)),
                ('userid_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='userid_align', max_length=150)),
                ('custsign_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='custsign_align', max_length=150)),
                ('footer_align', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], db_column='footer_align', max_length=150)),
            ],
            options={
                'db_table': 'Template_Settings',
            },
        ),
    ]
