# Generated by Django 3.0.7 on 2021-07-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0122_templatesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='pinyin',
            field=models.CharField(blank=True, db_column='Pinyin', max_length=500, null=True),
        ),
    ]
