# Generated by Django 3.0.7 on 2021-07-07 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0123_stock_pinyin'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhelper',
            name='session',
            field=models.FloatField(blank=True, db_column='Session', null=True),
        ),
        migrations.AddField(
            model_name='tmpitemhelper',
            name='session',
            field=models.FloatField(blank=True, db_column='Session', null=True),
        ),
        migrations.AddField(
            model_name='tmpitemhelper',
            name='tmptreatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Tmptreatment'),
        ),
    ]
