# Generated by Django 3.0.7 on 2021-07-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0124_auto_20210707_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemhelper',
            name='times',
            field=models.CharField(blank=True, db_column='Times', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='itemhelper',
            name='treatment_no',
            field=models.CharField(blank=True, db_column='Treatment_No', max_length=10, null=True),
        ),
    ]
