# Generated by Django 3.0.7 on 2021-07-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0125_auto_20210707_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='paygroup',
            name='picturelocation',
            field=models.CharField(db_column='PICTURELOCATION', max_length=200, null=True),
        ),
    ]
