# Generated by Django 3.0.7 on 2021-07-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0129_auto_20210719_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customertitle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dailysalestdsummary',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menusecurity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='menusecuritylevellist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='redeempolicy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rewardpolicy',
            options={},
        ),
        migrations.AlterModelOptions(
            name='securitycontrollist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='securitylevellist',
            options={},
        ),
        migrations.AlterModelOptions(
            name='skillstaff',
            options={},
        ),
        migrations.AddField(
            model_name='customer',
            name='Cust_titleid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.CustomerTitle'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_consultant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_consultant', to='cl_table.Employee'),
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_therapist_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_therapist', to='cl_table.Employee'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='cust_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_remarks',
            field=models.CharField(blank=True, db_column='Emp_remarks', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='schedulehour',
            name='shortdesc',
            field=models.CharField(db_column='shortDesc', max_length=2, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosis',
            unique_together=set(),
        ),
    ]
