# Generated by Django 3.0.7 on 2021-07-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0140_auto_20210719_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment_master',
            name='checktype',
        ),
    ]
