# Generated by Django 3.0.7 on 2021-07-20 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0044_merge_20210717_2039'),
        ('cl_table', '0143_auto_20210720_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multilanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('english', models.CharField(blank=True, max_length=250, null=True)),
                ('zh_sg', models.CharField(blank=True, db_column='zh-sg', max_length=250, null=True)),
            ],
            options={
                'db_table': 'MultiLanguage',
            },
        ),
        migrations.CreateModel(
            name='CustomerFormControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(blank=True, db_column='fieldName', max_length=50, null=True)),
                ('display_field_name', models.CharField(blank=True, db_column='displayFieldName', max_length=50, null=True)),
                ('visible_in_registration', models.BooleanField(db_column='visibleInRegistration')),
                ('visible_in_listing', models.BooleanField(db_column='visibleInListing')),
                ('visible_in_profile', models.BooleanField(db_column='visibleInProfile')),
                ('editable', models.BooleanField()),
                ('mandatory', models.BooleanField()),
                ('order', models.IntegerField()),
                ('col_width', models.IntegerField(default=6)),
                ('isActive', models.BooleanField(db_column='isActive')),
                ('Site_Codeid', models.ForeignKey(db_column='Site_Codeid_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_form_control', to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'customerFormControl',
            },
        ),
        migrations.CreateModel(
            name='MultiLanguageWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wordCode', models.IntegerField()),
                ('word', models.CharField(max_length=250)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cl_table.Language')),
            ],
            options={
                'db_table': 'MultiLanguageWord',
                'unique_together': {('wordCode', 'language')},
            },
        ),
    ]
