# Generated by Django 3.0.7 on 2021-07-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0144_customerformcontrol_multilanguage_multilanguageword'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshaud',
            name='control_no',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
