# Generated by Django 3.0.7 on 2021-07-22 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0145_poshaud_control_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshaud',
            name='control_no',
        ),
    ]
