# Generated by Django 3.0.7 on 2021-08-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0097_auto_20210119_1715'),
        ('cl_table', '0127_merge_20210717_2039'),
        ('cl_table', '0146_remove_poshaud_control_no'),
    ]

    operations = [
    ]
