# Generated by Django 3.0.7 on 2021-08-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0148_auto_20210802_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
