# Generated by Django 3.0.7 on 2021-08-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0149_customer_cust_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='add_duration',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='checktype',
            field=models.CharField(blank=True, choices=[('service', 'service'), ('package', 'package'), ('freetext', 'freetext')], db_column='CheckType', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='treat_parentcode',
            field=models.CharField(blank=True, db_column='Treat_ParentCode', max_length=20, null=True),
        ),
    ]
