# Generated by Django 3.0.7 on 2021-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0153_auto_20210823_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_freetext',
            field=models.BooleanField(blank=True, db_column='is_freetext', null=True),
        ),
    ]
