# Generated by Django 3.0.7 on 2021-09-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0154_stock_is_freetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetup',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
