# Generated by Django 3.0.7 on 2021-09-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0155_systemsetup_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time01',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time0130',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time02',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time0230',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time03',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time0330',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time04',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time0430',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time05',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time0530',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time06',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time0630',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time07',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time0730',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time10',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time1030',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time11',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time1130',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time12',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time1230',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time9',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time930',
        ),
    ]
