# Generated by Django 3.0.7 on 2021-09-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0156_auto_20210902_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulemonth',
            name='time01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0130',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time02',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0230',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time03',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0330',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time04',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0430',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time05',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0530',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time06',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0630',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time07',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0730',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time1030',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time1130',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time1230',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time930',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
