# Generated by Django 3.0.7 on 2021-09-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0159_auto_20210902_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time08',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time0830',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time09',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time0930',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time13',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time1330',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time14',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time1430',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time15',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time1530',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time16',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time1630',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time17',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time1730',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time18',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time1830',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time19',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time1930',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time20',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time2030',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time21',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time2130',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time22',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time2230',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time23',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time2330',
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time01',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0130',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time02',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0230',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time03',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0330',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time04',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0430',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time05',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0530',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time06',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0630',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time930',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemonth',
            name='time07',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemonth',
            name='time0730',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemonth',
            name='time10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemonth',
            name='time1030',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemonth',
            name='time11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemonth',
            name='time1130',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemonth',
            name='time12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemonth',
            name='time1230',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
