# Generated by Django 3.0.7 on 2021-09-02 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0160_auto_20210902_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time9',
        ),
        migrations.RemoveField(
            model_name='schedulemonth',
            name='time930',
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time09',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time0930',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
