# Generated by Django 3.0.7 on 2021-09-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0162_auto_20210902_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulemonth',
            old_name='time01',
            new_name='time13',
        ),
        migrations.RenameField(
            model_name='schedulemonth',
            old_name='time0130',
            new_name='time1330',
        ),
        migrations.RenameField(
            model_name='schedulemonth',
            old_name='time02',
            new_name='time14',
        ),
        migrations.RenameField(
            model_name='schedulemonth',
            old_name='time0230',
            new_name='time1430',
        ),
        migrations.RenameField(
            model_name='schedulemonth',
            old_name='time03',
            new_name='time15',
        ),
        migrations.RenameField(
            model_name='schedulemonth',
            old_name='time0330',
            new_name='time1530',
        ),
        migrations.RenameField(
            model_name='schedulemonth',
            old_name='time04',
            new_name='time16',
        ),
        migrations.RenameField(
            model_name='schedulemonth',
            old_name='time0430',
            new_name='time1630',
        ),
        migrations.RenameField(
            model_name='schedulemonth',
            old_name='time05',
            new_name='time17',
        ),
        migrations.RenameField(
            model_name='schedulemonth',
            old_name='time0530',
            new_name='time1730',
        ),
        migrations.RenameField(
            model_name='schedulemonth',
            old_name='time06',
            new_name='time18',
        ),
        migrations.RenameField(
            model_name='schedulemonth',
            old_name='time0630',
            new_name='time1830',
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time19',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time1930',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time20',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time2030',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time21',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time2130',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time22',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time2230',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time23',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='schedulemonth',
            name='time2330',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
