# Generated by Django 3.0.7 on 2021-09-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0163_auto_20210902_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='is_freetext',
        ),
    ]
