# Generated by Django 3.0.7 on 2021-09-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0164_remove_stock_is_freetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='license_key',
            field=models.CharField(blank=True, db_column='license_key', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='valid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='version_no',
            field=models.CharField(blank=True, db_column='version_no', max_length=200, null=True),
        ),
    ]
