# Generated by Django 3.0.7 on 2021-09-30 14:25

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0165_auto_20210924_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='MrRewardItemType',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('itemtype_code', models.CharField(db_column='ITEMTYPE_CODE', max_length=20)),
                ('itemtype_desc', models.CharField(blank=True, db_column='ITEMTYPE_DESC', max_length=50, null=True)),
                ('isactive', models.BooleanField(db_column='ISACTIVE')),
            ],
            options={
                'db_table': 'MR_Reward_Item_Type',
            },
        ),
        migrations.AlterModelOptions(
            name='redeempolicy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='rewardpolicy',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='skillstaff',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='customerformcontrol',
            name='isStacked',
            field=models.BooleanField(db_column='isStacked', default=False),
        ),
        migrations.AddField(
            model_name='customerformcontrol',
            name='layout',
            field=jsonfield.fields.JSONField(default={'lg': {'h': 0, 'w': 0, 'x': 0, 'y': 0}, 'md': {'h': 0, 'w': 0, 'x': 0, 'y': 0}, 'sm': {'h': 0, 'w': 0, 'x': 0, 'y': 0}}),
        ),
        migrations.AddField(
            model_name='customerformcontrol',
            name='showLabel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='pic_data',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='pic_data1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosiscompare',
            name='diagnosis',
            field=models.ManyToManyField(to='cl_table.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='approval_user',
            field=models.CharField(db_column='Approval_User', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='bal_point',
            field=models.FloatField(db_column='Bal_Point', default=0),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='cardno',
            field=models.CharField(db_column='CardNo', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='expired',
            field=models.BooleanField(db_column='Expired', default=False),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='expired_point',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='isvoid',
            field=models.BooleanField(db_column='Isvoid', default=True),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='locid',
            field=models.CharField(db_column='LocID', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='logno',
            field=models.CharField(db_column='LogNo', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='mac_code',
            field=models.CharField(db_column='Mac_Code', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='postransactionno',
            field=models.CharField(db_column='posTransactionNo', default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerpoint',
            name='remarks',
            field=models.CharField(blank=True, db_column='Remarks', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosiscompare',
            name='diagnosis1_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_compare_1', to='cl_table.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='diagnosiscompare',
            name='diagnosis2_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnosis_compare_2', to='cl_table.Diagnosis'),
        ),
    ]
