# Generated by Django 3.0.7 on 2021-10-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0166_auto_20210930_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentDuration',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('duration', models.TimeField()),
                ('isactive', models.BooleanField(db_column='Isactive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Treatment_Duration',
            },
        ),
    ]
