# Generated by Django 3.0.7 on 2021-10-21 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0169_auto_20211021_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='item_seq',
        ),
    ]
