# Generated by Django 3.0.7 on 2021-10-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0172_auto_20211021_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentlog',
            name='newempcode',
            field=models.CharField(db_column='NewEmp_Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='version_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
