# Generated by Django 3.0.7 on 2021-11-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0174_auto_20211029_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smsreceivelog',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sender', models.CharField(db_column='Sender', max_length=20)),
                ('smsc', models.CharField(blank=True, db_column='SMSC', max_length=50, null=True)),
                ('scts', models.CharField(blank=True, db_column='SCTS', max_length=50, null=True)),
                ('message', models.CharField(blank=True, db_column='Message', max_length=1000, null=True)),
                ('receivedtime', models.DateTimeField(blank=True, db_column='ReceivedTime', null=True)),
                ('customercode', models.CharField(blank=True, db_column='CustomerCode', max_length=20, null=True)),
                ('customername', models.CharField(blank=True, db_column='CustomerName', max_length=100, null=True)),
                ('appointmentcode', models.CharField(blank=True, db_column='appointmentCode', max_length=20, null=True)),
                ('handledon', models.DateTimeField(blank=True, db_column='HandledOn', null=True)),
                ('handledby', models.CharField(blank=True, db_column='HandledBy', max_length=100, null=True)),
            ],
            options={
                'db_table': 'SMSReceiveLog',
            },
        ),
    ]
