# Generated by Django 3.0.7 on 2021-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0175_smsreceivelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='new',
            field=models.BooleanField(blank=True, db_column='New', null=True),
        ),
    ]
