# Generated by Django 3.0.7 on 2021-11-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0176_auto_20211118_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='new',
            field=models.BooleanField(db_column='New', null=True),
        ),
    ]
