# Generated by Django 3.0.7 on 2021-11-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0179_auto_20211118_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appt_new',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='new',
            field=models.BooleanField(blank=True, db_column='New', null=True),
        ),
    ]
