# Generated by Django 3.0.7 on 2021-11-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0181_auto_20211118_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appt_new',
        ),
        migrations.AddField(
            model_name='appointment',
            name='new_appt',
            field=models.BooleanField(db_column='New_Appt', default=False),
        ),
    ]
