# Generated by Django 3.0.7 on 2021-12-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0184_tmpitemhelper_pospackage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillstaff',
            options={},
        ),
    ]
