# Generated by Django 3.0.7 on 2021-12-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0185_auto_20211209_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembatch',
            name='IsActive',
            field=models.IntegerField(blank=True, db_column='IsActive', default=1, null=True),
        ),
    ]
