# Generated by Django 3.0.7 on 2021-12-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0187_paytable_pay_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetup',
            name='content',
            field=models.TextField(blank=True, db_column='Content', null=True),
        ),
    ]
