# Generated by Django 3.0.7 on 2021-12-20 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0188_systemsetup_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsetup',
            name='content',
        ),
    ]
