# Generated by Django 3.0.7 on 2021-12-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0189_remove_systemsetup_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmspw',
            name='flgtransacdisc',
            field=models.BooleanField(db_column='flgtransacdisc', default=False),
        ),
    ]
