# Generated by Django 3.0.7 on 2021-12-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0191_stock_item_price_ceiling'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdept',
            name='pay_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemdiv',
            name='pay_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
