# Generated by Django 3.0.7 on 2022-01-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0192_auto_20211222_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardpolicy',
            options={},
        ),
    ]
