# Generated by Django 3.0.7 on 2022-01-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0193_auto_20220103_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpolicy',
            name='Item_Divid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.ItemDiv'),
        ),
        migrations.AddField(
            model_name='rewardpolicy',
            name='item_div',
            field=models.CharField(blank=True, db_column='Item_Div', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rewardpolicy',
            name='item_divdesc',
            field=models.CharField(blank=True, db_column='Item_DivDesc', max_length=300, null=True),
        ),
    ]
