# Generated by Django 3.0.7 on 2022-01-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0194_auto_20220103_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardpolicy',
            name='Item_Divid',
        ),
        migrations.RemoveField(
            model_name='rewardpolicy',
            name='item_div',
        ),
        migrations.RemoveField(
            model_name='rewardpolicy',
            name='item_divdesc',
        ),
        migrations.AddField(
            model_name='rewardpolicy',
            name='item_divids',
            field=models.ManyToManyField(blank=True, related_name='multi_item_divid', to='cl_table.ItemDiv'),
        ),
    ]
