# Generated by Django 3.0.7 on 2022-01-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0195_auto_20220104_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshaud',
            name='walkin',
        ),
    ]
