# Generated by Django 3.0.7 on 2022-01-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0196_remove_poshaud_walkin'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshaud',
            name='walkin',
            field=models.BooleanField(db_column='WalkIn', null=True),
        ),
    ]
