# Generated by Django 3.0.7 on 2022-02-12 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0197_poshaud_walkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpEpf',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('emp_code', models.CharField(blank=True, db_column='EMP_CODE', max_length=20, null=True)),
                ('emp_epf_employee', models.FloatField(db_column='EMP_EPF_EMPLOYEE')),
                ('emp_epf_employer', models.FloatField(db_column='EMP_EPF_EMPLOYER')),
            ],
            options={
                'db_table': 'EMP_EPF',
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('emp_code', models.CharField(blank=True, db_column='EMP_CODE', max_length=20, null=True)),
                ('salarymonth', models.DateField(db_column='SALARYMONTH')),
                ('basic', models.FloatField(db_column='BASIC')),
                ('ot', models.FloatField(db_column='OT')),
                ('commission', models.FloatField(db_column='COMMISSION')),
                ('incentives', models.FloatField(db_column='INCENTIVES')),
                ('others', models.FloatField(db_column='OTHERS')),
                ('total', models.FloatField(db_column='TOTAL')),
                ('status', models.FloatField(db_column='STATUS')),
            ],
            options={
                'db_table': 'EMPLOYEESALARY',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='emphoursalary',
            field=models.FloatField(blank=True, db_column='EMPHOURSALARY', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='flghourly',
            field=models.BooleanField(blank=True, db_column='FLGHOURLY', null=True),
        ),
        migrations.AddField(
            model_name='itemdiv',
            name='issellable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='EMP_EPFid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.EmpEpf'),
        ),
    ]
