# Generated by Django 3.0.7 on 2022-02-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0198_auto_20220212_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeSalary',
        ),
    ]
