# Generated by Django 3.0.7 on 2022-02-22 06:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0199_delete_employeesalary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageAuditingLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('treatment_parentcode', models.CharField(blank=True, db_column='Treatment_ParentCode', max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('package_type', models.CharField(blank=True, choices=[('Reversal', 'Reversal'), ('Void', 'Void'), ('Exchange', 'Exchange'), ('Redeem', 'Redeem')], db_column='package_type', max_length=20, null=True)),
                ('user_loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Fmspw')),
            ],
            options={
                'db_table': 'PackageAuditingLog',
            },
        ),
    ]
