# Generated by Django 3.0.7 on 2022-02-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0201_packageauditinglog_pa_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmspw',
            name='flgbackend',
            field=models.BooleanField(db_column='flgbackend', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgcatalog',
            field=models.BooleanField(db_column='flgcatalog', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgcommission',
            field=models.BooleanField(db_column='flgcommission', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgcustomer',
            field=models.BooleanField(db_column='flgcustomer', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgdashboard',
            field=models.BooleanField(db_column='flgdashboard', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgdayend',
            field=models.BooleanField(db_column='flgdayend', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flginventory',
            field=models.BooleanField(db_column='flginventory', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flginvoices',
            field=models.BooleanField(db_column='flginvoices', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgkpidashboard',
            field=models.BooleanField(db_column='flgkpidashboard', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgpayroll',
            field=models.BooleanField(db_column='flgpayroll', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgpo',
            field=models.BooleanField(db_column='flgpo', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgproject',
            field=models.BooleanField(db_column='flgproject', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgquantum',
            field=models.BooleanField(db_column='flgquantum', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgquotation',
            field=models.BooleanField(db_column='flgquotation', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgstaff',
            field=models.BooleanField(db_column='flgstaff', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgtcm',
            field=models.BooleanField(db_column='flgtcm', default=False),
        ),
    ]
