# Generated by Django 3.0.7 on 2022-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0202_auto_20220222_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmspw',
            name='flgbilling',
            field=models.BooleanField(db_column='flgbilling', default=False),
        ),
    ]
