# Generated by Django 3.0.7 on 2022-03-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0203_fmspw_flgbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='stripe_id',
            field=models.TextField(blank=True, db_column='StripeID', null=True),
        ),
    ]
