# Generated by Django 3.0.7 on 2022-03-14 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0204_customer_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshaud',
            name='date_ofchoose_dress',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poshaud',
            name='date_ofphotoshooting',
            field=models.DateField(blank=True, null=True),
        ),
    ]
