# Generated by Django 3.0.7 on 2022-03-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0207_auto_20220315_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redeempolicy',
            options={},
        ),
    ]
