# Generated by Django 3.0.7 on 2022-03-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0208_auto_20220316_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeempolicy',
            name='itemdiv_ids',
            field=models.ManyToManyField(blank=True, to='cl_table.ItemDiv'),
        ),
    ]
