# Generated by Django 3.0.7 on 2022-03-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0211_auto_20220316_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='store_card',
            field=models.BooleanField(blank=True, db_column='store_card', default=False, null=True),
        ),
    ]
