# Generated by Django 3.0.7 on 2022-03-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0212_customer_store_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='store_card',
        ),
        migrations.AddField(
            model_name='customer',
            name='cust_StoreCard',
            field=models.BooleanField(blank=True, db_column='cust_StoreCard', default=False, null=True),
        ),
    ]
