# Generated by Django 3.0.7 on 2022-03-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0213_auto_20220321_0635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempcustsign',
            fields=[
                ('id', models.SmallIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('cust_code', models.CharField(blank=True, db_column='Cust_Code', max_length=50, null=True)),
                ('transaction_no', models.CharField(blank=True, db_column='Transaction_No', max_length=50, null=True)),
                ('cust_sig', models.ImageField(blank=True, db_column='Cust_Sig', null=True, upload_to='img')),
                ('site_code', models.CharField(blank=True, db_column='SITE_CODE', max_length=4, null=True)),
                ('mac_code', models.CharField(blank=True, db_column='MAC_CODE', max_length=3, null=True)),
                ('mac_uid_ref', models.CharField(blank=True, db_column='MAC_UID_Ref', max_length=36, null=True)),
            ],
            options={
                'db_table': 'TempCustSign',
                'managed': False,
            },
        ),
    ]
