# Generated by Django 3.0.7 on 2022-03-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0214_tempcustsign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tempcustsign',
        ),
    ]
