# Generated by Django 3.0.7 on 2022-03-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0216_tempcustsign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulehour',
            old_name='shortdesc',
            new_name='shortDesc',
        ),
    ]
