# Generated by Django 3.0.7 on 2022-04-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0219_empsitelist_hide_in_appt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empsitelist',
            name='hide_in_appt',
            field=models.BooleanField(db_column='hide_in_appt', default=False, null=True),
        ),
    ]
