# Generated by Django 3.0.7 on 2022-04-05 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0220_auto_20220405_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empsitelist',
            name='hide_in_appt',
        ),
    ]
