# Generated by Django 3.0.7 on 2022-04-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0222_empsitelist_hide_in_appt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApptChannel',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('channel_code', models.CharField(blank=True, db_column='Channel_Code', max_length=20, null=True)),
                ('channel_desc', models.CharField(blank=True, db_column='Channel_Desc', max_length=50, null=True)),
                ('isactive', models.BooleanField(db_column='Active', default=True)),
            ],
            options={
                'db_table': 'Appt_Channel',
            },
        ),
    ]
