# Generated by Django 3.0.7 on 2022-04-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0226_auto_20220407_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApptChannel',
        ),
        migrations.RemoveField(
            model_name='empsitelist',
            name='hide_in_appt',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_status',
            field=models.CharField(blank=True, choices=[('Booking', 'Booking'), ('Waiting', 'Waiting List'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Arrived', 'Arrived'), ('Done', 'Done'), ('LastMinCancel', 'Cancelled Last Minute'), ('Late', 'Late'), ('No Show', 'No Show')], db_column='Appt_Status', default='Booking', max_length=20, null=True),
        ),
    ]
