# Generated by Django 3.0.7 on 2022-04-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0227_auto_20220412_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='empsitelist',
            name='hide_in_appt',
            field=models.BooleanField(db_column='hide_in_appt', default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appt_status',
            field=models.CharField(blank=True, choices=[('Booking', 'Booking'), ('Waiting', 'Waiting List'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Arrived', 'Arrived'), ('Done', 'Done'), ('LastMinCancel', 'Cancelled Last Minute'), ('Late', 'Late'), ('No Show', 'No Show'), ('Block', 'Block')], db_column='Appt_Status', default='Booking', max_length=20, null=True),
        ),
    ]
