# Generated by Django 3.0.7 on 2022-04-18 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0229_treatmentpackage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='treatmentpackage',
            table='Treatment_Package',
        ),
    ]
