# Generated by Django 3.0.7 on 2022-04-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0230_auto_20220418_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentpackage',
            name='lastsession_unit_amount',
            field=models.FloatField(blank=True, db_column='lastsession_unit_amount', null=True),
        ),
    ]
