# Generated by Django 3.0.7 on 2022-04-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0231_treatmentpackage_lastsession_unit_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='is_datainsert',
            field=models.BooleanField(default=False),
        ),
    ]
