# Generated by Django 3.0.7 on 2022-05-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0234_auto_20220524_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytable',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
