# Generated by Django 3.0.7 on 2022-06-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0236_empsitelist_emp_seq_webappt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='class_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='source_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='title_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('cust_code', 'cust_email', 'cust_phone1')},
        ),
    ]
