# Generated by Django 3.0.7 on 2022-06-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0237_auto_20220607_0942'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('cust_code', 'cust_email', 'cust_phone1', 'cust_phone2')},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='source_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='title_name',
        ),
    ]
