# Generated by Django 3.0.7 on 2022-06-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0239_auto_20220607_0950'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
    ]
