# Generated by Django 3.0.7 on 2022-06-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0241_auto_20220607_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustLogAudit',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cust_code', models.CharField(blank=True, db_column='Cust_Code', max_length=500, null=True)),
                ('username', models.CharField(blank=True, db_column='username', max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
                ('user_loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Fmspw')),
            ],
            options={
                'db_table': 'CustLogAudit',
            },
        ),
    ]
