# Generated by Django 3.0.7 on 2022-06-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0243_employee_isdelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='isdelete',
            field=models.BooleanField(db_column='IsDelete', default=False, null=True),
        ),
    ]
