# Generated by Django 3.0.7 on 2022-06-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0244_auto_20220616_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='flexi_expirydate',
            field=models.DateTimeField(blank=True, db_column='flexi_expirydate', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='flexipoints',
            field=models.FloatField(blank=True, db_column='flexipoints', null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='redeempoints',
            field=models.FloatField(blank=True, db_column='redeempoints', null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='flexipoints',
            field=models.FloatField(blank=True, db_column='flexipoints', null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='redeempoints',
            field=models.FloatField(blank=True, db_column='redeempoints', null=True),
        ),
    ]
