# Generated by Django 3.0.7 on 2022-06-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0245_auto_20220621_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='flexi_expirydate',
            field=models.DateField(blank=True, db_column='flexi_expirydate', null=True),
        ),
    ]
