# Generated by Django 3.0.7 on 2022-06-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0246_auto_20220621_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='flexi_expirydate',
        ),
    ]
