# Generated by Django 3.0.7 on 2022-06-24 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0247_remove_stock_flexi_expirydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cust_corporate',
            field=models.BooleanField(blank=True, db_column='cust_corporate', default=False, null=True),
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='name', max_length=500, null=True)),
                ('designation', models.CharField(blank=True, db_column='designation', max_length=500, null=True)),
                ('mobile_phone', models.CharField(blank=True, db_column='Mobile_phone', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=255, null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer')),
            ],
            options={
                'db_table': 'ContactPerson',
            },
        ),
    ]
