# Generated by Django 3.0.7 on 2022-06-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0248_auto_20220624_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cust_corporate',
            field=models.BooleanField(db_column='cust_corporate', default=False),
        ),
    ]
