# Generated by Django 3.0.7 on 2022-06-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0249_auto_20220624_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFlexiservice',
            fields=[
                ('itm_id', models.AutoField(db_column='itm_ID', primary_key=True, serialize=False)),
                ('item_code', models.CharField(blank=True, db_column='Item_Code', max_length=500, null=True)),
                ('item_srvcode', models.CharField(blank=True, db_column='Item_SrvCode', max_length=500, null=True)),
                ('item_srvdesc', models.CharField(blank=True, db_column='Item_SrvDesc', max_length=500, null=True)),
                ('itm_isactive', models.BooleanField(blank=True, db_column='Itm_IsActive', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Item_FlexiService',
            },
        ),
    ]
