# Generated by Django 3.0.7 on 2022-06-30 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0250_itemflexiservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemflexiservice',
            name='item_srvid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Stock'),
        ),
        migrations.AlterField(
            model_name='itemflexiservice',
            name='itm_isactive',
            field=models.BooleanField(db_column='Itm_IsActive', default=True),
        ),
    ]
