# Generated by Django 3.0.7 on 2022-07-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0251_auto_20220630_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='username', max_length=500, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('pp_no', models.CharField(db_column='PP_NO', max_length=500, null=True)),
                ('line_no', models.BigIntegerField(db_column='Line_No', null=True)),
                ('user_loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Fmspw')),
            ],
            options={
                'db_table': 'AuditLog',
            },
        ),
    ]
