# Generated by Django 3.0.7 on 2022-07-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0253_termsandcondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='is_datainsert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
