# Generated by Django 3.0.7 on 2022-07-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0254_auto_20220713_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='trans_footer5',
            field=models.CharField(blank=True, db_column='Trans_Footer5', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='title',
            name='trans_footer6',
            field=models.CharField(blank=True, db_column='Trans_Footer6', max_length=500, null=True),
        ),
    ]
