# Generated by Django 3.0.7 on 2022-07-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0255_auto_20220720_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerclass',
            name='autoclassamount',
            field=models.IntegerField(blank=True, db_column='autoclassamount', null=True),
        ),
    ]
