# Generated by Django 3.0.7 on 2022-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0256_customerclass_autoclassamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytable',
            name='paykey',
            field=models.IntegerField(blank=True, db_column='paykey', default=0, null=True),
        ),
    ]
