# Generated by Django 3.0.7 on 2022-07-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0257_paytable_paykey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytable',
            name='paykey',
            field=models.IntegerField(db_column='paykey', default=0),
        ),
    ]
