# Generated by Django 3.0.7 on 2022-07-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0258_auto_20220728_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytable',
            name='paykey',
            field=models.IntegerField(blank=True, db_column='paykey', default=0, null=True),
        ),
    ]
