# Generated by Django 3.0.7 on 2022-08-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0260_auto_20220808_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentpackage',
            name='sa_transacno',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='treatmentpackage',
            name='sa_transacno_ref',
            field=models.CharField(blank=True, db_column='SA_TransacNo_Ref', max_length=200, null=True),
        ),
    ]
