# Generated by Django 3.0.7 on 2022-08-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0261_auto_20220809_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='gstsetting',
            name='activefromdate',
            field=models.DateTimeField(blank=True, db_column='activefromdate', null=True),
        ),
        migrations.AddField(
            model_name='gstsetting',
            name='activetodate',
            field=models.DateTimeField(blank=True, db_column='activetodate', null=True),
        ),
    ]
