# Generated by Django 3.0.7 on 2022-08-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0054_itemsitelist_is_exclusive'),
        ('cl_table', '0262_auto_20220818_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dayendconfirmlog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='username', max_length=500, null=True)),
                ('dayend_date', models.DateField(blank=True, db_column='dayend_date', null=True)),
                ('confirm_date', models.DateTimeField(blank=True, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('dayend_pdf', models.ImageField(null=True, upload_to='img')),
                ('Site_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
                ('user_loginid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Fmspw')),
            ],
            options={
                'db_table': 'Dayendconfirmlog',
            },
        ),
    ]
