# Generated by Django 3.0.7 on 2022-08-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0263_dayendconfirmlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='maxclasssize',
            field=models.IntegerField(blank=True, db_column='maxclasssize', null=True),
        ),
    ]
