# Generated by Django 3.0.7 on 2022-08-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0265_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdocument',
            name='photo',
            field=models.BooleanField(blank=True, db_column='photo', null=True),
        ),
    ]
