# Generated by Django 3.0.7 on 2022-09-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0267_auto_20220830_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='autoappointment',
            field=models.BooleanField(blank=True, db_column='Autoappointment', null=True),
        ),
    ]
