# Generated by Django 3.0.7 on 2022-09-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0268_stock_autoappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioWork',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('work', models.CharField(blank=True, db_column='work', max_length=500, null=True)),
                ('dateplus', models.IntegerField(blank=True, db_column='dateplus', null=True)),
                ('isactive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'StudioWork',
            },
        ),
    ]
