# Generated by Django 3.0.7 on 2022-09-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0269_studiowork'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dt_lineno',
            field=models.IntegerField(blank=True, db_column='dt_LineNo', null=True),
        ),
    ]
