# Generated by Django 3.0.7 on 2022-09-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0271_studiowork_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlno',
            name='include_sitecode',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
