# Generated by Django 3.0.7 on 2022-09-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0272_controlno_include_sitecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlno',
            name='include_sitecode',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
