# Generated by Django 3.0.7 on 2022-09-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0273_auto_20220903_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlno',
            name='include_sitecode',
            field=models.BooleanField(default=False),
        ),
    ]
