# Generated by Django 3.0.7 on 2022-09-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0276_auto_20220906_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytable',
            name='pay_is_rounding',
            field=models.BooleanField(db_column='Pay_Is_Rounding', default=False, null=True),
        ),
    ]
