# Generated by Django 3.0.7 on 2022-09-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0280_auto_20220908_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayendconfirmlog',
            name='isdayend',
            field=models.BooleanField(blank=True, db_column='isdayend', null=True),
        ),
    ]
