# Generated by Django 3.0.7 on 2022-09-28 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0054_itemsitelist_is_exclusive'),
        ('cl_table', '0281_dayendconfirmlog_isdayend'),
    ]

    operations = [
        migrations.CreateModel(
            name='MGMPolicyCloud',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('level', models.CharField(db_column='level', max_length=200, null=True)),
                ('site_code', models.CharField(db_column='Site_Code', max_length=20, null=True)),
                ('isactive', models.BooleanField(db_column='IsActive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Site_Codeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'MGMPolicyCloud',
                'unique_together': {('level', 'Site_Codeid')},
            },
        ),
    ]
