# Generated by Django 3.0.7 on 2022-09-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0282_mgmpolicycloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgmpolicycloud',
            name='point_value',
            field=models.FloatField(blank=True, db_column='Point_Value', null=True),
        ),
    ]
