# Generated by Django 3.0.7 on 2022-09-29 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0284_customerreferral'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referredby_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer'),
        ),
        migrations.AddField(
            model_name='customerreferral',
            name='ispoints_awarded',
            field=models.BooleanField(db_column='ispoints_awarded', default=False),
        ),
    ]
