# Generated by Django 3.0.7 on 2022-09-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0285_auto_20220929_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreferral',
            name='cust_totpurchasevalue',
        ),
        migrations.AddField(
            model_name='mgmpolicycloud',
            name='minimum_purchase_amt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
