# Generated by Django 3.0.7 on 2022-10-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0288_auto_20221006_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MGMPolicyCloud',
        ),
    ]
