# Generated by Django 3.0.7 on 2022-10-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0054_itemsitelist_is_exclusive'),
        ('cl_table', '0289_delete_mgmpolicycloud'),
    ]

    operations = [
        migrations.CreateModel(
            name='MGMPolicyCloud',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('level', models.CharField(db_column='level', max_length=200, null=True)),
                ('point_value', models.FloatField(blank=True, db_column='Point_Value', null=True)),
                ('isactive', models.BooleanField(db_column='IsActive', default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('minimum_purchase_amt', models.FloatField(blank=True, null=True)),
                ('site_ids', models.ManyToManyField(blank=True, to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'MGMPolicyCloud',
                'unique_together': {('level', 'point_value')},
            },
        ),
    ]
