# Generated by Django 3.0.7 on 2022-10-06 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0290_mgmpolicycloud'),
    ]

    operations = [
        migrations.AddField(
            model_name='mgmpolicycloud',
            name='no_of_reward_times',
            field=models.IntegerField(blank=True, db_column='no_of_reward_times', null=True),
        ),
    ]
