# Generated by Django 3.0.7 on 2022-10-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0291_mgmpolicycloud_no_of_reward_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='date_booked',
            field=models.DateField(blank=True, db_column='date_booked', null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='remarks',
            field=models.CharField(blank=True, db_column='Remarks', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='status',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Cancelled', 'Cancelled'), ('Arrived', 'Arrived'), ('Done', 'Done')], db_column='status', max_length=200, null=True),
        ),
    ]
