# Generated by Django 3.0.7 on 2022-10-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0292_auto_20221007_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreferral',
            name='ispoints_awarded',
        ),
        migrations.AddField(
            model_name='customerreferral',
            name='rewards_given',
            field=models.IntegerField(db_column='rewards_given', default=0),
        ),
        migrations.AlterField(
            model_name='mgmpolicycloud',
            name='level',
            field=models.IntegerField(db_column='level', null=True),
        ),
    ]
