# Generated by Django 3.0.7 on 2022-10-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0293_auto_20221011_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpointdtl',
            name='mgm_level',
            field=models.IntegerField(db_column='mgm_level', null=True),
        ),
        migrations.AddField(
            model_name='customerpointdtl',
            name='reward_time',
            field=models.IntegerField(blank=True, db_column='reward_time', null=True),
        ),
    ]
