# Generated by Django 3.0.7 on 2022-10-17 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0294_auto_20221013_1409'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mgmpolicycloud',
            unique_together=set(),
        ),
    ]
