# Generated by Django 3.0.7 on 2022-10-18 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0054_itemsitelist_is_exclusive'),
        ('cl_table', '0295_auto_20221017_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='sitelistip',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, db_column='ip', max_length=500, null=True)),
                ('isactive', models.BooleanField(db_column='isactive', default=True)),
                ('siteid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'sitelistip',
            },
        ),
    ]
