# Generated by Django 3.0.7 on 2022-10-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0054_itemsitelist_is_exclusive'),
        ('cl_table', '0296_sitelistip'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempcustsign',
            name='cart_id',
            field=models.CharField(blank=True, db_column='cart_id', max_length=250, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='sitelistip',
            unique_together={('siteid', 'ip')},
        ),
    ]
