# Generated by Django 3.0.7 on 2022-10-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0298_participants_treatment_parentcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentpackage',
            name='balance',
            field=models.FloatField(db_column='Balance', null=True),
        ),
        migrations.AddField(
            model_name='treatmentpackage',
            name='outstanding',
            field=models.FloatField(blank=True, db_column='Outstanding', null=True),
        ),
        migrations.AddField(
            model_name='treatmentpackage',
            name='treatmentids',
            field=models.TextField(blank=True, db_column='treatmentids', null=True),
        ),
    ]
