# Generated by Django 3.0.7 on 2022-11-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0299_auto_20221028_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holditemdetail',
            name='sa_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
