# Generated by Django 3.0.7 on 2022-11-16 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0302_fmspw_flgservicelimit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemBatchSno',
        ),
    ]
