# Generated by Django 3.0.7 on 2022-11-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0304_itembatchsno'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembatchsno',
            name='batch_cost',
            field=models.FloatField(blank=True, db_column='BATCH_COST', null=True),
        ),
    ]
