# Generated by Django 3.0.7 on 2022-11-18 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0305_itembatchsno_batch_cost'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itembatchsno',
            unique_together={('batch_sno',)},
        ),
    ]
