# Generated by Django 3.0.7 on 2022-12-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0306_auto_20221118_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paygroup',
            name='picturelocation',
            field=models.ImageField(db_column='PICTURELOCATION', null=True, upload_to='img'),
        ),
    ]
