# Generated by Django 3.0.7 on 2022-12-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0307_auto_20221205_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itembatchsno',
            name='availability',
        ),
    ]
