# Generated by Django 3.0.7 on 2022-12-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0308_remove_itembatchsno_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembatchsno',
            name='availability',
            field=models.BooleanField(blank=True, db_column='Availability', null=True),
        ),
    ]
