# Generated by Django 3.0.7 on 2022-12-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0309_itembatchsno_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositaccount',
            name='item_description',
            field=models.CharField(blank=True, db_column='Item_Description', max_length=100, null=True),
        ),
    ]
