# Generated by Django 3.0.7 on 2022-12-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0311_auto_20221215_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmptreatment',
            name='course',
            field=models.CharField(blank=True, db_column='Course', max_length=280, null=True),
        ),
    ]
