# Generated by Django 3.0.7 on 2023-01-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0312_auto_20221222_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='estimated_deliverydate',
            field=models.DateField(blank=True, db_column='estimated_deliverydate', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_pregnant',
            field=models.BooleanField(blank=True, db_column='Pregnant_or_Nonpregnant', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_of_children',
            field=models.IntegerField(blank=True, db_column='no_of_children', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_of_weeks_pregnant',
            field=models.IntegerField(blank=True, db_column='no_of_weeks_pregnant', null=True),
        ),
    ]
