# Generated by Django 3.0.7 on 2023-01-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0313_auto_20230102_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='estimated_deliverydate',
            field=models.DateField(blank=True, db_column='EstimatedDeliveryDate', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_pregnant',
            field=models.BooleanField(blank=True, db_column='IsPregnant', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='no_of_children',
            field=models.IntegerField(blank=True, db_column='NoOfChildren', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='no_of_weeks_pregnant',
            field=models.IntegerField(blank=True, db_column='NoOfWeeksOfPregnancy', null=True),
        ),
    ]
