# Generated by Django 3.0.7 on 2023-01-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0314_auto_20230102_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='estimated_deliverydate',
            field=models.DateTimeField(blank=True, db_column='EstimatedDeliveryDate', null=True),
        ),
    ]
