# Generated by Django 3.0.7 on 2023-01-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0315_auto_20230102_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayendconfirmlog',
            name='dayend_pdf',
            field=models.ImageField(max_length=300, null=True, upload_to='img'),
        ),
    ]
