# Generated by Django 3.0.7 on 2023-01-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0316_auto_20230103_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_MembershipPrice',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('item_code', models.CharField(db_column='Item_Code', max_length=20)),
                ('class_code', models.CharField(db_column='Class_Code', max_length=50)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('discount_percent', models.FloatField(blank=True, db_column='DiscountPer', null=True)),
            ],
            options={
                'db_table': 'Item_MembershipPrice',
                'unique_together': {('item_code', 'class_code')},
            },
        ),
    ]
