# Generated by Django 3.0.7 on 2023-01-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0062_auto_20230112_1339'),
        ('cl_table', '0318_customerclass_package_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='item_sitelist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist'),
        ),
        migrations.AlterField(
            model_name='images',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Stock'),
        ),
        migrations.AlterField(
            model_name='posdaud',
            name='dt_itemnoid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Stock'),
        ),
    ]
