# Generated by Django 3.0.7 on 2023-03-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0319_auto_20230112_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletRequestLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('log_date', models.DateTimeField(blank=True, db_column='Log_Date', null=True)),
                ('cust_code', models.CharField(blank=True, db_column='Cust_Code', max_length=200, null=True)),
                ('cust_name', models.CharField(blank=True, db_column='Cust_Name', max_length=200, null=True)),
                ('from_site', models.CharField(blank=True, db_column='From_Site', max_length=200, null=True)),
                ('requesting_site', models.CharField(blank=True, db_column='Requesting_Site', max_length=200, null=True)),
                ('last_transaction', models.CharField(blank=True, db_column='Last_Transaction', max_length=200, null=True)),
                ('last_transaction_date', models.DateTimeField(blank=True, db_column='Last_Transaction_Date', null=True)),
                ('request_by', models.CharField(blank=True, db_column='Request_By', max_length=200, null=True)),
                ('req_date', models.DateTimeField(blank=True, db_column='Req_Date', null=True)),
                ('req_status', models.CharField(blank=True, db_column='Req_Status', max_length=20, null=True)),
                ('req_staff_code', models.CharField(blank=True, db_column='Req_Staff_Code', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Outlet_Request_Log',
            },
        ),
        migrations.RemoveField(
            model_name='treatmentpackage',
            name='treatmentids',
        ),
        migrations.AddField(
            model_name='multistaff',
            name='deposit',
            field=models.FloatField(db_column='Deposit', null=True),
        ),
        migrations.AddField(
            model_name='multistaff',
            name='gt1deposit',
            field=models.FloatField(db_column='GT1Deposit', null=True),
        ),
        migrations.AddField(
            model_name='paytable',
            name='paytypeimage',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterUniqueTogether(
            name='fmspw',
            unique_together={('pw_userlogin',)},
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('item_code',)},
        ),
        migrations.CreateModel(
            name='DisplayItem',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('menu_code', models.CharField(db_column='menuCode', max_length=10)),
                ('stockid', models.IntegerField(blank=True, db_column='stockId', null=True)),
            ],
            options={
                'db_table': 'displayItem',
                'unique_together': {('menu_code', 'stockid')},
            },
        ),
        migrations.CreateModel(
            name='DisplayCatalog',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('menu_code', models.CharField(db_column='menuCode', max_length=80)),
                ('parent_code', models.CharField(blank=True, db_column='parentCode', max_length=80, null=True)),
                ('menu_description', models.CharField(blank=True, db_column='menuDescription', max_length=300, null=True)),
                ('bgcolor', models.CharField(blank=True, db_column='bgColor', max_length=80, null=True)),
                ('imagepath', models.ImageField(blank=True, db_column='imagePath', null=True, upload_to='img')),
                ('seqnumber', models.IntegerField(blank=True, db_column='seqNumber', null=True)),
                ('isactive', models.BooleanField(db_column='isActive', default=True)),
            ],
            options={
                'db_table': 'DisplayCatalog',
                'unique_together': {('menu_code',)},
            },
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgbackend',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgbilling',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgcatalog',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgcommission',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgcustomer',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgdayend',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flginventory',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flginvoices',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgkpidashboard',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgpo',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgproject',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgquantum',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgquotation',
        ),
        migrations.RemoveField(
            model_name='fmspw',
            name='flgtcm',
        ),
    ]
