# Generated by Django 3.0.7 on 2023-03-29 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0320_auto_20230317_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmspw',
            name='flginvoicedate',
            field=models.BooleanField(db_column='flginvoicedate', default=False),
        ),
        migrations.AddField(
            model_name='fmspw',
            name='flgpayment',
            field=models.BooleanField(db_column='flgPayment', default=False),
        ),
    ]
