# Generated by Django 3.0.7 on 2023-06-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0323_auto_20230601_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaidaccount',
            name='pp_desc',
            field=models.CharField(blank=True, db_column='PP_DESC', max_length=250, null=True),
        ),
    ]
