# Generated by Django 3.0.7 on 2023-09-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0130_auto_20230731_1336'),
        ('cl_table', '0327_taxtype2taxcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepaidaccount',
            name='preacc_useid',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='prepaidaccountcondition',
            name='topup_remain',
            field=models.FloatField(blank=True, db_column='Topup_Remain', null=True),
        ),
        migrations.CreateModel(
            name='TempcartprepaidAccCond',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cart_id', models.CharField(max_length=20, null=True)),
                ('use_amt', models.FloatField(blank=True, db_column='Use_Amt', null=True)),
                ('bal_amt', models.FloatField(blank=True, db_column='Bal_Amt', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('itemcart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart')),
                ('prepaidaccount_cond', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.PrepaidAccountCondition')),
            ],
            options={
                'db_table': 'TempCartPrepaid_Account_Condition',
            },
        ),
    ]
