# Generated by Django 3.0.7 on 2023-09-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0328_auto_20230901_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempprepaidAccountCondition',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('pp_no', models.CharField(blank=True, db_column='PP_NO', max_length=50, null=True)),
                ('pp_type', models.CharField(blank=True, db_column='PP_TYPE', max_length=50, null=True)),
                ('pp_desc', models.CharField(blank=True, db_column='PP_DESC', max_length=50, null=True)),
                ('p_itemtype', models.CharField(blank=True, db_column='P_ItemType', max_length=50, null=True)),
                ('item_code', models.CharField(blank=True, max_length=20, null=True)),
                ('conditiontype1', models.CharField(blank=True, db_column='ConditionType1', max_length=20, null=True)),
                ('conditiontype2', models.CharField(blank=True, db_column='ConditionType2', max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, db_column='Amount', decimal_places=4, max_digits=19, null=True)),
                ('rate', models.CharField(blank=True, db_column='Rate', max_length=20, null=True)),
                ('membercardnoaccess', models.BooleanField(db_column='MemberCardNoAccess', null=True)),
                ('use_amt', models.FloatField(blank=True, db_column='Use_Amt', null=True)),
                ('remain', models.FloatField(blank=True, db_column='Remain', null=True)),
                ('pos_daud_lineno', models.FloatField(blank=True, db_column='POS_Daud_LineNo', null=True)),
                ('mac_uid_ref', models.CharField(blank=True, db_column='MAC_UID_Ref', max_length=50, null=True)),
                ('cart_id', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('prepaid_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.PrepaidAccount')),
                ('prepaidaccount_cond', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.PrepaidAccountCondition')),
            ],
            options={
                'db_table': 'TempPrepaid_Account_Condition',
            },
        ),
    ]
