# Generated by Django 3.0.7 on 2023-09-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0330_outletdocument_staffdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempprepaidaccountcondition',
            name='cart_id',
        ),
        migrations.RemoveField(
            model_name='tempprepaidaccountcondition',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tempprepaidaccountcondition',
            name='prepaid_account',
        ),
        migrations.RemoveField(
            model_name='tempprepaidaccountcondition',
            name='prepaidaccount_cond',
        ),
    ]
