# Generated by Django 3.0.7 on 2023-09-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0331_auto_20230901_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempprepaidaccountcondition',
            name='cart_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tempprepaidaccountcondition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tempprepaidaccountcondition',
            name='prepaid_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.PrepaidAccount'),
        ),
        migrations.AddField(
            model_name='tempprepaidaccountcondition',
            name='prepaidaccount_cond',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.PrepaidAccountCondition'),
        ),
    ]
