# Generated by Django 3.0.7 on 2020-10-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSitelist',
            fields=[
                ('itemsite_id', models.BigAutoField(db_column='ItemSite_ID', primary_key=True, serialize=False)),
                ('itemsite_code', models.CharField(db_column='ItemSite_Code', max_length=20, null=True)),
                ('itemsite_desc', models.CharField(blank=True, db_column='ItemSite_Desc', max_length=60, null=True)),
                ('itemsite_type', models.CharField(blank=True, db_column='ItemSite_Type', max_length=10, null=True)),
                ('item_purchasedept', models.CharField(blank=True, db_column='Item_PurchaseDept', max_length=20, null=True)),
                ('itemsite_address', models.CharField(blank=True, db_column='ItemSite_Address', max_length=255, null=True)),
                ('itemsite_postcode', models.CharField(blank=True, db_column='ItemSite_Postcode', max_length=20, null=True)),
                ('itemsite_city', models.CharField(blank=True, db_column='ItemSite_City', max_length=50, null=True)),
                ('itemsite_state', models.CharField(blank=True, db_column='ItemSite_State', max_length=50, null=True)),
                ('itemsite_country', models.CharField(blank=True, db_column='ItemSite_Country', max_length=50, null=True)),
                ('itemsite_phone1', models.CharField(blank=True, db_column='ItemSite_Phone1', max_length=50, null=True)),
                ('itemsite_phone2', models.CharField(blank=True, db_column='ItemSite_Phone2', max_length=50, null=True)),
                ('itemsite_fax', models.CharField(blank=True, db_column='ItemSite_Fax', max_length=50, null=True)),
                ('itemsite_email', models.CharField(blank=True, db_column='ItemSite_Email', max_length=50, null=True)),
                ('itemsite_user', models.CharField(blank=True, db_column='ItemSite_User', max_length=50, null=True)),
                ('itemsite_date', models.DateTimeField(blank=True, db_column='ItemSite_Date', null=True)),
                ('itemsite_time', models.DateTimeField(blank=True, db_column='ItemSite_Time', null=True)),
                ('itemsite_isactive', models.BooleanField(db_column='ItemSite_Isactive', null=True)),
                ('itemsite_refcode', models.CharField(blank=True, db_column='ITEMSITE_REFCODE', max_length=20, null=True)),
                ('site_group', models.CharField(blank=True, db_column='Site_Group', max_length=50, null=True)),
                ('site_is_gst', models.BooleanField(db_column='SITE_IS_GST', null=True)),
                ('account_code', models.CharField(blank=True, db_column='Account_Code', max_length=20, null=True)),
                ('clientindex', models.BigIntegerField(blank=True, db_column='ClientIndex', null=True)),
                ('heartbeat', models.DateTimeField(blank=True, db_column='HeartBeat', null=True)),
                ('systemlog_mdpl_update', models.BooleanField(db_column='SystemLog_MDPL_Update', null=True)),
                ('geolink', models.CharField(blank=True, max_length=100, null=True)),
                ('weekdays_timing', models.CharField(blank=True, max_length=100, null=True)),
                ('weekend_timing', models.CharField(blank=True, max_length=100, null=True)),
                ('holliday_timing', models.CharField(blank=True, max_length=100, null=True)),
                ('closed_on', models.CharField(blank=True, db_column='Closed_on', max_length=100, null=True)),
                ('picpath', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, db_column='Owner', max_length=300, null=True)),
            ],
            options={
                'db_table': 'Item_SiteList',
            },
        ),
        migrations.CreateModel(
            name='SiteGroup',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=20, null=True)),
                ('description', models.CharField(db_column='Description', max_length=100, null=True)),
                ('is_active', models.BooleanField(db_column='Is_Active', null=True)),
                ('is_delete', models.BooleanField(db_column='Is_Delete', null=True)),
            ],
            options={
                'db_table': 'Site_Group',
            },
        ),
    ]
