# Generated by Django 3.0.7 on 2020-10-09 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsitelist',
            name='Site_Groupid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.SiteGroup'),
        ),
        migrations.AddField(
            model_name='itemsitelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='itemsitelist',
            name='pic_path',
            field=models.TextField(blank=True, db_column='pic_Path', null=True),
        ),
        migrations.AddField(
            model_name='itemsitelist',
            name='qrcode',
            field=models.CharField(blank=True, db_column='QRCode', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='itemsitelist',
            name='ratings',
            field=models.CharField(blank=True, db_column='Ratings', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='itemsitelist',
            name='sitedbconnectionurl',
            field=models.CharField(blank=True, db_column='siteDbConnectionUrl', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemsitelist',
            name='skills_list',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='itemsitelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='sitegroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='sitegroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemsitelist',
            name='itemsite_date',
            field=models.DateField(blank=True, db_column='ItemSite_Date', null=True),
        ),
        migrations.AlterField(
            model_name='itemsitelist',
            name='itemsite_email',
            field=models.EmailField(blank=True, db_column='ItemSite_Email', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemsitelist',
            name='itemsite_isactive',
            field=models.BooleanField(db_column='ItemSite_Isactive', default=True),
        ),
        migrations.AlterField(
            model_name='itemsitelist',
            name='itemsite_phone1',
            field=models.CharField(db_column='ItemSite_Phone1', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='is_active',
            field=models.BooleanField(db_column='Is_Active', default=True),
        ),
    ]
