# Generated by Django 3.0.7 on 2020-10-12 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0003_auto_20201009_1642'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemsitelist',
            unique_together={('itemsite_desc', 'itemsite_phone1', 'itemsite_email')},
        ),
    ]
