# Generated by Django 3.0.7 on 2020-10-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0004_auto_20201012_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitegroup',
            name='code',
            field=models.CharField(db_column='Code', default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='description',
            field=models.CharField(db_column='Description', default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitegroup',
            name='is_delete',
            field=models.BooleanField(db_column='Is_Delete', default=False),
        ),
    ]
