# Generated by Django 3.0.7 on 2020-10-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0006_auto_20201012_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsitelist',
            name='site_is_gst',
            field=models.BooleanField(db_column='SITE_IS_GST', default=False, null=True),
        ),
    ]
