# Generated by Django 3.0.7 on 2020-11-03 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0009_tempuomprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseTrmtReason',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rev_no', models.CharField(blank=True, db_column='Rev_No', max_length=50, null=True)),
                ('rev_desc', models.CharField(blank=True, db_column='Rev_Desc', max_length=50, null=True)),
                ('rev_remark', models.CharField(blank=True, db_column='Rev_Remark', max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, db_column='Is_active', null=True)),
            ],
            options={
                'db_table': 'Reverse_Trmt_Reason',
            },
        ),
    ]
