# Generated by Django 3.0.7 on 2020-11-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0010_reversetrmtreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reversetrmtreason',
            name='is_active',
            field=models.BooleanField(blank=True, db_column='Is_active', default=True, null=True),
        ),
    ]
