# Generated by Django 3.0.7 on 2020-11-06 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0011_auto_20201103_0626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempUomPrice',
        ),
    ]
