# Generated by Django 3.0.7 on 2020-11-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0012_delete_tempuomprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoidReason',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason_code', models.CharField(blank=True, db_column='Reason_Code', max_length=20, null=True)),
                ('reason_desc', models.CharField(blank=True, db_column='Reason_Desc', max_length=50, null=True)),
                ('isactive', models.BooleanField(blank=True, db_column='IsActive', null=True)),
            ],
            options={
                'db_table': 'Void_Reason',
            },
        ),
    ]
