# Generated by Django 3.0.7 on 2020-11-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0013_voidreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voidreason',
            name='isactive',
            field=models.BooleanField(blank=True, db_column='IsActive', default=True, null=True),
        ),
    ]
