# Generated by Django 3.0.7 on 2020-12-30 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0015_loggedinuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loggedinuser',
            table='Logged_InUser',
        ),
    ]
