# Generated by Django 3.0.7 on 2020-12-31 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0016_auto_20201230_0051'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loggedinuser',
            table='logged_inuser',
        ),
    ]
