# Generated by Django 3.0.7 on 2021-01-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0017_auto_20201231_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='current_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
