# Generated by Django 3.0.7 on 2021-01-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0018_loggedinuser_current_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggedinuser',
            name='current_key',
        ),
    ]
