# Generated by Django 3.0.7 on 2021-01-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0019_remove_loggedinuser_current_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggedinuser',
            name='current_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
