# Generated by Django 3.0.7 on 2021-01-15 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0020_loggedinuser_current_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoggedInUser',
        ),
    ]
