# Generated by Django 3.0.7 on 2021-03-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0022_treatmentusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentusage',
            options={},
        ),
    ]
