# Generated by Django 3.0.7 on 2021-04-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0024_treatmentusage_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentusage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentusage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
