# Generated by Django 3.0.7 on 2021-04-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0026_usagememo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagememo',
            options={},
        ),
    ]
