# Generated by Django 3.0.7 on 2021-04-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0027_auto_20210406_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagememo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usagememo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
