# Generated by Django 3.0.7 on 2021-04-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0028_auto_20210406_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagememo',
            name='time_out',
            field=models.DateTimeField(auto_now=True, db_column='Time_Out', null=True),
        ),
    ]
