# Generated by Django 3.0.7 on 2021-04-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0029_auto_20210406_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatmentface',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('treatment_code', models.CharField(db_column='Treatment_Code', max_length=50)),
                ('str1', models.CharField(blank=True, db_column='Str1', max_length=100, null=True)),
                ('str2', models.CharField(blank=True, db_column='Str2', max_length=100, null=True)),
                ('str3', models.CharField(blank=True, db_column='Str3', max_length=100, null=True)),
                ('str4', models.CharField(blank=True, db_column='Str4', max_length=100, null=True)),
                ('str5', models.CharField(blank=True, db_column='Str5', max_length=100, null=True)),
                ('str6', models.CharField(blank=True, db_column='Str6', max_length=100, null=True)),
                ('str7', models.CharField(blank=True, db_column='Str7', max_length=100, null=True)),
                ('site_code', models.CharField(db_column='Site_Code', max_length=50)),
            ],
            options={
                'db_table': 'TreatmentFace',
                'managed': False,
            },
        ),
    ]
