# Generated by Django 3.0.7 on 2021-04-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0030_treatmentface'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentface',
            options={},
        ),
    ]
