# Generated by Django 3.0.7 on 2021-04-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0031_auto_20210419_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentface',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentface',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='treatmentface',
            unique_together={('treatment_code', 'site_code')},
        ),
    ]
