# Generated by Django 3.0.7 on 2021-04-30 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0033_usagelevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagelevel',
            options={},
        ),
    ]
