# Generated by Django 3.0.7 on 2021-04-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0034_auto_20210430_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagelevel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usagelevel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='usagelevel',
            name='isactive',
            field=models.BooleanField(db_column='IsActive', default=True),
        ),
    ]
