# Generated by Django 3.0.7 on 2021-06-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0039_itemsitelist_is_nric'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsitelist',
            name='is_automember',
            field=models.BooleanField(db_column='Is Auto Member', default=False),
        ),
    ]
