# Generated by Django 3.0.7 on 2021-06-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0040_itemsitelist_is_automember'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsitelist',
            name='cell_duration',
            field=models.CharField(blank=True, db_column='Cell_Duration', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemsitelist',
            name='endday_hour',
            field=models.CharField(blank=True, db_column='EndDay_Hour', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemsitelist',
            name='interval',
            field=models.CharField(blank=True, db_column='Interval', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemsitelist',
            name='startday_hour',
            field=models.CharField(blank=True, db_column='StartDay_Hour', max_length=100, null=True),
        ),
    ]
