# Generated by Django 3.0.7 on 2021-06-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0041_auto_20210621_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsitelist',
            name='interval',
        ),
        migrations.AddField(
            model_name='itemsitelist',
            name='resource_count',
            field=models.CharField(blank=True, db_column='Resource Count', max_length=100, null=True),
        ),
    ]
