# Generated by Django 3.0.7 on 2021-06-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0042_auto_20210621_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsitelist',
            name='inv_templatename',
            field=models.CharField(blank=True, db_column='Invoice_TemplateName', max_length=500, null=True),
        ),
    ]
