# Generated by Django 3.0.7 on 2021-07-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0043_itemsitelist_inv_templatename'),
        ('cl_app', '0037_auto_20210516_2145'),
    ]

    operations = [
    ]
