# Generated by Django 3.0.7 on 2021-08-23 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0045_auto_20210802_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsitelist',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
