# Generated by Django 3.0.7 on 2021-10-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0049_pricechangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricechangelog',
            name='lineno',
            field=models.IntegerField(blank=True, db_column='LineNo', null=True),
        ),
    ]
