# Generated by Django 3.0.7 on 2021-12-09 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0050_pricechangelog_lineno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsitelist',
            name='resource_count',
            field=models.CharField(blank=True, db_column='resource_count', max_length=100, null=True),
        ),
    ]
