# Generated by Django 3.0.7 on 2022-07-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0051_auto_20211209_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsitelist',
            name='service_sel',
            field=models.BooleanField(db_column='Service_Selection', default=False),
        ),
        migrations.AlterField(
            model_name='itemsitelist',
            name='service_text',
            field=models.BooleanField(db_column='Service_Text', default=False),
        ),
    ]
