# Generated by Django 3.0.7 on 2022-08-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0053_tmptreatmentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsitelist',
            name='is_exclusive',
            field=models.BooleanField(null=True),
        ),
    ]
