# Generated by Django 3.0.7 on 2022-11-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0055_voucherpromo'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherpromo',
            name='price',
            field=models.FloatField(blank=True, db_column='Price', null=True),
        ),
    ]
