# Generated by Django 3.0.7 on 2022-11-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0057_smsprocesslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsitelist',
            name='walkin_custid',
            field=models.IntegerField(blank=True, db_column='Walkin_Custid', null=True),
        ),
    ]
