# Generated by Django 3.0.7 on 2022-12-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0059_auto_20221208_1815'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voucherpromo',
            unique_together={('price', 'isdiscount', 'conditiontype1', 'conditiontype2')},
        ),
    ]
