# Generated by Django 3.0.7 on 2023-01-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0319_auto_20230112_1339'),
        ('cl_app', '0064_auto_20230112_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmpitemhelpersession',
            name='helper_code',
            field=models.CharField(blank=True, db_column='Helper_Code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tmpitemhelpersession',
            name='helper_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee'),
        ),
        migrations.AddField(
            model_name='tmpitemhelpersession',
            name='helper_name',
            field=models.CharField(blank=True, db_column='Helper_Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tmpitemhelpersession',
            name='sa_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tmpitemhelpersession',
            name='session',
            field=models.FloatField(blank=True, db_column='Session', null=True),
        ),
        migrations.AddField(
            model_name='tmpitemhelpersession',
            name='site_code',
            field=models.CharField(blank=True, db_column='Site_Code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tmpitemhelpersession',
            name='wp1',
            field=models.FloatField(blank=True, db_column='WP1', null=True),
        ),
        migrations.AlterField(
            model_name='tmpitemhelpersession',
            name='treatmentpackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cl_table.TreatmentPackage'),
        ),
    ]
