# Generated by Django 3.0.7 on 2023-01-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0319_auto_20230112_1339'),
        ('cl_app', '0070_auto_20230118_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmpitemhelpersession',
            name='treatmentpackage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.TreatmentPackage'),
        ),
    ]
