# Generated by Django 3.0.7 on 2023-01-18 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0071_auto_20230118_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmpitemhelpersession',
            name='treatmentpackage',
        ),
    ]
