# Generated by Django 3.0.7 on 2023-04-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reportmaster',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('code', models.CharField(db_column='Code', max_length=255)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.TextField(db_column='Description')),
                ('pageid', models.CharField(db_column='PageID', max_length=255)),
                ('url', models.CharField(db_column='URL', max_length=255)),
                ('image', models.CharField(db_column='Image', max_length=255)),
                ('seq', models.IntegerField(db_column='Seq')),
                ('inactive', models.CharField(blank=True, db_column='InActive', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ReportMaster',
            },
        ),
    ]
