# Generated by Django 3.0.7 on 2023-04-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmaster',
            name='image',
            field=models.ImageField(db_column='Image', max_length=255, upload_to='img'),
        ),
    ]
