# Generated by Django 3.0.7 on 2023-04-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_reports', '0002_auto_20230414_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmaster',
            name='code',
            field=models.CharField(db_column='Code', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportmaster',
            name='description',
            field=models.TextField(db_column='Description', null=True),
        ),
        migrations.AlterField(
            model_name='reportmaster',
            name='pageid',
            field=models.CharField(db_column='PageID', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reportmaster',
            name='url',
            field=models.CharField(db_column='URL', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='reportmaster',
            unique_together={('name',)},
        ),
    ]
