# Generated by Django 3.0.7 on 2022-02-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clpayroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_salary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
