# Generated by Django 3.0.7 on 2022-02-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clpayroll', '0003_auto_20220215_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_salary',
            name='firstovertimehour',
            field=models.FloatField(blank=True, db_column='firstOverTimeHour', null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='firstovertimerate',
            field=models.FloatField(blank=True, db_column='firstOverTimeRate', null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='hourlysalhour',
            field=models.FloatField(blank=True, db_column='hourlySalHour', null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='hourlysalrate',
            field=models.FloatField(blank=True, db_column='hourlySalRate', null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='secondovertimehour',
            field=models.FloatField(blank=True, db_column='secondOverTimeHour', null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='secondovertimerate',
            field=models.FloatField(blank=True, db_column='secondOverTimeRate', null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='totallowance',
            field=models.FloatField(blank=True, db_column='totAllowance', null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='totcommission',
            field=models.FloatField(blank=True, db_column='totCommission', null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='tototpay',
            field=models.FloatField(blank=True, db_column='totOTPay', null=True),
        ),
    ]
