# Generated by Django 3.0.7 on 2022-02-15 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clpayroll', '0004_auto_20220215_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentList',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
                ('type_name', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('Penalties', 'Penalties'), ('Basic', 'Basic'), ('OT', 'OT'), ('Commission', 'Commission'), ('Allowance', 'Allowance'), ('Claims', 'Claims'), ('Incentives', 'Incentives'), ('Bonus', 'Bonus')], max_length=500, null=True)),
                ('amount', models.FloatField(blank=True, db_column='amount', null=True)),
                ('emp_salaryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clpayroll.Employee_Salary')),
            ],
            options={
                'db_table': 'PaymentList',
            },
        ),
        migrations.CreateModel(
            name='DeductionList',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
                ('type_name', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('Penalties', 'Penalties'), ('Basic', 'Basic'), ('OT', 'OT'), ('Commission', 'Commission'), ('Allowance', 'Allowance'), ('Claims', 'Claims'), ('Incentives', 'Incentives'), ('Bonus', 'Bonus')], max_length=500, null=True)),
                ('amount', models.FloatField(blank=True, db_column='amount', null=True)),
                ('emp_salaryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clpayroll.Employee_Salary')),
            ],
            options={
                'db_table': 'DeductionList',
            },
        ),
        migrations.CreateModel(
            name='AllowanceList',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('desc', models.TextField(null=True)),
                ('type_name', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('Penalties', 'Penalties'), ('Basic', 'Basic'), ('OT', 'OT'), ('Commission', 'Commission'), ('Allowance', 'Allowance'), ('Claims', 'Claims'), ('Incentives', 'Incentives'), ('Bonus', 'Bonus')], max_length=500, null=True)),
                ('amount', models.FloatField(blank=True, db_column='amount', null=True)),
                ('emp_salaryid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clpayroll.Employee_Salary')),
            ],
            options={
                'db_table': 'AllowanceList',
            },
        ),
    ]
