# Generated by Django 3.0.7 on 2022-02-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clpayroll', '0005_allowancelist_deductionlist_paymentlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_salary',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
        ),
    ]
