# Generated by Django 3.0.7 on 2022-02-15 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clpayroll', '0007_auto_20220215_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_salary',
            name='is_active',
        ),
    ]
