# Generated by Django 3.0.7 on 2022-02-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clpayroll', '0008_remove_employee_salary_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_salary',
            name='checkbox',
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='addpay',
            field=models.FloatField(blank=True, db_column='AddPay', null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='dateofpay',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='empcpfcont',
            field=models.FloatField(blank=True, db_column='empCPFCont', null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='netpay',
            field=models.FloatField(blank=True, db_column='netPay', null=True),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='totdeduct',
            field=models.FloatField(blank=True, db_column='totDeduct', null=True),
        ),
    ]
