# Generated by Django 3.0.7 on 2022-02-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0059_modeofpayment_salarysubtypelookup'),
        ('clpayroll', '0009_auto_20220215_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowancelist',
            name='type_name',
        ),
        migrations.RemoveField(
            model_name='deductionlist',
            name='type_name',
        ),
        migrations.RemoveField(
            model_name='paymentlist',
            name='type_name',
        ),
        migrations.AddField(
            model_name='allowancelist',
            name='type_nameid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.SalarySubTypeLookup'),
        ),
        migrations.AddField(
            model_name='deductionlist',
            name='type_nameid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.SalarySubTypeLookup'),
        ),
        migrations.AddField(
            model_name='employee_salary',
            name='modeofPayid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='custom.ModeOfPayment'),
        ),
        migrations.AddField(
            model_name='paymentlist',
            name='type_nameid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.SalarySubTypeLookup'),
        ),
    ]
