# Generated by Django 3.0.7 on 2022-02-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clpayroll', '0010_auto_20220216_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_salary',
            name='isactive',
        ),
    ]
