# Generated by Django 3.0.7 on 2023-01-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0319_auto_20230112_1339'),
        ('custom', '0127_auto_20230112_1339'),
        ('clpayroll', '0011_remove_employee_salary_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowancelist',
            name='emp_salaryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clpayroll.Employee_Salary'),
        ),
        migrations.AlterField(
            model_name='deductionlist',
            name='emp_salaryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clpayroll.Employee_Salary'),
        ),
        migrations.AlterField(
            model_name='employee_salary',
            name='empid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee'),
        ),
        migrations.AlterField(
            model_name='employee_salary',
            name='modeofPayid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ModeOfPayment'),
        ),
        migrations.AlterField(
            model_name='paymentlist',
            name='emp_salaryid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clpayroll.Employee_Salary'),
        ),
    ]
