# Generated by Django 3.0.7 on 2022-11-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebConsultation_Hdr',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('doc_no', models.CharField(blank=True, db_column='DocNo', max_length=255, null=True)),
                ('cust_code', models.CharField(blank=True, db_column='CustCode', max_length=255, null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('doc_date', models.DateTimeField(blank=True, db_column='DocDate', null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('consultant_code', models.CharField(blank=True, db_column='Consultant_Code', max_length=50, null=True)),
            ],
            options={
                'db_table': 'WebConsultation_Hdr',
            },
        ),
    ]
