# Generated by Django 3.0.7 on 2022-11-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0002_auto_20221123_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebConsultation_Question',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('question_group', models.CharField(blank=True, db_column='QuestionGroup', max_length=200, null=True)),
                ('question_number', models.IntegerField(blank=True, db_column='QuestionNumber', null=True)),
                ('page_number', models.IntegerField(blank=True, db_column='PageNumber', null=True)),
                ('isactive', models.BooleanField(default=True)),
                ('question_type', models.IntegerField(blank=True, db_column='QuestionType', null=True)),
                ('image', models.ImageField(blank=True, db_column='image', null=True, upload_to='img')),
                ('question_english', models.CharField(blank=True, db_column='QuestionEnglish', max_length=500, null=True)),
                ('question_chinese', models.CharField(blank=True, db_column='QuestionChinese', max_length=500, null=True)),
                ('question_others', models.CharField(blank=True, db_column='QuestionOthers', max_length=500, null=True)),
            ],
            options={
                'db_table': 'WebConsultation_Question',
            },
        ),
    ]
