# Generated by Django 3.0.7 on 2022-11-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0057_smsprocesslog'),
        ('cl_ipad', '0003_webconsultation_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='webconsultation_question',
            name='site_ids',
            field=models.ManyToManyField(blank=True, to='cl_app.ItemSitelist'),
        ),
        migrations.AlterUniqueTogether(
            name='webconsultation_hdr',
            unique_together={('cust_code', 'site_code', 'consultant_code', 'doc_date')},
        ),
    ]
