# Generated by Django 3.0.7 on 2022-11-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0004_auto_20221124_1104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='webconsultation_hdr',
            unique_together=set(),
        ),
    ]
