# Generated by Django 3.0.7 on 2022-11-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0006_webconsultation_hdr_site_codeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebConsultation_AnalysisResult',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('doc_no', models.CharField(db_column='DocNo', max_length=255)),
                ('cust_code', models.CharField(blank=True, db_column='CustCode', max_length=255, null=True)),
                ('site_code', models.CharField(blank=True, db_column='SiteCode', max_length=20, null=True)),
                ('isactive', models.BooleanField(db_column='IsActive', default=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('cust_weight', models.FloatField(blank=True, db_column='CustWeight', null=True)),
                ('cust_height', models.FloatField(blank=True, db_column='CustHeight', null=True)),
                ('fat_mass', models.FloatField(blank=True, db_column='FatMass', null=True)),
                ('bmi', models.FloatField(blank=True, db_column='BMI', null=True)),
                ('target_weight', models.FloatField(blank=True, db_column='TargetWeight', null=True)),
                ('must_lose_weight', models.FloatField(blank=True, db_column='MustLoseWeight', null=True)),
                ('face_forehead', models.CharField(blank=True, db_column='FaceForeHead', max_length=30, null=True)),
                ('face_nosearea', models.CharField(blank=True, db_column='FaceNoseArea', max_length=30, null=True)),
                ('face_eyearea', models.CharField(blank=True, db_column='FaceEyeArea', max_length=30, null=True)),
                ('face_facearea', models.CharField(blank=True, db_column='FaceFaceArea', max_length=30, null=True)),
                ('face_neckarea', models.CharField(blank=True, db_column='FaceNeckArea', max_length=30, null=True)),
                ('face_remark', models.CharField(blank=True, db_column='FaceRemark', max_length=300, null=True)),
                ('waist_measure', models.FloatField(blank=True, db_column='WaistMeasure', null=True)),
                ('waist_remark', models.CharField(blank=True, db_column='WaistRemark', max_length=300, null=True)),
                ('tummy_measure', models.FloatField(blank=True, db_column='TummyMeasure', null=True)),
                ('tummy_remark', models.CharField(blank=True, db_column='TummyRemark', max_length=300, null=True)),
                ('buttock_measure', models.FloatField(blank=True, db_column='ButtockMeasure', null=True)),
                ('buttock_remark', models.CharField(blank=True, db_column='ButtockRemark', max_length=300, null=True)),
                ('thigh_measure', models.FloatField(blank=True, db_column='ThighMeasure', null=True)),
                ('thigh_remark', models.CharField(blank=True, db_column='ThighRemark', max_length=300, null=True)),
                ('lower_legmeasure', models.FloatField(blank=True, db_column='LowerLegMeasure', null=True)),
                ('lower_legremark', models.CharField(blank=True, db_column='LowerLegRemark', max_length=300, null=True)),
                ('arm_measure', models.FloatField(blank=True, db_column='ArmMeasure', null=True)),
                ('arm_remark', models.CharField(blank=True, db_column='ArmRemark', max_length=300, null=True)),
                ('rounded_shouldermeasure', models.FloatField(blank=True, db_column='RoundedShoulderMeasure', null=True)),
                ('rounded_shoulderremark', models.CharField(blank=True, db_column='RoundedShoulderRemark', max_length=300, null=True)),
                ('create_date', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('create_by', models.CharField(blank=True, db_column='CreateBy', max_length=20, null=True)),
                ('last_updatedate', models.DateTimeField(blank=True, db_column='LastUpdateDate', null=True)),
                ('last_updateby', models.CharField(blank=True, db_column='LastUpdateBy', max_length=20, null=True)),
                ('therapist_id', models.CharField(blank=True, db_column='TherapistID', max_length=50, null=True)),
            ],
            options={
                'db_table': 'WebConsultation_AnalysisResult',
            },
        ),
    ]
