# Generated by Django 3.0.7 on 2022-11-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0009_webconsultation_referral'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebConsultation_Referral_Hdr',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('doc_no', models.CharField(db_column='DocNo', max_length=255)),
                ('site_code', models.CharField(blank=True, db_column='SiteCode', max_length=20, null=True)),
                ('isactive', models.BooleanField(db_column='IsActive', default=True)),
                ('signature_img', models.ImageField(blank=True, db_column='SignatureImg', null=True, upload_to='img')),
                ('welcomedoor_signatureimg', models.ImageField(blank=True, db_column='WelcomeDoorSignatureImg', null=True, upload_to='img')),
                ('create_date', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('create_by', models.CharField(blank=True, db_column='CreateBy', max_length=20, null=True)),
                ('last_updatedate', models.DateTimeField(blank=True, db_column='LastUpdateDate', null=True)),
                ('last_updateby', models.CharField(blank=True, db_column='LastUpdateBy', max_length=20, null=True)),
            ],
            options={
                'db_table': 'WebConsultation_Referral_Hdr',
            },
        ),
    ]
