# Generated by Django 3.0.7 on 2022-12-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0010_webconsultation_referral_hdr'),
    ]

    operations = [
        migrations.CreateModel(
            name='TNC_Master',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sno', models.CharField(blank=True, db_column='SNo', max_length=20, null=True)),
                ('isactive', models.BooleanField(db_column='isActive', default=True)),
                ('english', models.CharField(blank=True, db_column='English', max_length=2000, null=True)),
                ('otherlanguage', models.CharField(blank=True, db_column='OtherLanguage', max_length=2000, null=True)),
            ],
            options={
                'db_table': 'TNC_Master',
                'unique_together': {('english',)},
            },
        ),
    ]
