# Generated by Django 3.0.7 on 2022-12-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0012_tnc_detail_tnc_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnc_detail',
            name='dt_lineno',
            field=models.IntegerField(blank=True, db_column='dt_LineNo', null=True),
        ),
        migrations.AddField(
            model_name='tnc_header',
            name='consultant_code',
            field=models.CharField(blank=True, db_column='ConsultantCode', max_length=20, null=True),
        ),
    ]
