# Generated by Django 3.0.7 on 2022-12-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0013_auto_20221207_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebConsultation_Dtl',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('doc_no', models.CharField(blank=True, db_column='DocNo', max_length=255, null=True)),
                ('question_number', models.CharField(blank=True, db_column='questionNumber', max_length=10, null=True)),
                ('answer', models.IntegerField(blank=True, db_column='answer', null=True)),
                ('answer_text', models.CharField(blank=True, db_column='answerText', max_length=200, null=True)),
            ],
            options={
                'db_table': 'WebConsultation_Dtl',
            },
        ),
    ]
