# Generated by Django 3.0.7 on 2022-12-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0014_webconsultation_dtl'),
    ]

    operations = [
        migrations.AddField(
            model_name='webconsultation_question',
            name='question_text',
            field=models.IntegerField(blank=True, db_column='QuestionText', null=True),
        ),
    ]
