# Generated by Django 3.0.7 on 2022-12-20 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0015_webconsultation_question_question_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebConsultation_QuestionMultichoice',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('choice', models.CharField(blank=True, db_column='choice', max_length=100, null=True)),
                ('questionid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_ipad.WebConsultation_Question')),
            ],
            options={
                'db_table': 'WebConsultation_QuestionMultichoice',
            },
        ),
    ]
