# Generated by Django 3.0.7 on 2022-12-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0016_webconsultation_questionmultichoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='arm_remark',
            field=models.CharField(blank=True, db_column='ArmRemark', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='buttock_remark',
            field=models.CharField(blank=True, db_column='ButtockRemark', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='create_by',
            field=models.CharField(blank=True, db_column='CreateBy', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='face_eyearea',
            field=models.CharField(blank=True, db_column='FaceEyeArea', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='face_facearea',
            field=models.CharField(blank=True, db_column='FaceFaceArea', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='face_forehead',
            field=models.CharField(blank=True, db_column='FaceForeHead', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='face_neckarea',
            field=models.CharField(blank=True, db_column='FaceNeckArea', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='face_nosearea',
            field=models.CharField(blank=True, db_column='FaceNoseArea', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='face_remark',
            field=models.CharField(blank=True, db_column='FaceRemark', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='last_updateby',
            field=models.CharField(blank=True, db_column='LastUpdateBy', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='lower_legremark',
            field=models.CharField(blank=True, db_column='LowerLegRemark', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='rounded_shoulderremark',
            field=models.CharField(blank=True, db_column='RoundedShoulderRemark', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='site_code',
            field=models.CharField(blank=True, db_column='SiteCode', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='therapist_id',
            field=models.CharField(blank=True, db_column='TherapistID', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='thigh_remark',
            field=models.CharField(blank=True, db_column='ThighRemark', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='tummy_remark',
            field=models.CharField(blank=True, db_column='TummyRemark', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_analysisresult',
            name='waist_remark',
            field=models.CharField(blank=True, db_column='WaistRemark', max_length=500, null=True),
        ),
    ]
