# Generated by Django 3.0.7 on 2023-01-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0017_auto_20221223_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webconsultation_question',
            name='question_text',
            field=models.CharField(blank=True, db_column='QuestionText', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='webconsultation_question',
            name='question_type',
            field=models.CharField(blank=True, db_column='QuestionType', max_length=500, null=True),
        ),
    ]
