# Generated by Django 3.0.7 on 2023-03-17 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0018_auto_20230102_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnc_master',
            name='is_declaration',
            field=models.BooleanField(db_column='Declaration', null=True),
        ),
        migrations.AddField(
            model_name='tnc_master',
            name='mandatory',
            field=models.BooleanField(db_column='Mandatory', null=True),
        ),
        migrations.AddField(
            model_name='tnc_master',
            name='tnctext1',
            field=models.CharField(blank=True, db_column='Tnctext1', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tnc_master',
            name='tnctext2',
            field=models.CharField(blank=True, db_column='Tnctext2', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='webconsultation_dtl',
            name='image',
            field=models.ImageField(blank=True, db_column='image', max_length=255, null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='webconsultation_dtl',
            name='page_number',
            field=models.IntegerField(blank=True, db_column='PageNumber', null=True),
        ),
        migrations.AddField(
            model_name='webconsultation_dtl',
            name='pic_data1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webconsultation_dtl',
            name='subquestion_number',
            field=models.CharField(blank=True, db_column='subquestionNumber', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='webconsultation_hdr',
            name='signature',
            field=models.ImageField(blank=True, db_column='Signature', null=True, upload_to='img'),
        ),
        migrations.AddField(
            model_name='webconsultation_question',
            name='declaration_text',
            field=models.TextField(blank=True, db_column='Declaration_Text', null=True),
        ),
        migrations.AddField(
            model_name='webconsultation_question',
            name='mandatory',
            field=models.BooleanField(db_column='Mandatory', default=False),
        ),
        migrations.AddField(
            model_name='webconsultation_question',
            name='option_type',
            field=models.IntegerField(blank=True, db_column='option_type', null=True),
        ),
        migrations.CreateModel(
            name='WebConsultation_Questionsub_questions',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('options', models.CharField(blank=True, db_column='options', max_length=100, null=True)),
                ('sub_question_english', models.CharField(blank=True, db_column='sub_question_english', max_length=500, null=True)),
                ('sub_question_chinese', models.CharField(blank=True, db_column='sub_question_chinese', max_length=500, null=True)),
                ('questionid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_ipad.WebConsultation_Question')),
            ],
            options={
                'db_table': 'WebConsultation_Questionsub_questions',
            },
        ),
    ]
