# Generated by Django 3.0.7 on 2023-02-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0025_webconsultation_question_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnc_master',
            name='is_declaration',
            field=models.BooleanField(db_column='Declaration', null=True),
        ),
        migrations.AddField(
            model_name='tnc_master',
            name='mandatory',
            field=models.BooleanField(db_column='Mandatory', null=True),
        ),
        migrations.AddField(
            model_name='tnc_master',
            name='tnctext1',
            field=models.CharField(blank=True, db_column='Tnctext1', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tnc_master',
            name='tnctext2',
            field=models.CharField(blank=True, db_column='Tnctext2', max_length=500, null=True),
        ),
    ]
