# Generated by Django 3.0.7 on 2023-03-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0027_auto_20230306_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webconsultation_dtl',
            name='image',
            field=models.ImageField(blank=True, db_column='image', max_length=255, null=True, upload_to='img'),
        ),
    ]
