# Generated by Django 3.0.7 on 2023-03-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0028_auto_20230313_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='webconsultation_dtl',
            name='page_number',
            field=models.IntegerField(blank=True, db_column='PageNumber', null=True),
        ),
    ]
