# Generated by Django 3.0.7 on 2023-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0029_webconsultation_dtl_page_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='webconsultation_question',
            name='declaration_text',
            field=models.TextField(blank=True, db_column='Declaration_Text', null=True),
        ),
    ]
