# Generated by Django 3.0.7 on 2023-08-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0032_auto_20230802_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='webconsultation_analysismaster',
            name='seq',
            field=models.IntegerField(blank=True, db_column='Seq', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='webconsultation_analysismaster',
            unique_together={('field_name', 'display_field_name', 'choice_name')},
        ),
    ]
