# Generated by Django 3.0.7 on 2023-08-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_ipad', '0033_auto_20230802_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='webconsultation_analysismaster',
            name='is_image',
            field=models.BooleanField(db_column='is_image', default=False),
        ),
    ]
