# Generated by Django 3.0.7 on 2020-10-09 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0034_images'),
        ('cl_app', '0003_auto_20201009_1642'),
        ('custom', '0002_auto_20201009_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo_Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Isactive', models.BooleanField(default=True)),
                ('Site_Code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
                ('services', models.ManyToManyField(blank=True, to='cl_table.Stock')),
            ],
            options={
                'db_table': 'Combo_Services',
            },
        ),
    ]
