# Generated by Django 3.0.7 on 2020-10-09 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0034_images'),
        ('custom', '0003_combo_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='Appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Appointment'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='cust_noid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='focreason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.FocReason'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='helper_ids',
            field=models.ManyToManyField(blank=True, related_name='itemhelper', to='cl_table.TmpItemHelper'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='item_uom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.ItemUom'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='itemcodeid',
            field=models.ForeignKey(db_column='itemCodeid', null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Stock'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='itemstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.ItemStatus'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='pos_disc',
            field=models.ManyToManyField(blank=True, to='cl_table.PosDisc'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='products_used',
            field=models.ManyToManyField(blank=True, related_name='salon_product', to='cl_table.Stock'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='sales_staff',
            field=models.ManyToManyField(blank=True, related_name='sales_staff', to='cl_table.Employee'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='service_staff',
            field=models.ManyToManyField(blank=True, related_name='service_staff', to='cl_table.Employee'),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='treatment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Treatment_Master'),
        ),
        migrations.AddField(
            model_name='voucherrecord',
            name='cust_codeid',
            field=models.ForeignKey(db_column='Cust_codeid', null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer'),
        ),
    ]
