# Generated by Django 3.0.7 on 2020-10-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0006_itemcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='workcommpoints',
            field=models.FloatField(blank=True, db_column='WorkCommPoints', default=0.0, null=True),
        ),
    ]
