# Generated by Django 3.0.7 on 2020-10-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0007_itemcart_workcommpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcart',
            name='workcommpoints',
        ),
    ]
