# Generated by Django 3.0.7 on 2020-10-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0009_itemcart_done_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='type',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Top Up', 'Top Up'), ('Sales', 'Sales')], db_column='Type', max_length=10, null=True),
        ),
    ]
