# Generated by Django 3.0.7 on 2020-10-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0068_stock_favorites'),
        ('custom', '0010_itemcart_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='treatment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trmtacc', to='cl_table.TreatmentAccount'),
        ),
    ]
