# Generated by Django 3.0.7 on 2020-10-26 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0071_auto_20201026_1000'),
        ('custom', '0011_itemcart_treatment_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcart',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Treatment', to='cl_table.Treatment'),
        ),
    ]
