# Generated by Django 3.0.7 on 2020-11-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0013_auto_20201029_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcart',
            name='type',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Top Up', 'Top Up'), ('Sales', 'Sales'), ('VT-Deposit', 'VT-Deposit'), ('VT-Top Up', 'VT-Top Up'), ('VT-Sales', 'VT-Sales')], db_column='Type', max_length=10, null=True),
        ),
    ]
