# Generated by Django 3.0.7 on 2020-11-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0015_itemcart_is_foc'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo_services',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='combo_services',
            name='unit_price',
            field=models.FloatField(db_column='Unit_Price', null=True),
        ),
    ]
