# Generated by Django 3.0.7 on 2020-12-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0016_auto_20201123_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherrecord',
            name='sa_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
