# Generated by Django 3.0.7 on 2021-01-23 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0017_auto_20201201_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosPackagedeposit',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cas_logno', models.CharField(blank=True, db_column='cas_logNo', max_length=50, null=True)),
                ('sa_date', models.DateTimeField(blank=True, db_column='sa_Date', default=django.utils.timezone.now, editable=False, null=True)),
                ('sa_time', models.DateTimeField(blank=True, db_column='sa_Time', default=django.utils.timezone.now, editable=False, null=True)),
                ('sa_transacno', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=80, null=True)),
                ('price', models.FloatField(blank=True, db_column='Price', null=True)),
                ('discount', models.CharField(blank=True, db_column='Discount', max_length=20, null=True)),
                ('package_code', models.CharField(blank=True, db_column='Package_Code', max_length=20, null=True)),
                ('package_description', models.CharField(blank=True, db_column='Package_Description', max_length=80, null=True)),
                ('qty', models.IntegerField(blank=True, db_column='Qty', null=True)),
                ('unit_price', models.FloatField(blank=True, db_column='Unit_Price', null=True)),
                ('ttl_uprice', models.FloatField(db_column='Ttl_Uprice')),
                ('site_code', models.CharField(db_column='Site_Code', max_length=20)),
                ('dt_lineno', models.IntegerField(blank=True, db_column='dt_LineNo', null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=20, null=True)),
                ('deposit_amt', models.FloatField(db_column='Deposit_Amt')),
                ('deposit_lineno', models.IntegerField(blank=True, db_column='Deposit_LineNo', null=True)),
                ('hold_qty', models.FloatField(blank=True, db_column='Hold_Qty', null=True)),
            ],
            options={
                'db_table': 'POS_PackageDeposit',
            },
        ),
    ]
