# Generated by Django 3.0.7 on 2021-01-23 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0018_pospackagedeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='pospackagedeposit',
            name='auto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pospackagedeposit',
            name='itemcart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ItemCart'),
        ),
        migrations.AlterField(
            model_name='pospackagedeposit',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED')], db_column='Status', max_length=20, null=True),
        ),
    ]
