# Generated by Django 3.0.7 on 2021-04-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0019_auto_20210123_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcart',
            name='type',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Top Up', 'Top Up'), ('Sales', 'Sales'), ('VT-Deposit', 'VT-Deposit'), ('VT-Top Up', 'VT-Top Up'), ('VT-Sales', 'VT-Sales'), ('Exchange', 'Exchange')], db_column='Type', max_length=10, null=True),
        ),
    ]
