# Generated by Django 3.0.7 on 2021-05-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_app', '0036_usagelevel_optional'),
        ('custom', '0020_auto_20210409_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpSettings',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sender_name', models.CharField(blank=True, db_column='Sender_Name', max_length=200, null=True)),
                ('sender_address', models.CharField(blank=True, db_column='Sender_Address', max_length=200, null=True)),
                ('smtp_serverhost', models.CharField(blank=True, db_column='Smtp_Serverhost', max_length=500, null=True)),
                ('port', models.CharField(blank=True, db_column='Port', max_length=100, null=True)),
                ('user_email', models.EmailField(blank=True, db_column='User_Email', max_length=255, null=True)),
                ('user_password', models.CharField(blank=True, db_column='User_Password', max_length=15, null=True)),
                ('email_use_ssl', models.BooleanField(db_column='EMAIL_USE_SSL', default=True)),
                ('email_use_tls', models.BooleanField(db_column='EMAIL_USE_TLS', default=False)),
                ('email_subject', models.CharField(blank=True, db_column='Email_Subject', max_length=300, null=True)),
                ('email_content', models.TextField(blank=True, db_column='Email_Content', null=True)),
                ('site_code', models.CharField(blank=True, db_column='Site_Code', max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('site_codeid', models.ForeignKey(db_column='Site_Codeid', null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_app.ItemSitelist')),
            ],
            options={
                'db_table': 'smtp_settings',
            },
        ),
    ]
