# Generated by Django 3.0.7 on 2021-05-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0021_smtpsettings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='smtpsettings',
            unique_together={('site_code',)},
        ),
    ]
