# Generated by Django 3.0.7 on 2021-05-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0022_auto_20210503_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='smtpsettings',
            name='sms_content',
            field=models.TextField(blank=True, db_column='Sms_Content', null=True),
        ),
    ]
