# Generated by Django 3.0.7 on 2021-06-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0033_itemcart_is_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='isopen_prepaid',
            field=models.BooleanField(db_column='isOpen_Prepaid', default=False),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='prepaid_value',
            field=models.FloatField(blank=True, db_column='Prepaid_Value', null=True),
        ),
    ]
