# Generated by Django 3.0.7 on 2021-06-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0034_auto_20210621_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcart',
            name='prepaid_value',
            field=models.FloatField(blank=True, db_column='Prepaid_Value', default=0.0, null=True),
        ),
    ]
