# Generated by Django 3.0.7 on 2021-07-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0036_auto_20210621_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='sessiondone',
            field=models.CharField(blank=True, db_column='Session_Done', max_length=700, null=True),
        ),
    ]
