# Generated by Django 3.0.7 on 2021-07-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0125_auto_20210707_1707'),
        ('custom', '0037_itemcart_sessiondone'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='multi_treat',
            field=models.ManyToManyField(blank=True, to='cl_table.Treatment'),
        ),
    ]
