# Generated by Django 3.0.7 on 2021-07-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0038_itemcart_multi_treat'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='itemtype',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='recorddetail',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
