# Generated by Django 3.0.7 on 2021-07-17 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0039_auto_20210712_1439'),
        ('custom', '0027_auto_20210516_2145'),
    ]

    operations = [
    ]
