# Generated by Django 3.0.7 on 2021-08-02 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0040_merge_20210717_2038'),
        ('custom', '0040_merge_20210719_1443'),
    ]

    operations = [
    ]
