# Generated by Django 3.0.7 on 2021-09-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0041_merge_20210802_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='is_service',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
