# Generated by Django 3.0.7 on 2021-10-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0042_itemcart_is_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='salesStaffChangeLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sa_transacno', models.CharField(db_column='sa_transacNo', max_length=20, null=True)),
                ('item_code', models.CharField(db_column='Item_Code', max_length=20, null=True)),
                ('emp_code', models.CharField(db_column='Emp_Code', max_length=20, null=True)),
                ('ratio', models.FloatField(db_column='Ratio', null=True)),
                ('salesamt', models.FloatField(db_column='SalesAmt', null=True)),
                ('newempcode', models.CharField(db_column='NewEmp_Code', max_length=20, null=True)),
                ('newratio', models.FloatField(db_column='NewRatio', null=True)),
                ('newsalesamt', models.FloatField(db_column='NewSalesAmt', null=True)),
                ('dt_lineno', models.IntegerField(db_column='Dt_LineNo', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'salesStaffChangeLog',
            },
        ),
    ]
