# Generated by Django 3.0.7 on 2021-10-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0043_salesstaffchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceStaffChangeLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sa_transacno', models.CharField(db_column='sa_transacNo', max_length=20, null=True)),
                ('item_code', models.CharField(db_column='Item_Code', max_length=20, null=True)),
                ('emp_code', models.CharField(db_column='Emp_Code', max_length=20, null=True)),
                ('amount', models.FloatField(blank=True, db_column='Amount', null=True)),
                ('share_amt', models.FloatField(blank=True, db_column='Share_Amt', null=True)),
                ('work_amt', models.FloatField(blank=True, db_column='Work_Amount', null=True)),
                ('newempcode', models.CharField(db_column='NewEmp_Code', max_length=20, null=True)),
                ('newamount', models.FloatField(blank=True, db_column='NewAmount', null=True)),
                ('newshareamt', models.FloatField(blank=True, db_column='NewShare_Amt', null=True)),
                ('newworkamt', models.FloatField(blank=True, db_column='NewWork_Amount', null=True)),
                ('line_no', models.IntegerField(db_column='Line_No', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'serviceStaffChangeLog',
            },
        ),
        migrations.AddField(
            model_name='salesstaffchangelog',
            name='newsalescommpoints',
            field=models.FloatField(blank=True, db_column='NewSalesCommPoints', null=True),
        ),
        migrations.AddField(
            model_name='salesstaffchangelog',
            name='salescommpoints',
            field=models.FloatField(blank=True, db_column='SalesCommPoints', null=True),
        ),
    ]
