# Generated by Django 3.0.7 on 2021-10-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0167_treatmentduration'),
        ('custom', '0044_auto_20211020_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesstaffchangelog',
            name='itemsite_code',
            field=models.CharField(db_column='itemsite_code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='servicestaffchangelog',
            name='itemsite_code',
            field=models.CharField(db_column='itemsite_code', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='payModeChangeLog',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('sa_transacno', models.CharField(blank=True, max_length=20, null=True)),
                ('paytype', models.CharField(blank=True, max_length=30, null=True)),
                ('payamt', models.FloatField(blank=True, null=True)),
                ('newpaytype', models.CharField(blank=True, max_length=30, null=True)),
                ('newpayamt', models.FloatField(blank=True, null=True)),
                ('dt_lineno', models.IntegerField(null=True)),
                ('itemsite_code', models.CharField(db_column='itemsite_code', max_length=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('taudid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.PosTaud')),
            ],
            options={
                'db_table': 'payModeChangeLog',
            },
        ),
    ]
