# Generated by Django 3.0.7 on 2021-12-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0046_datechangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='POModel',
            fields=[
                ('PO_ID', models.AutoField(db_column='PO_ID', primary_key=True, serialize=False)),
                ('PO_NO', models.CharField(blank=True, db_column='PO_NO', default='', max_length=255, null=True)),
                ('ItemSite_Code', models.CharField(blank=True, db_column='ItemSite_Code', default='', max_length=255, null=True)),
                ('SUPP_Code', models.CharField(blank=True, db_column='SUPP_Code', default='', max_length=255, null=True)),
                ('PO_REF', models.CharField(blank=True, db_column='PO_REF', default='', max_length=255, null=True)),
                ('PO_User', models.CharField(blank=True, db_column='PO_User', default='', max_length=255, null=True)),
                ('PO_DATE', models.DateTimeField(db_column='PO_DATE', null=True)),
                ('PO_STATUS', models.CharField(blank=True, db_column='PO_STATUS', default='', max_length=255, null=True)),
                ('PO_TTQTY', models.FloatField(blank=True, db_column='PO_TTQTY', null=True)),
                ('PO_TTFOC', models.FloatField(blank=True, db_column='PO_TTFOC', null=True)),
                ('PO_TTDISC', models.FloatField(blank=True, db_column='PO_TTDISC', null=True)),
                ('PO_TTAMT', models.FloatField(blank=True, db_column='PO_TTAMT', null=True)),
                ('PO_ATTN', models.CharField(blank=True, db_column='PO_ATTN', default='', max_length=255, null=True)),
                ('PO_REMK1', models.CharField(blank=True, db_column='PO_REMK1', default='', max_length=255, null=True)),
                ('PO_REMK2', models.CharField(blank=True, db_column='PO_REMK2', default='', max_length=255, null=True)),
                ('PO_BNAME', models.CharField(blank=True, db_column='PO_BNAME', default='', max_length=255, null=True)),
                ('PO_BADDR1', models.CharField(blank=True, db_column='PO_BADDR1', default='', max_length=255, null=True)),
                ('PO_BADDR2', models.CharField(blank=True, db_column='PO_BADDR2', default='', max_length=255, null=True)),
                ('PO_BADDR3', models.CharField(blank=True, db_column='PO_BADDR3', default='', max_length=255, null=True)),
                ('PO_BPOSTCODE', models.CharField(blank=True, db_column='PO_BPOSTCODE', default='', max_length=255, null=True)),
                ('PO_BSTATE', models.CharField(blank=True, db_column='PO_BSTATE', default='', max_length=255, null=True)),
                ('PO_BCITY', models.CharField(blank=True, db_column='PO_BCITY', default='', max_length=255, null=True)),
                ('PO_BCOUNTRY', models.CharField(blank=True, db_column='PO_BCOUNTRY', default='', max_length=255, null=True)),
                ('PO_DADDR1', models.CharField(blank=True, db_column='PO_DADDR1', default='', max_length=255, null=True)),
                ('PO_DADDR2', models.CharField(blank=True, db_column='PO_DADDR2', default='', max_length=255, null=True)),
                ('PO_DADDR3', models.CharField(blank=True, db_column='PO_DADDR3', default='', max_length=255, null=True)),
                ('PO_DPOSTCODE', models.CharField(blank=True, db_column='PO_DPOSTCODE', default='', max_length=255, null=True)),
                ('PO_DSTATE', models.CharField(blank=True, db_column='PO_DSTATE', default='', max_length=255, null=True)),
                ('PO_DCITY', models.CharField(blank=True, db_column='PO_DCITY', default='', max_length=255, null=True)),
                ('PO_DCOUNTRY', models.CharField(blank=True, db_column='PO_DCOUNTRY', default='', max_length=255, null=True)),
                ('PO_CANCELQTY', models.FloatField(blank=True, db_column='PO_CANCELQTY', null=True)),
                ('PO_RECSTATUS', models.CharField(blank=True, db_column='PO_RECSTATUS', default='', max_length=255, null=True)),
                ('PO_RECEXPECT', models.DateTimeField(db_column='PO_RECEXPECT', null=True)),
                ('PO_RECTTL', models.FloatField(blank=True, db_column='PO_RECTTL', null=True)),
                ('PO_TIME', models.DateTimeField(db_column='PO_TIME', null=True)),
                ('REQ_NO', models.CharField(blank=True, db_column='REQ_NO', default='', max_length=255, null=True)),
                ('contactPerson', models.CharField(blank=True, db_column='contactPerson', default='', max_length=255, null=True)),
                ('terms', models.CharField(blank=True, db_column='terms', default='', max_length=255, null=True)),
                ('IsApproved', models.IntegerField(blank=True, db_column='IsApproved', null=True)),
                ('PersonApproved', models.CharField(blank=True, db_column='PersonApproved', default='', max_length=255, null=True)),
                ('DO_NO', models.CharField(blank=True, db_column='DO_NO', default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'PO',
            },
        ),
    ]
