# Generated by Django 3.0.7 on 2021-12-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0047_pomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropdownModel',
            fields=[
                ('id', models.AutoField(db_column='Dropdown_ID', primary_key=True, serialize=False)),
                ('dropdown_item', models.CharField(blank=True, db_column='Dropdown_Item', default='', max_length=255, null=True)),
                ('dropdown_desc', models.CharField(blank=True, db_column='Dropdown_Desc', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Dropdown_List',
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(db_column='Project_ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Project_Title', default='', max_length=255, null=True)),
                ('desc', models.CharField(blank=True, db_column='Project_Desc', default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Project_Status', default='', max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, db_column='Customer_Name', default='', max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, db_column='Contact_Person', default='', max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, db_column='Contact_Number', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='Project_Date', null=True)),
            ],
            options={
                'db_table': 'Project_List',
            },
        ),
        migrations.CreateModel(
            name='QuotationModel',
            fields=[
                ('id', models.AutoField(db_column='Quotation_ID', primary_key=True, serialize=False)),
                ('quotation_number', models.CharField(blank=True, db_column='Quotation_Number', default='', max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_column='Quotation_Project', default='', max_length=255, null=True)),
                ('company', models.CharField(blank=True, db_column='Quotation_Company', default='', max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, db_column='Quotation_ContactPerson', default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Quotation_Status', default='', max_length=255, null=True)),
                ('validity', models.CharField(blank=True, db_column='Quotation_Validity', default='', max_length=255, null=True)),
                ('terms', models.CharField(blank=True, db_column='Quotation_Terms', default='', max_length=255, null=True)),
                ('in_charge', models.CharField(blank=True, db_column='Quotation_InCharge', default='', max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Quotation_Remarks', default='', max_length=255, null=True)),
                ('footer', models.CharField(blank=True, db_column='Quotation_Footer', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_column='Quotation_Date', null=True)),
                ('fk_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ProjectModel')),
            ],
            options={
                'db_table': 'Quotation_List',
            },
        ),
        migrations.CreateModel(
            name='TimeLogModel',
            fields=[
                ('id', models.AutoField(db_column='TimeLog_ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='TimeLog_Username', default='', max_length=255, null=True)),
                ('createormodify', models.CharField(blank=True, db_column='CreateOrModify', default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='TimeLog_Date', null=True)),
                ('fk_po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.POModel')),
                ('fk_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ProjectModel')),
                ('fk_quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.QuotationModel')),
            ],
            options={
                'db_table': 'TimeLog',
            },
        ),
        migrations.CreateModel(
            name='QuotationItemModel',
            fields=[
                ('id', models.AutoField(db_column='Quotation_Item_ID', primary_key=True, serialize=False)),
                ('quotation_quantity', models.CharField(blank=True, db_column='Quotation_Item_Quantity', default='', max_length=255, null=True)),
                ('quotation_unitprice', models.CharField(blank=True, db_column='Quotation_Item_UnitPrice', default='', max_length=255, null=True)),
                ('quotation_itemremarks', models.CharField(blank=True, db_column='Quotation_Item_Remarks', default='', max_length=255, null=True)),
                ('quotation_itemcode', models.CharField(blank=True, db_column='Quotation_Item_Code', default='', max_length=255, null=True)),
                ('quotation_itemdesc', models.CharField(blank=True, db_column='Quotation_Item_Desc', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_quotation', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.QuotationModel')),
            ],
            options={
                'db_table': 'Quotation_Item',
            },
        ),
        migrations.CreateModel(
            name='QuotationDetailModel',
            fields=[
                ('id', models.AutoField(db_column='Quotation_Detail_ID', primary_key=True, serialize=False)),
                ('q_shipcost', models.CharField(blank=True, db_column='Quotation_ShipCost', default='', max_length=255, null=True)),
                ('q_discount', models.CharField(blank=True, db_column='Quotation_Discount', default='', max_length=255, null=True)),
                ('q_taxes', models.CharField(blank=True, db_column='Quotation_Taxes', default='', max_length=255, null=True)),
                ('q_total', models.CharField(blank=True, db_column='Quotation_Total', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_quotation', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.QuotationModel')),
            ],
            options={
                'db_table': 'Quotation_Detail',
            },
        ),
        migrations.CreateModel(
            name='QuotationAddrModel',
            fields=[
                ('id', models.AutoField(db_column='Quotation_Addr_ID', primary_key=True, serialize=False)),
                ('billto', models.CharField(blank=True, db_column='Quotation_Bill_To', default='', max_length=255, null=True)),
                ('bill_addr1', models.CharField(blank=True, db_column='Quotation_Bill_Addr1', default='', max_length=255, null=True)),
                ('bill_addr2', models.CharField(blank=True, db_column='Quotation_Bill_Addr2', default='', max_length=255, null=True)),
                ('bill_addr3', models.CharField(blank=True, db_column='Quotation_Bill_Addr3', default='', max_length=255, null=True)),
                ('bill_postalcode', models.CharField(blank=True, db_column='Quotation_Bill_PostalCode', default='', max_length=255, null=True)),
                ('bill_city', models.CharField(blank=True, db_column='Quotation_Bill_City', default='', max_length=255, null=True)),
                ('bill_state', models.CharField(blank=True, db_column='Quotation_Bill_State', default='', max_length=255, null=True)),
                ('bill_country', models.CharField(blank=True, db_column='Quotation_Bill_Country', default='', max_length=255, null=True)),
                ('shipto', models.CharField(blank=True, db_column='Quotation_Ship_To', default='', max_length=255, null=True)),
                ('ship_addr1', models.CharField(blank=True, db_column='Quotation_Ship_Addr1', default='', max_length=255, null=True)),
                ('ship_addr2', models.CharField(blank=True, db_column='Quotation_Ship_Addr2', default='', max_length=255, null=True)),
                ('ship_addr3', models.CharField(blank=True, db_column='Quotation_Ship_Addr3', default='', max_length=255, null=True)),
                ('ship_postalcode', models.CharField(blank=True, db_column='Quotation_Ship_PostalCode', default='', max_length=255, null=True)),
                ('ship_city', models.CharField(blank=True, db_column='Quotation_Ship_City', default='', max_length=255, null=True)),
                ('ship_state', models.CharField(blank=True, db_column='Quotation_Ship_State', default='', max_length=255, null=True)),
                ('ship_country', models.CharField(blank=True, db_column='Quotation_Ship_Country', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_quotation', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.QuotationModel')),
            ],
            options={
                'db_table': 'Quotation_Address',
            },
        ),
        migrations.CreateModel(
            name='POItemModel',
            fields=[
                ('id', models.AutoField(db_column='PO_Item_ID', primary_key=True, serialize=False)),
                ('po_quantity', models.CharField(blank=True, db_column='PO_Item_Quantity', default='', max_length=255, null=True)),
                ('po_unitprice', models.CharField(blank=True, db_column='PO_Item_UnitPrice', default='', max_length=255, null=True)),
                ('po_itemremarks', models.CharField(blank=True, db_column='PO_Item_Remarks', default='', max_length=255, null=True)),
                ('po_itemcode', models.CharField(blank=True, db_column='PO_Item_Code', default='', max_length=255, null=True)),
                ('po_itemdesc', models.CharField(blank=True, db_column='PO_Item_Desc', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_po', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.POModel')),
            ],
            options={
                'db_table': 'PurchaseOrder_Item',
            },
        ),
        migrations.CreateModel(
            name='POAddrModel',
            fields=[
                ('id', models.AutoField(db_column='PO_Addr_ID', primary_key=True, serialize=False)),
                ('billto', models.CharField(blank=True, db_column='PO_Bill_To', default='', max_length=255, null=True)),
                ('bill_addr1', models.CharField(blank=True, db_column='PO_Bill_Addr1', default='', max_length=255, null=True)),
                ('bill_addr2', models.CharField(blank=True, db_column='PO_Bill_Addr2', default='', max_length=255, null=True)),
                ('bill_addr3', models.CharField(blank=True, db_column='PO_Bill_Addr3', default='', max_length=255, null=True)),
                ('bill_postalcode', models.CharField(blank=True, db_column='PO_Bill_PostalCode', default='', max_length=255, null=True)),
                ('bill_city', models.CharField(blank=True, db_column='PO_Bill_City', default='', max_length=255, null=True)),
                ('bill_state', models.CharField(blank=True, db_column='PO_Bill_State', default='', max_length=255, null=True)),
                ('bill_country', models.CharField(blank=True, db_column='PO_Bill_Country', default='', max_length=255, null=True)),
                ('shipto', models.CharField(blank=True, db_column='PO_Ship_To', default='', max_length=255, null=True)),
                ('ship_addr1', models.CharField(blank=True, db_column='PO_Ship_Addr1', default='', max_length=255, null=True)),
                ('ship_addr2', models.CharField(blank=True, db_column='PO_Ship_Addr2', default='', max_length=255, null=True)),
                ('ship_addr3', models.CharField(blank=True, db_column='PO_Ship_Addr3', default='', max_length=255, null=True)),
                ('ship_postalcode', models.CharField(blank=True, db_column='PO_Ship_PostalCode', default='', max_length=255, null=True)),
                ('ship_city', models.CharField(blank=True, db_column='PO_Ship_City', default='', max_length=255, null=True)),
                ('ship_state', models.CharField(blank=True, db_column='PO_Ship_State', default='', max_length=255, null=True)),
                ('ship_country', models.CharField(blank=True, db_column='PO_Ship_Country', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_po', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.POModel')),
            ],
            options={
                'db_table': 'PurchaseOrder_Address',
            },
        ),
        migrations.CreateModel(
            name='ActivityModel',
            fields=[
                ('id', models.AutoField(db_column='Activity_ID', primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_column='Activity_Title', default='', max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_column='Creator_Name', default='', max_length=255, null=True)),
                ('activity_type', models.CharField(blank=True, db_column='Activity_Type', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_column='Activity_Date', null=True)),
                ('fk_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ProjectModel')),
            ],
            options={
                'db_table': 'Project_Activities',
            },
        ),
    ]
