# Generated by Django 3.0.7 on 2021-12-10 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0051_itemsupplymodel_movdtlmodel_movhdrmodel_phydtlmodel_phyhdrmodel_supplycontactinfomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemsupplymodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movdtlmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='movhdrmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='phydtlmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='phyhdrmodel',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplycontactinfomodel',
            options={},
        ),
    ]
