# Generated by Django 3.0.7 on 2021-12-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0052_auto_20211210_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='movdtlmodel',
            name='DOCUOMDesc',
            field=models.CharField(blank=True, db_column='DOCUOMDesc', default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movdtlmodel',
            name='itmBrandDesc',
            field=models.CharField(blank=True, db_column='itmBrandDesc', default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movdtlmodel',
            name='itmRangeDesc',
            field=models.CharField(blank=True, db_column='itmRangeDesc', default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movhdrmodel',
            name='PO_NO',
            field=models.CharField(blank=True, db_column='PO_NO', default='', max_length=259, null=True),
        ),
    ]
