# Generated by Django 3.0.7 on 2021-12-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0053_auto_20211210_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_desc', models.CharField(blank=True, max_length=40, null=True)),
                ('itm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_isactive', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'City',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ControlNoModel',
            fields=[
                ('id', models.AutoField(db_column='Control_id', primary_key=True, serialize=False)),
                ('control_prefix', models.CharField(blank=True, db_column='control_prefix', default='', max_length=255, null=True)),
                ('control_description', models.CharField(blank=True, db_column='control_description', default='', max_length=255, null=True)),
                ('control_no', models.CharField(blank=True, db_column='control_no', default='', max_length=255, null=True)),
                ('Site_Code', models.CharField(blank=True, db_column='Site_Code', default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Control_No',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('itm_id', models.AutoField(primary_key=True, serialize=False)),
                ('itm_desc', models.CharField(blank=True, max_length=40, null=True)),
                ('itm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_isactive', models.BooleanField(default=True)),
                ('phonecode', models.CharField(blank=True, db_column='phoneCode', max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('itm_id', models.AutoField(db_column='itm_ID', primary_key=True, serialize=False)),
                ('itm_desc', models.CharField(blank=True, max_length=40, null=True)),
                ('itm_code', models.CharField(blank=True, max_length=10, null=True)),
                ('itm_isactive', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'State',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SystemLogModel',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('Log_Type', models.CharField(blank=True, db_column='Log_Type', default='', max_length=255, null=True)),
                ('Log_DateTime', models.DateTimeField(auto_now_add=True, db_column='Log_DateTime', null=True)),
                ('Log_User', models.CharField(blank=True, db_column='Log_User', default='', max_length=255, null=True)),
                ('Log_Process', models.CharField(blank=True, db_column='Log_Process', default='', max_length=255, null=True)),
                ('Log_Message', models.CharField(blank=True, db_column='Log_Message', default='', max_length=255, null=True)),
                ('Log_Site_Code', models.CharField(blank=True, db_column='Log_Site_Code', default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at', null=True)),
            ],
            options={
                'db_table': 'SystemLog',
                'managed': False,
            },
        ),
    ]
