# Generated by Django 3.0.7 on 2021-12-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0054_city_controlnomodel_country_state_systemlogmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DropdownModel',
        ),
    ]
