# Generated by Django 3.0.7 on 2021-12-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0056_dropdownmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_level', models.CharField(db_column='employee level', max_length=50)),
                ('profile_name', models.CharField(db_column='Profile name', max_length=50)),
                ('gst', models.FloatField(db_column='GST')),
                ('gst_ispercent', models.BooleanField()),
                ('bank_changes', models.FloatField(db_column='Bank changes')),
                ('bc_ispercent', models.BooleanField()),
                ('emi', models.FloatField(db_column='EMI')),
                ('emi_ispercent', models.BooleanField()),
            ],
            options={
                'db_table': 'Comm_deduction',
            },
        ),
        migrations.CreateModel(
            name='CommissionProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_level', models.CharField(db_column='employee level', max_length=50)),
                ('profile_name', models.CharField(db_column='Profile name', max_length=50)),
                ('period', models.CharField(choices=[('1', 'year'), ('2', 'month'), ('3', 'week')], default=None, max_length=20)),
                ('item', models.CharField(db_column='Item', max_length=50)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('min_value', models.FloatField(db_column='Target min')),
                ('max_value', models.FloatField(db_column='Target max')),
                ('commission', models.IntegerField(blank=True, db_column='commission', null=True)),
                ('ispercent', models.BooleanField()),
                ('incentive', models.FloatField(db_column='incentive', null=True)),
                ('incentive_ispercent', models.BooleanField()),
                ('rangee', models.FloatField(db_column='Range')),
                ('brand', models.CharField(db_column='brand', max_length=50)),
                ('department', models.CharField(db_column='Department', max_length=50)),
                ('commission_type', models.CharField(choices=[('1', 'commission'), ('2', 'incentive')], default=None, max_length=20)),
                ('rangee_comm', models.FloatField(blank=True, db_column='Range comm', null=True)),
                ('brand_comm', models.CharField(blank=True, db_column='brand comm', max_length=50, null=True)),
                ('department_comm', models.CharField(blank=True, db_column='Department Comm', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Commission_profile',
            },
        ),
        migrations.CreateModel(
            name='CommTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employe_level', models.CharField(db_column='employee level', max_length=50)),
                ('profile_name', models.CharField(db_column='Profile name', max_length=50)),
                ('from_date_comm', models.DateField(null=True)),
                ('to_date_comm', models.DateField(null=True)),
                ('min_value_comm', models.FloatField(db_column='Target min comm')),
                ('max_value_comm', models.FloatField(db_column='Target max comm')),
                ('commission_comm', models.IntegerField(blank=True, db_column='commission comm', null=True)),
                ('ispercent_comm', models.BooleanField()),
                ('incentive_comm', models.FloatField(blank=True, db_column='incentive comm', null=True)),
                ('incentive_ispercent_comm', models.BooleanField()),
            ],
            options={
                'db_table': 'Comm_target',
            },
        ),
    ]
