# Generated by Django 3.0.7 on 2022-02-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0058_auto_20211221_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('modename', models.CharField(max_length=40)),
                ('accountcode', models.CharField(max_length=10)),
                ('isactive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'modeofpayment',
            },
        ),
        migrations.CreateModel(
            name='SalarySubTypeLookup',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=40)),
                ('accountcode', models.CharField(max_length=10)),
                ('showinallowance', models.BooleanField(default=False)),
                ('showindeduction', models.BooleanField(default=False)),
                ('showinpayment', models.BooleanField(default=False)),
                ('isactive', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'SalarySubTypeLookup',
            },
        ),
    ]
