# Generated by Django 3.0.7 on 2022-02-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0059_modeofpayment_salarysubtypelookup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dropdownmodel',
            old_name='Active',
            new_name='active',
        ),
        migrations.RemoveField(
            model_name='dropdownmodel',
            name='AllDropdown_Desc',
        ),
        migrations.RemoveField(
            model_name='dropdownmodel',
            name='AllDropdown_ID',
        ),
        migrations.RemoveField(
            model_name='dropdownmodel',
            name='AllDropdown_Item',
        ),
        migrations.AddField(
            model_name='dropdownmodel',
            name='dropdown_desc',
            field=models.CharField(blank=True, db_column='Dropdown_Desc', default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dropdownmodel',
            name='dropdown_item',
            field=models.CharField(blank=True, db_column='Dropdown_Item', default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dropdownmodel',
            name='id',
            field=models.AutoField(db_column='Dropdown_ID', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='dropdownmodel',
            table='Dropdown_List',
        ),
    ]
