# Generated by Django 3.0.7 on 2022-02-25 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0062_manualinvoicedetailmodel_manualinvoicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualInvoiceAddrModel',
            fields=[
                ('id', models.AutoField(db_column='ManualInvoice_Addr_ID', primary_key=True, serialize=False)),
                ('billto', models.CharField(blank=True, db_column='ManualInvoice_Bill_To', default='', max_length=255, null=True)),
                ('bill_addr1', models.CharField(blank=True, db_column='ManualInvoice_Bill_Addr1', default='', max_length=255, null=True)),
                ('bill_addr2', models.CharField(blank=True, db_column='ManualInvoice_Bill_Addr2', default='', max_length=255, null=True)),
                ('bill_addr3', models.CharField(blank=True, db_column='ManualInvoice_Bill_Addr3', default='', max_length=255, null=True)),
                ('bill_postalcode', models.CharField(blank=True, db_column='ManualInvoice_Bill_PostalCode', default='', max_length=255, null=True)),
                ('bill_city', models.CharField(blank=True, db_column='ManualInvoice_Bill_City', default='', max_length=255, null=True)),
                ('bill_state', models.CharField(blank=True, db_column='ManualInvoice_Bill_State', default='', max_length=255, null=True)),
                ('bill_country', models.CharField(blank=True, db_column='ManualInvoice_Bill_Country', default='', max_length=255, null=True)),
                ('shipto', models.CharField(blank=True, db_column='ManualInvoice_Ship_To', default='', max_length=255, null=True)),
                ('ship_addr1', models.CharField(blank=True, db_column='ManualInvoice_Ship_Addr1', default='', max_length=255, null=True)),
                ('ship_addr2', models.CharField(blank=True, db_column='ManualInvoice_Ship_Addr2', default='', max_length=255, null=True)),
                ('ship_addr3', models.CharField(blank=True, db_column='ManualInvoice_Ship_Addr3', default='', max_length=255, null=True)),
                ('ship_postalcode', models.CharField(blank=True, db_column='ManualInvoice_Ship_PostalCode', default='', max_length=255, null=True)),
                ('ship_city', models.CharField(blank=True, db_column='ManualInvoice_Ship_City', default='', max_length=255, null=True)),
                ('ship_state', models.CharField(blank=True, db_column='ManualInvoice_Ship_State', default='', max_length=255, null=True)),
                ('ship_country', models.CharField(blank=True, db_column='ManualInvoice_Ship_Country', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_manualinvoice', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ManualInvoiceModel')),
            ],
            options={
                'db_table': 'ManualInvoice_Address',
            },
        ),
    ]
