# Generated by Django 3.0.7 on 2022-03-01 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0064_manualinvoiceitemmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodel',
            old_name='PO_ID',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='DO_NO',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='IsApproved',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='ItemSite_Code',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_ATTN',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_BADDR1',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_BADDR2',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_BADDR3',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_BCITY',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_BCOUNTRY',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_BNAME',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_BPOSTCODE',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_BSTATE',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_CANCELQTY',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_DADDR1',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_DADDR2',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_DADDR3',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_DATE',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_DCITY',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_DCOUNTRY',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_DPOSTCODE',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_DSTATE',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_NO',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_RECEXPECT',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_RECSTATUS',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_RECTTL',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_REF',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_REMK1',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_REMK2',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_STATUS',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_TIME',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_TTAMT',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_TTDISC',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_TTFOC',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_TTQTY',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PO_User',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='PersonApproved',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='REQ_NO',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='SUPP_Code',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='contactPerson',
        ),
        migrations.RemoveField(
            model_name='pomodel',
            name='terms',
        ),
        migrations.AddField(
            model_name='pomodel',
            name='active',
            field=models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='company',
            field=models.CharField(blank=True, db_column='PO_Company', default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='contact_person',
            field=models.CharField(blank=True, db_column='PO_ContactPerson', default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='created_at',
            field=models.DateTimeField(db_column='PO_Date', null=True),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='fk_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ProjectModel'),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='fk_quotation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.QuotationModel'),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='in_charge',
            field=models.CharField(blank=True, db_column='PO_InCharge', default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='po_number',
            field=models.CharField(blank=True, db_column='PO_Number', default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='remarks',
            field=models.CharField(blank=True, db_column='PO_Remarks', default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='status',
            field=models.CharField(blank=True, db_column='PO_Status', default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pomodel',
            name='title',
            field=models.CharField(blank=True, db_column='PO_Project', default='', max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='pomodel',
            table='PurchaseOrder_List',
        ),
    ]
