# Generated by Django 3.0.7 on 2022-03-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0067_workorderinvoicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderInvoiceDetailModel',
            fields=[
                ('id', models.AutoField(db_column='WorkOrderInvoice_Detail_ID', primary_key=True, serialize=False)),
                ('q_shipcost', models.CharField(blank=True, db_column=' WorkOrderInvoice_ShipCost', default='', max_length=255, null=True)),
                ('q_discount', models.CharField(blank=True, db_column=' WorkOrderInvoice_Discount', default='', max_length=255, null=True)),
                ('q_taxes', models.CharField(blank=True, db_column='WorkOrderInvoice_Taxes', default='', max_length=255, null=True)),
                ('q_total', models.CharField(blank=True, db_column=' WorkOrderInvoice_Total', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_workorderinvoice', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.WorkOrderInvoiceModel')),
            ],
            options={
                'db_table': 'WorkOrderInvoice_Detail',
            },
        ),
    ]
