# Generated by Django 3.0.7 on 2022-03-01 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0069_workorderinvoiceaddrmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderInvoiceItemModel',
            fields=[
                ('id', models.AutoField(db_column='WorkOrderInvoice_Item_ID', primary_key=True, serialize=False)),
                ('quotation_quantity', models.CharField(blank=True, db_column='WorkOrderInvoice_Item_Quantity', default='', max_length=255, null=True)),
                ('quotation_unitprice', models.CharField(blank=True, db_column='WorkOrderInvoice_Item_UnitPrice', default='', max_length=255, null=True)),
                ('quotation_itemremarks', models.CharField(blank=True, db_column='WorkOrderInvoice_Item_Remarks', default='', max_length=255, null=True)),
                ('quotation_itemcode', models.CharField(blank=True, db_column='WorkOrderInvoice_Item_Code', default='', max_length=255, null=True)),
                ('quotation_itemdesc', models.CharField(blank=True, db_column='WorkOrderInvoice_Item_Desc', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_workorderinvoice', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.WorkOrderInvoiceModel')),
            ],
            options={
                'db_table': 'WorkOrderInvoice_Item',
            },
        ),
    ]
