# Generated by Django 3.0.7 on 2022-04-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0070_workorderinvoiceitemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='expiry',
            field=models.DateField(blank=True, db_column='Expiry', null=True),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='treatment_limit_times',
            field=models.FloatField(blank=True, db_column='Treatment_Limit_Times', null=True),
        ),
        migrations.AlterField(
            model_name='itemcart',
            name='type',
            field=models.CharField(blank=True, db_column='Type', max_length=50, null=True),
        ),
    ]
