# Generated by Django 3.0.7 on 2022-04-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0071_auto_20220412_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcart',
            name='expiry',
        ),
        migrations.AddField(
            model_name='itemcart',
            name='is_flexi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='treat_expiry',
            field=models.DateField(blank=True, db_column='Treatment_Expiry', null=True),
        ),
        migrations.AddField(
            model_name='itemcart',
            name='treat_type',
            field=models.CharField(blank=True, db_column='treat_type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itemcart',
            name='type',
            field=models.CharField(blank=True, choices=[('Deposit', 'Deposit'), ('Top Up', 'Top Up'), ('Sales', 'Sales'), ('VT-Deposit', 'VT-Deposit'), ('VT-Top Up', 'VT-Top Up'), ('VT-Sales', 'VT-Sales'), ('Exchange', 'Exchange')], db_column='Type', max_length=10, null=True),
        ),
    ]
