# Generated by Django 3.0.7 on 2022-04-29 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0072_auto_20220412_1455'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='manualinvoicemodel',
            name='cart_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
