# Generated by Django 3.0.7 on 2022-04-29 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0073_auto_20220429_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='quotationitem_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.QuotationItemModel'),
        ),
    ]
