# Generated by Django 3.0.7 on 2022-05-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0074_itemcart_quotationitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderinvoicemodel',
            name='cart_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
