# Generated by Django 3.0.7 on 2022-05-02 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0075_workorderinvoicemodel_cart_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOrderModel',
            fields=[
                ('id', models.AutoField(db_column='DeliveryOrder_ID', primary_key=True, serialize=False)),
                ('do_number', models.CharField(blank=True, db_column='Do_Number', default='', max_length=255, null=True)),
                ('title', models.CharField(blank=True, db_column='Do_Project', default='', max_length=255, null=True)),
                ('company', models.CharField(blank=True, db_column='Do_Company', default='', max_length=255, null=True)),
                ('contact_person', models.CharField(blank=True, db_column='Do_ContactPerson', default='', max_length=255, null=True)),
                ('status', models.CharField(blank=True, db_column='Do_Status', default='', max_length=255, null=True)),
                ('validity', models.CharField(blank=True, db_column='Do_Validity', default='', max_length=255, null=True)),
                ('terms', models.CharField(blank=True, db_column='Do_Terms', default='', max_length=255, null=True)),
                ('in_charge', models.CharField(blank=True, db_column='Do_InCharge', default='', max_length=255, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Do_Remarks', default='', max_length=255, null=True)),
                ('footer', models.CharField(blank=True, db_column='Do_Footer', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_column='Do_Date', null=True)),
                ('fk_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ProjectModel')),
            ],
            options={
                'db_table': 'DeliveryOrder_List',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderItemModel',
            fields=[
                ('id', models.AutoField(db_column='Do_Item_ID', primary_key=True, serialize=False)),
                ('quotation_quantity', models.CharField(blank=True, db_column='Do_Item_Quantity', default='', max_length=255, null=True)),
                ('quotation_unitprice', models.CharField(blank=True, db_column='Do_Item_UnitPrice', default='', max_length=255, null=True)),
                ('quotation_itemremarks', models.CharField(blank=True, db_column='Do_Item_Remarks', default='', max_length=255, null=True)),
                ('quotation_itemcode', models.CharField(blank=True, db_column='Do_Item_Code', default='', max_length=255, null=True)),
                ('quotation_itemdesc', models.CharField(blank=True, db_column='Do_Item_Desc', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_deliveryorder', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.DeliveryOrderModel')),
            ],
            options={
                'db_table': 'DeliveryOrder_Item',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderDetailModel',
            fields=[
                ('id', models.AutoField(db_column='Do_Detail_ID', primary_key=True, serialize=False)),
                ('q_shipcost', models.CharField(blank=True, db_column='Do_ShipCost', default='', max_length=255, null=True)),
                ('q_discount', models.CharField(blank=True, db_column='Do_Discount', default='', max_length=255, null=True)),
                ('q_taxes', models.CharField(blank=True, db_column='Do_Taxes', default='', max_length=255, null=True)),
                ('q_total', models.CharField(blank=True, db_column='Do_Total', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_deliveryorder', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.DeliveryOrderModel')),
            ],
            options={
                'db_table': 'DeliveryOrder_Detail',
            },
        ),
        migrations.CreateModel(
            name='DeliveryOrderAddrModel',
            fields=[
                ('id', models.AutoField(db_column='Do_Addr_ID', primary_key=True, serialize=False)),
                ('billto', models.CharField(blank=True, db_column='Do_Bill_To', default='', max_length=255, null=True)),
                ('bill_addr1', models.CharField(blank=True, db_column='Do_Bill_Addr1', default='', max_length=255, null=True)),
                ('bill_addr2', models.CharField(blank=True, db_column='Do_Bill_Addr2', default='', max_length=255, null=True)),
                ('bill_addr3', models.CharField(blank=True, db_column='Do_Bill_Addr3', default='', max_length=255, null=True)),
                ('bill_postalcode', models.CharField(blank=True, db_column='Do_Bill_PostalCode', default='', max_length=255, null=True)),
                ('bill_city', models.CharField(blank=True, db_column='Do_Bill_City', default='', max_length=255, null=True)),
                ('bill_state', models.CharField(blank=True, db_column='Do_Bill_State', default='', max_length=255, null=True)),
                ('bill_country', models.CharField(blank=True, db_column='Do_Bill_Country', default='', max_length=255, null=True)),
                ('shipto', models.CharField(blank=True, db_column='Do_Ship_To', default='', max_length=255, null=True)),
                ('ship_addr1', models.CharField(blank=True, db_column='Do_Ship_Addr1', default='', max_length=255, null=True)),
                ('ship_addr2', models.CharField(blank=True, db_column='Do_Ship_Addr2', default='', max_length=255, null=True)),
                ('ship_addr3', models.CharField(blank=True, db_column='Do_Ship_Addr3', default='', max_length=255, null=True)),
                ('ship_postalcode', models.CharField(blank=True, db_column='Do_Ship_PostalCode', default='', max_length=255, null=True)),
                ('ship_city', models.CharField(blank=True, db_column='Do_Ship_City', default='', max_length=255, null=True)),
                ('ship_state', models.CharField(blank=True, db_column='Do_Ship_State', default='', max_length=255, null=True)),
                ('ship_country', models.CharField(blank=True, db_column='Do_Ship_Country', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_deliveryorder', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.DeliveryOrderModel')),
            ],
            options={
                'db_table': 'DeliveryOrder_Address',
            },
        ),
    ]
