# Generated by Django 3.0.7 on 2022-05-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0078_deliveryordersign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POAddrModel',
        ),
    ]
