# Generated by Django 3.0.7 on 2022-05-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0080_poaddrmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='admin_staff',
            field=models.CharField(blank=True, db_column='admin_staff', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='operation_staff',
            field=models.CharField(blank=True, db_column='operation_staff', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='sales_staff',
            field=models.CharField(blank=True, db_column='sales_staff', max_length=255, null=True),
        ),
    ]
