# Generated by Django 3.0.7 on 2022-05-09 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0081_auto_20220509_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeLogModel',
        ),
    ]
