# Generated by Django 3.0.7 on 2022-05-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0082_delete_timelogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLogModel',
            fields=[
                ('id', models.AutoField(db_column='TimeLog_ID', primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, db_column='TimeLog_Username', default='', max_length=255, null=True)),
                ('createormodify', models.CharField(blank=True, db_column='CreateOrModify', default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='TimeLog_Date', null=True)),
                ('fk_po', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.POModel')),
                ('fk_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ProjectModel')),
                ('fk_quotation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.QuotationModel')),
            ],
            options={
                'db_table': 'TimeLog',
            },
        ),
    ]
