# Generated by Django 3.0.7 on 2022-05-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0083_timelogmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='POItemModel',
        ),
    ]
