# Generated by Django 3.0.7 on 2022-05-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0085_poitemmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PODetailModel',
        ),
    ]
