# Generated by Django 3.0.7 on 2022-05-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0087_podetailmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualinvoicemodel',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='manualinvoicemodel',
            name='sa_transacno_ref',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
