# Generated by Django 3.0.7 on 2022-05-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0088_auto_20220512_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderinvoicemodel',
            name='cart_id',
        ),
        migrations.AddField(
            model_name='workorderinvoicemodel',
            name='sa_transacno_ref',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
