# Generated by Django 3.0.7 on 2022-05-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0089_auto_20220513_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='is_prepaidused',
            field=models.BooleanField(default=False),
        ),
    ]
