# Generated by Django 3.0.7 on 2022-05-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0093_equipmentdropdownmodel_equipmentusage_equipmentusageitemmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentusage',
            name='is_issued',
            field=models.BooleanField(default=False),
        ),
    ]
