# Generated by Django 3.0.7 on 2022-06-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0242_custlogaudit'),
        ('custom', '0094_equipmentusage_is_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentusage',
            name='emp_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Employee'),
        ),
    ]
