# Generated by Django 3.0.7 on 2022-06-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0243_employee_isdelete'),
        ('custom', '0098_auto_20220613_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentusageitemmodel',
            name='cust_id',
        ),
        migrations.AddField(
            model_name='equipmentusage',
            name='cust_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.Customer'),
        ),
    ]
