# Generated by Django 3.0.7 on 2022-06-24 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0101_quotationmodel_currency_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationPayment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('payment_schedule', models.CharField(blank=True, db_column='payment_schedule', default='', max_length=255, null=True)),
                ('payment_term', models.CharField(blank=True, db_column='payment_term', default='', max_length=255, null=True)),
                ('active', models.CharField(blank=True, db_column='Active', default='active', max_length=255, null=True)),
                ('fk_quotation', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.QuotationModel')),
            ],
            options={
                'db_table': 'Quotation_Payment',
            },
        ),
    ]
