# Generated by Django 3.0.7 on 2022-06-24 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0103_auto_20220624_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualinvoicemodel',
            name='currency_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.Currencytable'),
        ),
    ]
