# Generated by Django 3.0.7 on 2022-06-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0105_auto_20220624_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationmodel',
            name='rev_quoteno',
            field=models.CharField(blank=True, db_column='rev_quoteno', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='quotationmodel',
            name='revision',
            field=models.IntegerField(blank=True, db_column='revision', null=True),
        ),
    ]
