# Generated by Django 3.0.7 on 2022-06-29 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0107_auto_20220629_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posdiscquant',
            name='quotationitem_id',
        ),
    ]
