# Generated by Django 3.0.7 on 2022-06-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0108_remove_posdiscquant_quotationitem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationitemmodel',
            name='discreason_txt',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
