# Generated by Django 3.0.7 on 2022-07-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0109_auto_20220629_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencytable',
            name='curr_isactive',
            field=models.BooleanField(db_column='Curr_isactive', default=True),
        ),
    ]
