# Generated by Django 3.0.7 on 2022-07-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0112_auto_20220713_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationitemmodel',
            name='additional_discount',
        ),
        migrations.RemoveField(
            model_name='quotationitemmodel',
            name='additional_discountamt',
        ),
        migrations.RemoveField(
            model_name='quotationitemmodel',
            name='auto',
        ),
        migrations.RemoveField(
            model_name='quotationitemmodel',
            name='disc_reason',
        ),
        migrations.RemoveField(
            model_name='quotationitemmodel',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='quotationitemmodel',
            name='discount_amt',
        ),
        migrations.RemoveField(
            model_name='quotationitemmodel',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='quotationitemmodel',
            name='discreason_txt',
        ),
        migrations.RemoveField(
            model_name='quotationitemmodel',
            name='pos_disc',
        ),
        migrations.RemoveField(
            model_name='quotationitemmodel',
            name='trans_amt',
        ),
    ]
