# Generated by Django 3.0.7 on 2022-07-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0113_auto_20220715_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualinvoiceitemmodel',
            name='discount_amt',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='manualinvoiceitemmodel',
            name='discount_percent',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='quotationitemmodel',
            name='discount_amt',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='quotationitemmodel',
            name='discount_percent',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
