# Generated by Django 3.0.7 on 2022-08-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0114_auto_20220722_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualinvoicedetailmodel',
            name='q_discpercent',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='quotationdetailmodel',
            name='q_discpercent',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
