# Generated by Django 3.0.7 on 2022-09-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0115_auto_20220801_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundsales',
            name='site_code',
            field=models.CharField(blank=True, db_column='Site_Code', max_length=500, null=True),
        ),
    ]
