# Generated by Django 3.0.7 on 2022-09-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0116_roundsales_site_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualinvoicemodel',
            name='quotation_number',
            field=models.CharField(blank=True, db_column='Quotation_Number', default='', max_length=255, null=True),
        ),
    ]
