# Generated by Django 3.0.7 on 2022-10-05 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0117_manualinvoicemodel_quotation_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryordersign',
            name='deliveryorder_no',
            field=models.CharField(blank=True, db_column='DeliveryOrder_No', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='ManualInvoicesign',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('manualinv_number', models.CharField(blank=True, db_column='ManualInvoice_Number', default='', max_length=255, null=True)),
                ('manualinv_sig', models.ImageField(blank=True, db_column='manualinv_sig', null=True, upload_to='img')),
                ('fk_manualinvoice', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.ManualInvoiceModel')),
            ],
            options={
                'db_table': 'ManualInvoicesign',
            },
        ),
    ]
