# Generated by Django 3.0.7 on 2022-10-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0118_auto_20221005_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualinvoicemodel',
            name='isxeroposted',
            field=models.BooleanField(db_column='isxeroposted', default=False, null=True),
        ),
    ]
