# Generated by Django 3.0.7 on 2022-10-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0119_manualinvoicemodel_isxeroposted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualinvoicemodel',
            name='isxeroposted',
            field=models.BooleanField(db_column='isxeroposted', default=False),
        ),
    ]
