# Generated by Django 3.0.7 on 2022-10-11 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0292_auto_20221007_1158'),
        ('custom', '0120_auto_20221010_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcart',
            name='exchange_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cl_table.ExchangeDtl'),
        ),
    ]
