# Generated by Django 3.0.7 on 2022-11-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0122_itemcart_addstaff_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcart',
            name='batch_sno',
            field=models.CharField(blank=True, db_column='BATCH_SNO', max_length=300, null=True),
        ),
    ]
