# Generated by Django 3.0.7 on 2022-12-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0123_itemcart_batch_sno'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherrecord',
            name='conditiontype1',
            field=models.CharField(blank=True, db_column='conditiontype1', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voucherrecord',
            name='conditiontype2',
            field=models.CharField(blank=True, db_column='conditiontype2', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voucherrecord',
            name='isdiscount',
            field=models.BooleanField(db_column='isdiscount', default=False),
        ),
    ]
