# Generated by Django 3.0.7 on 2023-01-12 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0126_auto_20230110_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commdeduction',
            name='comm_Profilede_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.CommissionProfile'),
        ),
        migrations.AlterField(
            model_name='commdeduction',
            name='employe_level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom.EmpLevel'),
        ),
        migrations.AlterField(
            model_name='commissionprofile',
            name='brand_comm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='range_brand', to='custom.ItemBrandModel'),
        ),
        migrations.AlterField(
            model_name='commissionprofile',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom.ItemBrandModel'),
        ),
        migrations.AlterField(
            model_name='commissionprofile',
            name='department_comm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='range_dept', to='custom.ItemDeptModel'),
        ),
        migrations.AlterField(
            model_name='commissionprofile',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_department', to='custom.ItemDeptModel'),
        ),
        migrations.AlterField(
            model_name='commissionprofile',
            name='employe_level_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.EmpLevel'),
        ),
        migrations.AlterField(
            model_name='commissionprofile',
            name='range_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom.ItemRangeModel'),
        ),
        migrations.AlterField(
            model_name='commissionprofile',
            name='rangee_comm_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='range_commission', to='custom.ItemRangeModel'),
        ),
        migrations.AlterField(
            model_name='commtarget',
            name='comm_Profile_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='custom.CommissionProfile'),
        ),
        migrations.AlterField(
            model_name='commtarget',
            name='employe_level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='custom.EmpLevel'),
        ),
    ]
