# Generated by Django 3.0.7 on 2023-01-12 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cl_table', '0319_auto_20230112_1339'),
        ('custom', '0127_auto_20230112_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcart',
            name='exchange_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cl_table.ExchangeDtl'),
        ),
    ]
