# Generated by Django 3.0.7 on 2023-06-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0128_auto_20230112_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymodechangelog',
            name='taudid',
        ),
        migrations.AddField(
            model_name='smtpsettings',
            name='isactive',
            field=models.BooleanField(db_column='Isactive', default=True),
        ),
    ]
